'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, Clock3, KeyRound, Loader2, Plus, ShieldAlert, UserRound, XCircle } from 'lucide-react';

type Access = { id: string; status: string; auditPeriodStart: string; auditPeriodEnd: string; accessExpiresAt: string; user: { email: string }; property: { name: string; code: string }; grantedByUser: { email: string } };
type Engagement = { id: string; name: string; auditType: string; status: string; auditPeriodStart: string; auditPeriodEnd: string };
type Option = { id: string; email?: string; name?: string; code?: string };
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function ExternalAuditorManagementPage() {
  const [accesses, setAccesses] = useState<Access[]>([]); const [engagements, setEngagements] = useState<Engagement[]>([]); const [users, setUsers] = useState<Option[]>([]); const [properties, setProperties] = useState<Option[]>([]); const [showForm, setShowForm] = useState(false); const [showEngagementForm, setShowEngagementForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = () => { setLoading(true); void Promise.all([fetch('/api/v1/external-auditor/access').then(async r => { const v = await r.json(); if (!r.ok) throw new Error(v.error || 'Unable to load access'); return v; }), fetch('/api/v1/external-auditor/management?resource=engagements').then(r => r.json())]).then(([a, e]) => { setAccesses(a.accesses || []); setUsers(a.users || []); setProperties(a.properties || []); setEngagements(e.items || []); }).catch(e => setError(e.message)).finally(() => setLoading(false)); };
  // The register hydrates from the live access and engagement APIs on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>, resource: string) => { event.preventDefault(); setSaving(true); const body = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(resource === 'access' ? '/api/v1/external-auditor/access' : '/api/v1/external-auditor/management', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(resource === 'access' ? body : { resource: 'engagement', ...body }) }); const value = await response.json(); if (!response.ok) setError(value.error || 'Unable to save'); else { event.currentTarget.reset(); setShowForm(false); setShowEngagementForm(false); load(); } setSaving(false); };
  const revoke = async (id: string) => { if (!window.confirm('Revoke this auditor access?')) return; await updateAccess({ id, action: 'revoke', reason: 'Revoked by administrator' }); };
  const extend = async (access: Access) => { const expiry = window.prompt('New expiry in ISO format', new Date(new Date(access.accessExpiresAt).getTime() + 7 * 86400000).toISOString()); if (expiry) await updateAccess({ id: access.id, action: 'extend', accessExpiresAt: expiry }); };
  const updateAccess = async (body: Record<string, string>) => { const response = await fetch('/api/v1/external-auditor/access', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) { const value = await response.json(); setError(value.error || 'Unable to update access'); } else load(); };
  return <div className="min-h-screen bg-slate-950 px-5 py-8 text-slate-200 sm:px-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><KeyRound className="h-4 w-4" /> Governance & access</div><h1 className="text-3xl font-semibold tracking-tight text-white">External auditor management</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Create engagements, grant least-privilege access, and keep the full lifecycle visible.</p></div><div className="flex gap-2"><button onClick={() => { setShowEngagementForm(v => !v); setShowForm(false); }} className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-slate-200"><Plus className="h-4 w-4 text-emerald-300" /> New engagement</button><button onClick={() => { setShowForm(v => !v); setShowEngagementForm(false); }} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-300 px-4 text-sm font-semibold text-slate-950"><Plus className="h-4 w-4" /> Grant access</button></div></header>{error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    {showEngagementForm && <form onSubmit={event => void submit(event, 'engagement')} className="rounded-2xl border border-violet-300/20 bg-violet-300/[.04] p-5"><h2 className="mb-4 font-semibold text-white">Create audit engagement</h2><div className="grid gap-3 md:grid-cols-2"><input required name="name" placeholder="Engagement name" className="field" /><input required name="auditType" placeholder="Audit type" className="field" /><select required name="propertyId" className="field"><option value="">Select property</option>{properties.map(p => <option key={p.id} value={p.id}>{p.name} ({p.code})</option>)}</select><select required name="leadAuditorId" className="field"><option value="">Lead auditor account</option>{users.map(u => <option key={u.id} value={u.id}>{u.email}</option>)}</select><input required name="auditPeriodStart" type="date" className="field" /><input required name="auditPeriodEnd" type="date" className="field" /><input name="materiality" type="number" min="0" step="0.01" placeholder="Materiality threshold" className="field" /><textarea name="objective" placeholder="Engagement objective" className="field min-h-24 md:col-span-2" /></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShowEngagementForm(false)} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-emerald-300 px-3 py-2 text-sm font-semibold text-slate-950">{saving ? 'Creating…' : 'Create engagement'}</button></div></form>}
    {showForm && <form onSubmit={event => void submit(event, 'access')} className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[.04] p-5"><h2 className="mb-4 font-semibold text-white">Grant controlled access</h2><div className="grid gap-3 md:grid-cols-2"><select required name="userId" className="field"><option value="">Select auditor account</option>{users.map(u => <option key={u.id} value={u.id}>{u.email}</option>)}</select><select required name="propertyId" className="field"><option value="">Select property</option>{properties.map(p => <option key={p.id} value={p.id}>{p.name} ({p.code})</option>)}</select><input required name="auditPeriodStart" type="date" className="field" /><input required name="auditPeriodEnd" type="date" className="field" /><input required name="accessStartsAt" type="datetime-local" className="field" /><input required name="accessExpiresAt" type="datetime-local" className="field" /></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-emerald-300 px-3 py-2 text-sm font-semibold text-slate-950">{saving ? 'Granting…' : 'Grant controlled access'}</button></div></form>}
    <section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><h2 className="font-semibold text-white">Engagement register</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{engagements.map(e => <div key={e.id} className="rounded-xl border border-white/[.07] p-4"><div className="flex items-center justify-between gap-3"><p className="font-medium text-white">{e.name}</p><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[10px] text-emerald-300">{human(e.status)}</span></div><p className="mt-2 text-xs text-slate-500">{e.auditType} · {new Date(e.auditPeriodStart).toLocaleDateString()} — {new Date(e.auditPeriodEnd).toLocaleDateString()}</p></div>)}{!engagements.length && <p className="text-sm text-slate-500">No engagement records have been created.</p>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]"><div className="border-b border-white/[.07] px-5 py-4"><h2 className="font-semibold text-white">Access register</h2><p className="mt-1 text-xs text-slate-500">Every engagement is property-scoped, date-scoped, extendable, and revocable.</p></div><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-left text-sm"><thead><tr>{['Auditor', 'Property', 'Audit period', 'Access expiry', 'Status', 'Granted by', 'Actions'].map(header => <th key={header} className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">{header}</th>)}</tr></thead><tbody className="divide-y divide-white/[.06]">{accesses.map(access => <tr key={access.id}><td className="px-5 py-4"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-500" />{access.user.email}</div></td><td className="px-5 py-4 text-slate-300">{access.property.name}</td><td className="px-5 py-4 text-slate-400">{new Date(access.auditPeriodStart).toLocaleDateString()} — {new Date(access.auditPeriodEnd).toLocaleDateString()}</td><td className="px-5 py-4 text-slate-400">{new Date(access.accessExpiresAt).toLocaleString()}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 text-xs">{access.status === 'ACTIVE' ? <CheckCircle2 className="h-3 w-3 text-emerald-300" /> : access.status === 'EXPIRED' ? <Clock3 className="h-3 w-3 text-amber-300" /> : <XCircle className="h-3 w-3 text-red-300" />}{human(access.status)}</span></td><td className="px-5 py-4 text-xs text-slate-500">{access.grantedByUser.email}</td><td className="px-5 py-4"><div className="flex gap-3">{access.status === 'ACTIVE' && <><button onClick={() => void extend(access)} className="text-xs text-emerald-300">Extend</button><button onClick={() => void revoke(access.id)} className="text-xs text-red-300">Revoke</button></>}</div></td></tr>)}</tbody></table></div>{loading && <div className="p-10 text-center text-sm text-slate-500"><Loader2 className="mx-auto mb-2 h-4 w-4 animate-spin" />Loading access register…</div>}{!loading && !accesses.length && <div className="p-14 text-center"><ShieldAlert className="mx-auto h-7 w-7 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No auditor access has been granted.</p></div>}</section>
  </div></div>;
}
