'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, BarChart3, BellRing, Check, ChevronRight, CircleAlert, Download, Gauge, Layers3, LifeBuoy, LockKeyhole, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';

type PortalData = any;
const tip = { background: '#0d1b2a', border: '1px solid rgba(148,163,184,.2)', borderRadius: 12, color: '#e2e8f0' };
const money = (value: number, currency: string) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());

export default function SubscriptionPortal({ data }: { data: PortalData }) {
  const [dialog, setDialog] = useState<'plans' | 'invoice' | null>(null);
  const [selectedInvoice, setSelectedInvoice] = useState<any>(null);
  const [checkout, setCheckout] = useState<string | null>(null);
  const currentPlan = data.current?.plan?.name || 'No active plan';
  const currentEnd = data.current?.currentPeriodEnd;
  const daysRemaining = currentEnd ? Math.max(0, Math.ceil((new Date(currentEnd).getTime() - Date.now()) / 86400000)) : 0;
  const activeProperties = data.properties.filter((property: any) => property.isActive).length;
  const suspendedProperties = data.properties.length - activeProperties;
  const billingRisk = data.current?.status === 'PAST_DUE' || data.invoices.some((invoice: any) => invoice.status === 'failed' && invoice.amountDue > 0);
  const insights = useMemo(() => [
    data.properties.length === 0 ? { tone: 'amber', icon: CircleAlert, title: 'Property setup is incomplete', detail: 'Add an active property before provisioning the full operating stack.' } : null,
    suspendedProperties > 0 ? { tone: 'rose', icon: CircleAlert, title: `${suspendedProperties} property lifecycle record${suspendedProperties === 1 ? '' : 's'} need attention`, detail: 'Resolve property suspension or setup controls before assigning new subscription scope.' } : null,
    billingRisk ? { tone: 'rose', icon: BellRing, title: 'Billing attention required', detail: 'A failed or past-due billing record can interrupt property entitlements after the grace window.' } : null,
    activeProperties > 0 ? { tone: 'emerald', icon: BarChart3, title: `${activeProperties} active propert${activeProperties === 1 ? 'y' : 'ies'} in scope`, detail: 'Your subscription can be reviewed against the organization’s current property estate.' } : null,
  ].filter(Boolean), [activeProperties, billingRisk, data.properties.length, suspendedProperties]);

  async function startCheckout(plan: any) {
    const price = plan.items.flatMap((item: any) => item.product.prices).find((item: any) => item.interval === 'month') || plan.items.flatMap((item: any) => item.product.prices)[0];
    if (!price) return;
    setCheckout(plan.id);
    const response = await fetch('/api/v1/billing/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ organizationId: data.organization.id, planId: plan.id, priceIds: plan.items.map((item: any) => item.product.prices.find((candidate: any) => candidate.interval === price.interval)?.id).filter(Boolean), propertyIds: data.properties.filter((property: any) => property.isActive).map((property: any) => property.id), successUrl: `${window.location.origin}/portal/subscription?success=true`, cancelUrl: `${window.location.origin}/portal/subscription?cancelled=true` }) });
    const payload = await response.json();
    setCheckout(null);
    if (response.ok && payload.url) window.location.assign(payload.url);
    else window.alert(payload.error || 'Unable to start secure checkout.');
  }

  return <main className="min-h-screen bg-[#07111f] text-slate-100"><div className="mx-auto max-w-[1640px] space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.24em] text-cyan-300"><span className="size-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_#67e8f9]" /> LodgeCore portal · live control plane</div><h1 className="text-3xl font-semibold tracking-[-.05em] text-white sm:text-4xl">Subscription command center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">One operating view for plan health, property capacity, billing continuity, and the performance signals that shape your next growth decision.</p></div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/15 bg-emerald-300/[.06] px-3 py-2 text-[11px] text-emerald-200"><span className="size-1.5 rounded-full bg-emerald-300" />Live · {new Date(data.generatedAt).toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' })}</span><Button onClick={() => location.reload()} variant="outline" size="sm" className="border-white/10 bg-white/[.04] text-slate-200"><RefreshCw className="mr-2 size-3.5" />Refresh</Button></div></header>
    <section className="relative overflow-hidden rounded-3xl border border-indigo-300/20 bg-gradient-to-br from-[#182953] via-[#122039] to-[#0c1728] p-6 shadow-2xl shadow-indigo-950/25 sm:p-8"><div className="pointer-events-none absolute -right-16 -top-32 size-96 rounded-full border-[48px] border-indigo-300/[.07]" /><div className="relative grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><div className="flex items-center gap-2 text-xs font-medium text-indigo-200"><Sparkles className="size-4 text-cyan-300" /> {data.organization.name}</div><div className="mt-4 flex flex-wrap items-end gap-3"><h2 className="text-4xl font-semibold tracking-tight text-white">{currentPlan}</h2><span className={cn('mb-1 rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider', data.current?.status === 'PAST_DUE' ? 'border-rose-300/25 bg-rose-300/10 text-rose-200' : 'border-emerald-300/25 bg-emerald-300/10 text-emerald-200')}>{data.current ? label(data.current.status) : 'Not configured'}</span></div><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">{data.current?.plan?.description || 'Choose a plan to activate the complete LodgeCore property management operating model.'}</p><div className="mt-6 flex flex-wrap gap-2"><Button onClick={() => setDialog('plans')} className="bg-white text-slate-950 hover:bg-cyan-50">{data.current ? 'Review plans' : 'Choose a plan'}<ChevronRight className="ml-2 size-4" /></Button><Link href="/settings" className="inline-flex h-8 items-center rounded-lg border border-white/15 bg-white/[.04] px-3 text-sm font-medium text-slate-200 hover:bg-white/10">Workspace settings<ArrowUpRight className="ml-2 size-3.5" /></Link></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-wider text-indigo-200/65">Renewal window</p><p className="mt-2 text-2xl font-semibold text-white">{data.current ? `${daysRemaining}d` : '—'}</p><p className="mt-1 text-xs text-slate-400">{data.current ? `through ${date(currentEnd)}` : 'No active cycle'}</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-wider text-indigo-200/65">Coverage</p><p className="mt-2 text-2xl font-semibold text-white">{data.organization.propertyCount}</p><p className="mt-1 text-xs text-slate-400">active properties</p></div><div className="col-span-2 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.06] p-4"><div className="flex items-center gap-2 text-xs font-medium text-cyan-100"><ShieldCheck className="size-4 text-cyan-300" /> Entitlements are reconciled from the billing ledger</div><p className="mt-2 text-[11px] leading-5 text-slate-400">Changes from Flutterwave webhooks flow into property-scoped access after provider verification.</p></div></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Properties in scope", `${activeProperties}/${data.properties.length}`, 'Organization lifecycle records', Layers3, 'text-cyan-300'], ['Active team seats', data.metrics.staffCount, 'Organization staff records', LockKeyhole, 'text-violet-300'], ['POS outlets provisioned', data.metrics.outletsCount, 'Across the property estate', BarChart3, 'text-indigo-300'], ['Billing continuity', data.current ? 'Protected' : 'Action needed', data.current ? 'Active provider-backed cycle' : 'Activate a plan to unlock modules', ShieldCheck, data.current ? 'text-emerald-300' : 'text-amber-300'], ['Entitlement signals', data.entitlements.length, 'Persisted access records', Gauge, 'text-emerald-300']].map(([title, value, detail, Icon, color]: any) => <div key={title} className="rounded-2xl border border-white/10 bg-[#101b2f] p-4 shadow-xl shadow-black/10"><div className="flex items-start justify-between"><div><p className="text-[10px] font-medium uppercase tracking-[.14em] text-slate-500">{title}</p><p className="mt-3 text-xl font-semibold tracking-tight text-white">{value}</p></div><Icon className={cn('size-4', color)} /></div><p className="mt-3 truncate text-xs text-slate-500">{detail}</p></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">Billing performance</p><p className="mt-1 text-xs text-slate-500">Billed versus collected from the persisted invoice ledger · {data.metrics.currency}</p></div><span className="rounded-full bg-white/[.04] px-2.5 py-1 text-[10px] text-slate-400">6 months</span></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.revenueTrend} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="portalCollected" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#34d399" stopOpacity={.32} /><stop offset="95%" stopColor="#34d399" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.1)" vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#64748b', fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: '#64748b', fontSize: 10 }} tickFormatter={(value) => `${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tip} formatter={(value: any, name: any) => [money(Number(value), data.metrics.currency), name]} /><Area type="monotone" dataKey="billed" name="Billed" stroke="#818cf8" strokeWidth={2.5} fill="none" /><Area type="monotone" dataKey="collected" name="Collected" stroke="#34d399" strokeWidth={2.5} fill="url(#portalCollected)" /></AreaChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-4"><p className="text-sm font-semibold text-white">Decision signals</p><p className="mt-1 text-xs text-slate-500">Live operating and billing observations</p></div><div className="space-y-3">{insights.length ? insights.map((item: any) => <div key={item.title} className="flex gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3"><div className={cn('mt-0.5 rounded-lg p-2', item.tone === 'rose' ? 'bg-rose-300/10 text-rose-300' : item.tone === 'amber' ? 'bg-amber-300/10 text-amber-300' : item.tone === 'violet' ? 'bg-violet-300/10 text-violet-300' : 'bg-emerald-300/10 text-emerald-300')}><item.icon className="size-4" /></div><div><p className="text-xs font-medium text-white">{item.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{item.detail}</p></div></div>) : <p className="py-8 text-center text-sm text-slate-500">No live signals require attention.</p>}</div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">Property lifecycle scope</p><p className="mt-1 text-xs text-slate-500">Organization-level property records only · room and guest operations stay in each property workspace</p></div><span className="rounded-full bg-cyan-300/10 px-2.5 py-1 text-[10px] text-cyan-200">{data.properties.length} records</span></div><div className="space-y-2">{data.properties.map((property: any) => <div key={property.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-100">{property.name}</p><p className="mt-1 text-[11px] text-slate-500">{property.city}, {property.country} · {property.isActive ? 'Available for organization scope' : property.suspensionReason || 'Inactive lifecycle record'}</p></div><div className="flex shrink-0 items-center gap-3"><span className={cn('rounded-full px-2 py-1 text-[10px]', property.isActive ? 'bg-emerald-300/10 text-emerald-200' : 'bg-rose-300/10 text-rose-200')}>{property.isActive ? 'Active' : 'Suspended'}</span><span className="hidden text-[10px] text-slate-600 sm:inline">{property.auditStatus || 'Audit not started'}</span></div></div>)}{!data.properties.length && <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No property lifecycle records are attached to this organization.</div>}</div></div><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5"><p className="text-sm font-semibold text-white">Entitlement posture</p><p className="mt-1 text-xs text-slate-500">Feature access and limits from the live subscription scope</p></div><div className="space-y-2">{data.entitlements.slice(0, 8).map((item: any) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-200">{item.product.name}</p><p className="mt-1 truncate text-[10px] text-slate-500">{item.property?.name || 'Organization-wide'} · expires {date(item.expiresAt)}</p></div><div className="text-right"><p className="text-xs font-semibold text-emerald-300">{item.quantity === null ? 'Unlimited' : item.quantity}</p><p className="text-[9px] uppercase tracking-wider text-slate-600">{label(item.status)}</p></div></div>)}{!data.entitlements.length && <p className="py-8 text-center text-sm text-slate-500">Entitlements appear after provider-confirmed billing.</p>}</div></div></section>
    <section className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-4 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">Invoice ledger</p><p className="mt-1 text-xs text-slate-500">Provider-backed billing records; open a row for the full transaction context.</p></div><Button onClick={() => setDialog('plans')} variant="outline" size="sm" className="border-white/10 bg-white/[.03] text-slate-200">Plans & pricing<ArrowUpRight className="ml-2 size-3.5" /></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b border-white/8 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-3 py-3">Record</th><th className="px-3 py-3">Created</th><th className="px-3 py-3">Period</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Total</th><th className="px-3 py-3 text-right" /></tr></thead><tbody className="divide-y divide-white/8">{data.invoices.map((invoice: any) => <tr key={invoice.id} className="hover:bg-white/[.025]"><td className="px-3 py-3 font-mono text-[10px] text-slate-300">{invoice.flutterwaveInvoiceId}</td><td className="px-3 py-3 text-slate-400">{date(invoice.createdAt)}</td><td className="px-3 py-3 text-slate-500">{date(invoice.periodStart)} — {date(invoice.periodEnd)}</td><td className="px-3 py-3"><span className={cn('rounded-full px-2 py-1 text-[10px]', invoice.status === 'paid' ? 'bg-emerald-300/10 text-emerald-200' : 'bg-amber-300/10 text-amber-200')}>{label(invoice.status)}</span></td><td className="px-3 py-3 text-right font-semibold text-white">{money(invoice.total / 100, invoice.currency)}</td><td className="px-3 py-3 text-right"><button onClick={() => { setSelectedInvoice(invoice); setDialog('invoice'); }} className="rounded-lg p-2 text-slate-500 hover:bg-white/10 hover:text-cyan-300" aria-label="Inspect invoice"><ChevronRight className="size-4" /></button></td></tr>)}</tbody></table>{!data.invoices.length && <div className="p-10 text-center text-sm text-slate-500">No provider invoice records yet.</div>}</div></section>
    <footer className="flex flex-col justify-between gap-3 border-t border-white/8 pt-5 text-xs text-slate-500 sm:flex-row"><span>Data generated {date(data.generatedAt)} · timezone {data.organization.defaultTimezone}</span><span className="flex items-center gap-3"><Link href="/support" className="hover:text-white"><LifeBuoy className="mr-1 inline size-3.5" />Support</Link><span><LockKeyhole className="mr-1 inline size-3.5" />Secure provider-backed billing</span></span></footer>
    <Dialog open={dialog === 'plans'} onOpenChange={(open) => !open && setDialog(null)}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#101b2f] text-slate-100 sm:max-w-5xl"><DialogHeader><DialogTitle className="text-xl text-white">Plans built for the full property lifecycle</DialogTitle><DialogDescription className="text-slate-400">Live plans and prices from the LodgeCore billing catalogue. Checkout is verified by Flutterwave before access changes.</DialogDescription></DialogHeader><div className="grid gap-4 py-4 lg:grid-cols-3">{data.plans.map((plan: any) => { const monthly = plan.items.flatMap((item: any) => item.product.prices).find((price: any) => price.interval === 'month'); return <div key={plan.id} className={cn('flex flex-col rounded-2xl border p-5', plan.id === data.current?.planId ? 'border-cyan-300/40 bg-cyan-300/[.06]' : 'border-white/10 bg-white/[.025]')}><div className="flex items-center justify-between"><p className="font-semibold text-white">{plan.name}</p>{plan.id === data.current?.planId && <span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] text-cyan-200">Current</span>}</div><p className="mt-2 min-h-10 text-xs leading-5 text-slate-400">{plan.description}</p><p className="mt-5 text-2xl font-semibold text-white">{monthly ? money(monthly.amount / 100, monthly.currency) : 'Contact us'}</p><p className="text-[10px] text-slate-500">{monthly ? 'per month · billed securely' : 'Tailored enterprise pricing'}</p><div className="mt-5 flex-1 space-y-2">{plan.items.map((item: any) => <p key={item.id} className="flex gap-2 text-xs text-slate-300"><Check className="size-3.5 shrink-0 text-emerald-300" />{item.product.name}{item.includedQty !== null ? ` · ${item.includedQty} included` : ''}</p>)}</div><Button disabled={checkout === plan.id || plan.id === data.current?.planId || !monthly} onClick={() => void startCheckout(plan)} className="mt-6 bg-indigo-500 text-white hover:bg-indigo-400">{checkout === plan.id ? 'Opening secure checkout…' : plan.id === data.current?.planId ? 'Active plan' : monthly ? 'Select plan' : 'Talk to LodgeCore'}</Button></div> })}</div><DialogFooter><p className="mr-auto text-[11px] text-slate-500">Plan changes are not applied until the payment provider confirms the transaction.</p></DialogFooter></DialogContent></Dialog>
    <Dialog open={dialog === 'invoice'} onOpenChange={(open) => !open && setDialog(null)}><DialogContent className="border-white/10 bg-[#101b2f] text-slate-100 sm:max-w-xl"><DialogHeader><DialogTitle className="text-white">Billing record inspection</DialogTitle><DialogDescription className="text-slate-400">Persisted invoice information from the verified payment-provider event.</DialogDescription></DialogHeader>{selectedInvoice && <div className="grid gap-3 py-3 sm:grid-cols-3">{[['Total', money(selectedInvoice.total / 100, selectedInvoice.currency)], ['Collected', money(selectedInvoice.amountPaid / 100, selectedInvoice.currency)], ['Outstanding', money(selectedInvoice.amountDue / 100, selectedInvoice.currency)]].map(([name, value]) => <div key={name} className="rounded-xl border border-white/8 bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">{name}</p><p className="mt-2 text-lg font-semibold text-white">{value}</p></div>)}<div className="sm:col-span-3 rounded-xl border border-white/8 bg-white/[.02] p-4 text-xs leading-6 text-slate-400"><p><span className="text-slate-500">Provider reference:</span> {selectedInvoice.flutterwaveInvoiceId}</p><p><span className="text-slate-500">Status:</span> {label(selectedInvoice.status)}</p><p><span className="text-slate-500">Billing period:</span> {date(selectedInvoice.periodStart)} — {date(selectedInvoice.periodEnd)}</p></div></div>}<DialogFooter><Button variant="outline" onClick={() => setDialog(null)} className="border-white/10 bg-transparent text-slate-200">Close</Button>{selectedInvoice?.invoicePdf && <Button asChild className="bg-indigo-500"><a href={selectedInvoice.invoicePdf} target="_blank" rel="noreferrer"><Download className="mr-2 size-4" />Open PDF</a></Button>}</DialogFooter></DialogContent></Dialog>
  </div></main>;
}
