
[String]
; main window items
IDD102_Title=智能锁扩展分区设置工具
IDD102_1000=启用扩展扇区_1
IDD102_1008=扇区：
IDD102_1009=密钥A:
IDD102_1010=12个字符(0~9,A~F)
IDD102_1001=启用扩展扇区_2(Hooks)
IDD102_1011=扇区：
IDD102_1012=密钥A:
IDD102_1013=12个字符(0~9,A~F)
IDD102_1006=自动加密扇区
IDD102_1=保存
IDD102_2=取消
; strings
IDS_INVALID_FACTORY_DATA=对不起, 厂商加密数据不正确!
IDS_STRKEYA_ERR1=密钥A_1的长度不对, 请输入12个字符
IDS_STRKEYA_ERR2=密钥A_2的长度不对, 请输入12个字符
IDS_STRSAVE_OK=保存成功
g_LoadString