'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Loader2, Plus, ShieldAlert } from 'lucide-react';

type Finding = { id: string; reference: string; title: string };
type Plan = { id: string; action: string; status: string; progress: number; dueDate: string; findingId: string; completionNote?: string | null };
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function ActionPlansPage() {
  const [propertyId, setPropertyId] = useState(''); const [plans, setPlans] = useState<Plan[]>([]); const [findings, setFindings] = useState<Finding[]>([]); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (id: string) => { const [p, f] = await Promise.all([fetch(`/api/v1/external-auditor/management?resource=action-plans&propertyId=${id}`).then(r => r.json()), fetch(`/api/v1/external-auditor/management?resource=findings&propertyId=${id}`).then(r => r.json())]); setPlans(p.items || []); setFindings(f.items || []); setLoading(false); };
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(v => { const scope = v.scopes?.[0]; if (!scope) throw new Error(v.error || 'No active engagement'); setPropertyId(scope.propertyId); return load(scope.propertyId); }).catch(e => { setError(e.message); setLoading(false); }); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!findings.length) { setError('Create or load a finding before adding an action plan.'); return; } setSaving(true); setError(''); const body = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch('/api/v1/external-auditor/management', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resource: 'action-plan', propertyId, ...body }) }); const value = await response.json(); if (!response.ok) setError(value.error || 'Unable to create action plan'); else { setShowForm(false); event.currentTarget.reset(); await load(propertyId); } setSaving(false); };
  const update = async (plan: Plan, status: string) => { const response = await fetch('/api/v1/external-auditor/management', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resource: 'action-plan', id: plan.id, status, progress: status === 'COMPLETED' ? 100 : plan.progress }) }); if (!response.ok) { const value = await response.json(); setError(value.error || 'Unable to update action plan'); } else await load(propertyId); };
  return <div className="space-y-6 pb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><ClipboardCheck className="h-4 w-4" /> Remediation governance</div><h1 className="text-3xl font-semibold tracking-tight text-white">Action plans</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Track management remediation from finding through completion with a dated owner trail.</p></div><button type="button" onClick={() => setShowForm(value => !value)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-300 px-4 text-sm font-semibold text-slate-950 hover:bg-emerald-200"><Plus className="h-4 w-4" /> New action plan</button></div>
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    {showForm && <form onSubmit={create} className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[.04] p-5"><div className="grid gap-3 sm:grid-cols-2"><select required name="findingId" className="field sm:col-span-2"><option value="">Link to finding</option>{findings.map(finding => <option key={finding.id} value={finding.id}>{finding.reference} · {finding.title}</option>)}</select><input name="ownerId" placeholder="Owner user ID (optional)" className="field" /><input required name="dueDate" type="date" className="field" /><input required name="action" placeholder="Remediation action" className="field sm:col-span-2" /><input name="progress" type="number" min="0" max="100" defaultValue="0" placeholder="Progress %" className="field" /></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="rounded-lg border border-white/10 px-3 py-2 text-sm text-slate-300">Cancel</button><button disabled={saving} className="rounded-lg bg-emerald-300 px-3 py-2 text-sm font-semibold text-slate-950">{saving ? 'Saving…' : 'Create action plan'}</button></div></form>}
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]">{loading ? <div className="flex h-48 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading action plans…</div> : <div className="divide-y divide-white/[.06]">{plans.map(plan => <div key={plan.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="min-w-0"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><h2 className="font-medium text-white">{plan.action}</h2><span className="rounded-full bg-white/[.06] px-2 py-1 text-[10px] text-slate-400">{human(plan.status)}</span></div><p className="mt-2 text-xs text-slate-500">Due {new Date(plan.dueDate).toLocaleDateString()} · {plan.progress}% complete</p><div className="mt-3 h-1.5 max-w-md overflow-hidden rounded-full bg-white/[.08]"><div className="h-full rounded-full bg-emerald-300" style={{ width: `${Math.min(100, Math.max(0, plan.progress))}%` }} /></div></div><select value={plan.status} onChange={event => void update(plan, event.target.value)} className="field w-auto"><option>OPEN</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>CLOSED</option></select></div>)}{!plans.length && <div className="p-14 text-center"><ShieldAlert className="mx-auto h-7 w-7 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No action plans have been recorded.</p></div>}</div>}</section>
  </div>;
}
