'use client';

import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Activity, CheckCircle2, ChevronRight, CircleAlert, FileSearch, Filter, Hash, Loader2, Search, X } from 'lucide-react';

type Item = { id: string; reference?: string; date: string; type: string; amount: number | null; currency?: string; description?: string; actor?: string; status: string; source: string; requestId?: string };
type Detail = { item: { id: string; description: string; amount: number; currency: string; type: string; folio: { folioNumber: string } }; auditLogs: Array<{ id: string; createdAt: string; action: string; resource: string; userEmail?: string; userRole?: string; requestId?: string }>; financialLogs: Array<{ id: string; createdAt: string; operationType: string; reason?: string; approvalStatus: string; amount?: number }> };
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());
const money = (value: number | null, currency = '') => value == null ? '—' : new Intl.NumberFormat('en', { style: 'currency', currency: currency || 'USD', maximumFractionDigits: 2 }).format(value);

export default function ExternalAuditorEvidence() {
  const params = useSearchParams(); const [propertyId, setPropertyId] = useState(params.get('propertyId') || ''); const [q, setQ] = useState(params.get('q') || ''); const [source, setSource] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [items, setItems] = useState<Item[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!propertyId) void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(v => setPropertyId(v.scopes?.[0]?.propertyId || '')); }, [propertyId]);
  useEffect(() => { if (!propertyId) return; const timer = window.setTimeout(() => { setLoading(true); void fetch(`/api/v1/external-auditor/evidence?propertyId=${propertyId}&q=${encodeURIComponent(q)}`).then(async r => { const v = await r.json(); if (!r.ok) throw new Error(v.error || 'Unable to load evidence'); return v; }).then(v => setItems(v.items || [])).catch(e => setError(e.message)).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [propertyId, q]);
  const visible = useMemo(() => items.filter(item => (source === 'ALL' || item.source === source) && (status === 'ALL' || item.status === status)), [items, source, status]);
  const openTrail = (item: Item) => { if (item.source !== 'FOLIO') return; void fetch(`/api/v1/external-auditor/evidence?propertyId=${propertyId}&source=FOLIO&id=${item.id}`).then(r => r.json()).then(v => setDetail(v.evidence)); };
  const sources = [...new Set(items.map(item => item.source))]; const statuses = [...new Set(items.map(item => item.status))];
  return <div className="space-y-6 pb-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><FileSearch className="h-4 w-4" /> Evidence management</div><h1 className="text-3xl font-semibold tracking-tight text-white">Evidence explorer</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Trace source transactions, ledger activity, and immutable control events within the authorized engagement window.</p></div><div className="rounded-xl border border-white/[.08] bg-white/[.035] px-3 py-2 text-xs text-slate-400"><span className="text-slate-200">{visible.length.toLocaleString()}</span> visible records</div></div>
    <section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search description, reference, resource or actor" className="h-11 w-full rounded-xl border border-white/10 bg-slate-950/50 pl-10 pr-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-emerald-300/40" /></div><div className="flex flex-wrap gap-2"><div className="relative"><Filter className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-500" /><select value={source} onChange={e => setSource(e.target.value)} className="h-11 rounded-xl border border-white/10 bg-slate-950/50 pl-9 pr-8 text-sm text-slate-300 outline-none"><option value="ALL">All sources</option>{sources.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-11 rounded-xl border border-white/10 bg-slate-950/50 px-3 text-sm text-slate-300 outline-none"><option value="ALL">All statuses</option>{statuses.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></div></div></section>
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]"><div className="flex items-center justify-between border-b border-white/[.07] px-5 py-4"><div><h2 className="font-semibold text-white">Source register</h2><p className="mt-1 text-xs text-slate-500">Select a folio transaction to inspect its complete audit lineage.</p></div>{loading && <Loader2 className="h-4 w-4 animate-spin text-emerald-300" />}</div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-950/25"><tr>{['Reference', 'Business date', 'Source / type', 'Amount', 'Actor', 'Control state', ''].map(header => <th key={header} className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">{header}</th>)}</tr></thead><tbody className="divide-y divide-white/[.06]">{visible.map(item => <tr key={`${item.source}-${item.id}`} className="group hover:bg-white/[.025]"><td className="px-5 py-4"><div className="flex items-center gap-2"><Hash className="h-3.5 w-3.5 text-slate-600" /><span className="font-mono text-xs text-emerald-300">{item.reference || item.id.slice(0, 12)}</span></div><p className="mt-1 max-w-[220px] truncate text-xs text-slate-500">{item.description || 'No description'}</p></td><td className="px-5 py-4 text-slate-400">{new Date(item.date).toLocaleDateString()}</td><td className="px-5 py-4"><p className="text-slate-300">{label(item.type)}</p><p className="mt-1 text-[11px] text-slate-500">{label(item.source)}</p></td><td className="px-5 py-4 font-medium text-slate-200">{money(item.amount, item.currency)}</td><td className="px-5 py-4"><p className="max-w-[150px] truncate text-slate-400">{item.actor || 'System'}</p></td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${item.status === 'POSTED' || item.status === 'AUDIT_LOG' ? 'bg-emerald-300/10 text-emerald-300' : 'bg-amber-300/10 text-amber-300'}`}>{item.status === 'POSTED' ? <CheckCircle2 className="h-3 w-3" /> : <CircleAlert className="h-3 w-3" />}{label(item.status)}</span></td><td className="px-5 py-4 text-right"><button onClick={() => openTrail(item)} disabled={item.source !== 'FOLIO'} className="inline-flex items-center gap-1 text-xs font-medium text-sky-300 transition hover:text-sky-200 disabled:cursor-not-allowed disabled:text-slate-700">Inspect <ChevronRight className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table></div>{!visible.length && !loading && <div className="px-6 py-16 text-center"><Activity className="mx-auto h-8 w-8 text-slate-700" /><p className="mt-3 text-sm text-slate-400">No evidence matches the current review scope.</p><p className="mt-1 text-xs text-slate-600">Try a broader search or remove one of the filters.</p></div>}</section>
    {detail && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/80 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl border border-white/10 bg-[#101b2c] shadow-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-white/[.08] bg-[#101b2c]/95 p-5 backdrop-blur sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-300">Immutable source trail</p><h2 className="mt-2 text-xl font-semibold text-white">{detail.item.folio.folioNumber}</h2><p className="mt-1 max-w-xl text-sm text-slate-400">{detail.item.description} · {money(Number(detail.item.amount), detail.item.currency)}</p></div><button onClick={() => setDetail(null)} className="rounded-lg p-2 text-slate-500 hover:bg-white/[.06] hover:text-white" aria-label="Close trail"><X className="h-5 w-5" /></button></div><div className="grid gap-3 border-b border-white/[.08] p-5 sm:grid-cols-3 sm:p-6"><div><p className="text-xs text-slate-500">Transaction type</p><p className="mt-1 text-sm text-slate-200">{label(detail.item.type)}</p></div><div><p className="text-xs text-slate-500">Financial events</p><p className="mt-1 text-sm text-slate-200">{detail.financialLogs.length}</p></div><div><p className="text-xs text-slate-500">System audit events</p><p className="mt-1 text-sm text-slate-200">{detail.auditLogs.length}</p></div></div><div className="space-y-3 p-5 sm:p-6">{[...detail.financialLogs.map(event => ({ ...event, kind: 'FINANCIAL', title: event.operationType, meta: `${event.approvalStatus}${event.reason ? ` · ${event.reason}` : ''}` })), ...detail.auditLogs.map(event => ({ ...event, kind: 'SYSTEM', title: event.action, meta: `${event.userEmail || event.userRole || 'SYSTEM'}${event.requestId ? ` · ${event.requestId}` : ''}` }))].sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()).map(event => <div key={`${event.kind}-${event.id}`} className="flex gap-3 rounded-xl border border-white/[.07] bg-slate-950/20 p-4"><div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${event.kind === 'FINANCIAL' ? 'bg-amber-300/10 text-amber-300' : 'bg-sky-300/10 text-sky-300'}`}><Activity className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium text-slate-200">{label(event.title)}</p><time className="text-[11px] text-slate-500">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-1 text-xs text-slate-500">{event.meta}</p></div></div>)}{!detail.financialLogs.length && !detail.auditLogs.length && <p className="py-8 text-center text-sm text-slate-500">No linked audit events were recorded for this source transaction.</p>}</div></div></div>}
  </div>;
}
