[SystemInfo]

Sn=3602E025429B0B1D6222

HotelName=
DayCount=30
TimeTolerance=20
Pass=881A0001
LanguageID=1033
DoorAlarmSound=16
enOpeningMusic=1
enNormalOPen=0
LeaveTime=13:00:00
MoreGuestCards=1
EncodeDirectly=1
DataExtension=1
RoomExtension=1
DeadboltOverride=0
Lift=1
SoftVer=50
OpenRecordUnit=$08
OpenRecordCounts=$02
LockEepType=$08
MainListView_ViewStyle=0
ServerIp=127.0.0.1
RmtPort=2008
LocalServer=1
NetworkLock=0
NetworkSwitch=0
CheckMCDevice=1

DoorDelayTime=4
DataSaveMode=0
HostilityBrushCard=4
OldIpAdress=192.168.0.100
Subnetmask=255.255.255.0
Gateway=192.168.0.1
MotorInterval=2
CheckDoorState=0
UseRoomID=0


[RoomColor]
#在住房
Checked in=33023
#正常客房
Normal=15793151
#预定
Booked=15793151
#自用
Reserved=15793151
#脏房
Dirty=15793151
#维修
Service=15793151

[Config]
LockType=4
CommProt=0
Block=0
KeyType=0
KeyStr=FFFFFFFFFFFF
Sector=1
M1CommonDataSector = $0e

[Client Config]
ConnType=0
UserName=Admin
Pass=lockdbpass
ServerName=(local)
DbPath=C:\Program Files\Hotel lock system V5.853D\Db\lock.mdb


[Default Common doors]
D0=12
D1=0
D2=0
D3=0
