import prisma from '@hotel-pms/db';
import { requireHQAdmin } from '@/lib/auth/hq';
import { LeadActions } from './LeadActions';

export default async function HQLeadsPage() {
  await requireHQAdmin();
  const leads = await prisma.salesLead.findMany({ orderBy: { createdAt: 'desc' }, take: 100, include: { organization: { select: { id: true, name: true } } } });
  return <div className="min-h-full bg-[#07111f] p-5 text-slate-200 sm:p-8 xl:p-10"><div className="mx-auto max-w-[1500px] space-y-6"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-indigo-300">Sales pipeline</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Inbound leads</h1><p className="mt-2 text-sm text-slate-400">Qualify requests and provision customer portal access when a lead is ready.</p></div><div className="overflow-x-auto rounded-2xl border border-white/10 bg-[#101b2f]"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[.15em] text-slate-500"><tr><th className="px-5 py-4">Contact</th><th className="px-5 py-4">Property</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Received</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-white/6">{leads.map((lead) => <tr key={lead.id}><td className="px-5 py-4"><p className="font-medium text-white">{lead.name}</p><p className="mt-1 text-xs text-slate-500">{lead.email}{lead.phone ? ` · ${lead.phone}` : ''}</p></td><td className="px-5 py-4 text-slate-300">{lead.propertyName || lead.company || '—'}<p className="mt-1 text-xs text-slate-500">{lead.roomCount ? `${lead.roomCount} rooms` : 'Room count not provided'}</p></td><td className="px-5 py-4"><span className="rounded-full bg-white/[.06] px-2.5 py-1 text-xs text-slate-300">{lead.status}</span>{lead.organization && <p className="mt-2 text-xs text-emerald-300">{lead.organization.name}</p>}</td><td className="px-5 py-4 text-xs text-slate-500">{lead.createdAt.toLocaleString('en-NG', { dateStyle: 'medium', timeStyle: 'short' })}</td><td className="px-5 py-4 text-right"><LeadActions leadId={lead.id} status={lead.status} defaultOrganizationName={lead.propertyName || lead.company || ''} /></td></tr>)}</tbody></table>{leads.length === 0 && <p className="p-12 text-center text-sm text-slate-500">No inbound leads have been received.</p>}</div></div></div>;
}

