'use client';

import { useEffect, useState } from 'react';
import { CalendarRange, Loader2, ShieldCheck } from 'lucide-react';

type Engagement = { id: string; name: string; auditType: string; status: string; objective?: string | null; scope?: string | null; exclusions?: string | null; materiality?: number | null; auditPeriodStart: string; auditPeriodEnd: string; risks?: string[] | null; financialAreas?: string[] | null };
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function EngagementPage() {
  const [engagement, setEngagement] = useState<Engagement | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(async context => { const scope = context.scopes?.[0]; if (!scope) throw new Error(context.error || 'No active engagement'); const response = await fetch(`/api/v1/external-auditor/management?resource=engagements&propertyId=${scope.propertyId}`); const value = await response.json(); setEngagement(value.items?.[0] || null); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="flex min-h-[40vh] items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading engagement…</div>;
  if (error || !engagement) return <div className="rounded-2xl border border-red-400/20 bg-red-400/[.07] p-6 text-red-200">{error || 'No engagement is available.'}</div>;
  return <div className="space-y-6 pb-8"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><ShieldCheck className="h-4 w-4" /> Engagement scope</div><h1 className="text-3xl font-semibold tracking-tight text-white">{engagement.name}</h1><p className="mt-2 text-sm text-slate-500">{human(engagement.auditType)} · {new Date(engagement.auditPeriodStart).toLocaleDateString()} — {new Date(engagement.auditPeriodEnd).toLocaleDateString()}</p></div><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">Status</p><p className="mt-2 text-xl font-semibold text-emerald-300">{human(engagement.status)}</p></div><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">Materiality</p><p className="mt-2 text-xl font-semibold text-white">{engagement.materiality == null ? 'Not set' : engagement.materiality.toLocaleString()}</p></div><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">Audit period</p><p className="mt-2 flex items-center gap-2 text-sm font-medium text-white"><CalendarRange className="h-4 w-4 text-sky-300" />{new Date(engagement.auditPeriodStart).toLocaleDateString()} — {new Date(engagement.auditPeriodEnd).toLocaleDateString()}</p></div></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><h2 className="font-semibold text-white">Objective and scope</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-400">{engagement.objective || 'No objective has been recorded.'}</p>{engagement.scope && <p className="mt-4 whitespace-pre-wrap border-t border-white/[.06] pt-4 text-sm leading-6 text-slate-400">{engagement.scope}</p>}</section><section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><h2 className="font-semibold text-white">Exclusions and risk context</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-400">{engagement.exclusions || 'No exclusions have been recorded.'}</p>{engagement.risks?.length ? <ul className="mt-4 space-y-2 border-t border-white/[.06] pt-4 text-sm text-slate-400">{engagement.risks.map(risk => <li key={risk}>• {risk}</li>)}</ul> : null}</section></div></div>;
}
