"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { PublicHeader, PublicFooter } from "@/components/public-shell";

export default function BookDemoPage() {
  const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form).entries()); const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, source: "BOOK_DEMO" }) }); setState(response.ok ? "sent" : "error"); if (response.ok) form.reset(); }
  return <main className="site-shell"><PublicHeader /><section className="page-hero"><div className="section-kicker">Start a conversation</div><h1>See a clearer way to run your hotel.</h1><p>Tell us about your property and we will shape a walkthrough around the way your teams actually work.</p></section><section className="section" style={{ paddingTop: 0 }}><div className="demo-layout"><div><div className="section-kicker">What happens next</div><div className="foundation-grid" style={{ display: "block", marginTop: 25 }}>{[["01", "A focused conversation", "We learn how your property operates today."], ["02", "A tailored walkthrough", "See the workflows that matter to your team."], ["03", "A practical next step", "Leave with a clear implementation path." ]].map(([n, title, body]) => <div className="foundation-card" style={{ marginBottom: 12, minHeight: "auto" }} key={n}><span>{n}</span><h3 style={{ marginTop: 18 }}>{title}</h3><p>{body}</p></div>)}</div></div><form onSubmit={submit} className="foundation-card" style={{ minHeight: 0 }}><div style={{ display: "grid", gap: 15 }}>{[["name", "Full name", "text"], ["email", "Work email", "email"], ["company", "Company / property group", "text"], ["phone", "Phone number", "tel"], ["roomCount", "Number of rooms", "number"]].map(([name, label, type]) => <label key={name} style={{ display: "block", color: "#b6c7d3", fontSize: 12 }}>{label}<input required={name === "name" || name === "email"} name={name} type={type} className="form-field" /></label>)}<label style={{ display: "block", color: "#b6c7d3", fontSize: 12 }}>What would you like to improve?<textarea name="message" rows={4} className="form-field" /></label><label style={{ display: "flex", gap: 10, color: "#8298a8", fontSize: 11, lineHeight: 1.5 }}><input required name="consent" type="checkbox" value="true" />I agree to LodgeCore using these details to contact me about its products and services.</label><button disabled={state === "sending"} className="button button-primary" style={{ border: 0, cursor: "pointer" }}>{state === "sending" ? "Sending…" : "Request a demo ↗"}</button>{state === "sent" && <p style={{ color: "#a9f5c9", fontSize: 12 }}>Thanks—we received your request.</p>}{state === "error" && <p style={{ color: "#ff9d9d", fontSize: 12 }}>We could not submit your request. Please try again.</p>}</div></form></div></section><PublicFooter /></main>;
}
