import prisma from '@hotel-pms/db';
import { ArrowUpRight, BellRing, Building2, CheckCircle2, CircleAlert, CreditCard, Gauge, Layers3, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { requireHQAdmin } from '@/lib/auth/hq';
import { HQPortfolioCharts } from './HQDashboardCharts';

const monthStart = (date: Date) => new Date(date.getFullYear(), date.getMonth(), 1);
const money = (amount: number, currency = 'NGN') => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount / 100);

export default async function HQDashboard() {
  await requireHQAdmin();
  const now = new Date();
  const since = monthStart(new Date(now.getFullYear(), now.getMonth() - 5, 1));
  const [organizations, properties, users, activeStaff, subscriptions, invoices, connections, failedOutbox, recentLogs] = await Promise.all([
    prisma.organization.findMany({ orderBy: { createdAt: 'asc' }, select: { id: true, name: true, slug: true, createdAt: true, properties: { select: { id: true, name: true, isActive: true, businessDate: true, auditStatus: true } }, subscriptions: { orderBy: { createdAt: 'desc' }, take: 1, select: { status: true, plan: { select: { name: true, code: true } } } } } }),
    prisma.property.findMany({ where: { deletedAt: null }, select: { id: true, name: true, city: true, isActive: true, businessDate: true, auditStatus: true, createdAt: true, organization: { select: { id: true, name: true } }, _count: { select: { rooms: true, reservations: true } } }, orderBy: { updatedAt: 'desc' } }),
    prisma.user.count(),
    prisma.staff.count({ where: { isActive: true, deletedAt: null } }),
    prisma.subscription.findMany({ select: { status: true, items: { include: { price: true } } } }),
    prisma.billingInvoice.aggregate({ _sum: { amountDue: true, amountPaid: true }, where: { createdAt: { gte: monthStart(now) } } }),
    prisma.channelConnection.findMany({ select: { status: true } }),
    prisma.outboxEvent.count({ where: { status: { in: ['FAILED', 'DEAD_LETTER'] } } }),
    prisma.auditLog.findMany({ orderBy: { createdAt: 'desc' }, take: 8, include: { organization: { select: { name: true } } } }),
  ]);

  const liveSubscriptions = subscriptions.filter((item) => ['ACTIVE', 'TRIALING'].includes(item.status));
  const mrr = liveSubscriptions.reduce((sum, subscription) => sum + subscription.items.reduce((subtotal, item) => subtotal + (item.price.interval === 'year' ? Math.round(item.price.amount / 12) : item.price.amount), 0), 0);
  const attentionOrganizations = organizations.filter((organization) => { const status = organization.subscriptions[0]?.status; return !organization.properties.some((property) => property.isActive) || ['PAST_DUE', 'PAUSED', 'INCOMPLETE', 'CANCELED'].includes(status || ''); }).length;
  const configuredProperties = properties.filter((property) => property.isActive && property.businessDate && property.auditStatus).length;
  const connectionIssues = connections.filter((connection) => ['ERROR', 'DEGRADED', 'DISCONNECTED'].includes(connection.status)).length;
  const monthly = Array.from({ length: 6 }, (_, index) => { const date = new Date(since); date.setMonth(since.getMonth() + index); return { label: date.toLocaleDateString('en-US', { month: 'short' }), organizations: organizations.filter((organization) => organization.createdAt.getFullYear() === date.getFullYear() && organization.createdAt.getMonth() === date.getMonth()).length, properties: properties.filter((property) => property.createdAt.getFullYear() === date.getFullYear() && property.createdAt.getMonth() === date.getMonth()).length }; });
  const propertyLifecycle = [{ status: 'READY', count: configuredProperties }, { status: 'NEEDS SETUP', count: Math.max(0, properties.length - configuredProperties) }].filter((item) => item.count > 0);
  const subscriptionStatuses = Object.entries(subscriptions.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] || 0) + 1; return acc; }, {})).map(([status, count]) => ({ status, count }));
  const connectionStatuses = Object.entries(connections.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] || 0) + 1; return acc; }, {})).map(([status, count]) => ({ status, count }));
  const organizationRows = organizations.map((organization) => { const subscription = organization.subscriptions[0]; const activePropertyCount = organization.properties.filter((property) => property.isActive).length; const state = !activePropertyCount ? 'Needs setup' : ['PAST_DUE', 'PAUSED', 'INCOMPLETE', 'CANCELED'].includes(subscription?.status || '') ? 'Attention' : 'Operational'; return { id: organization.id, name: organization.name, slug: organization.slug, properties: organization.properties.length, activeProperties: activePropertyCount, plan: subscription?.plan?.name || 'Unconfigured', subscriptionStatus: subscription?.status || 'NO PLAN', state }; });

  return <div className="min-h-full bg-[#07111f] p-5 text-slate-200 sm:p-8 xl:p-10"><div className="mx-auto max-w-[1500px] space-y-7">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.22em] text-indigo-300"><Sparkles className="size-3.5" /> LodgeCore HQ · organisation operations</div><h1 className="text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">Organisation command centre</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Manage the operating activity, property lifecycle, access, subscriptions and controls of every organisation from one executive workspace.</p></div><div className="flex gap-2"><a href="/hq/organizations" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs font-medium text-slate-200 hover:bg-white/[.08]">Organisation directory <ArrowUpRight className="size-3.5" /></a><a href="/hq/activity" className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-3 py-2 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20 hover:bg-indigo-400"><BellRing className="size-3.5" /> Activity log</a></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'Organisations', value: organizations.length, note: `${attentionOrganizations} need HQ attention`, icon: Building2, tone: 'indigo' }, { label: 'Managed properties', value: properties.length, note: `${configuredProperties} lifecycle-ready`, icon: Layers3, tone: 'sky' }, { label: 'Active subscriptions', value: liveSubscriptions.length, note: `${money(mrr)} estimated MRR`, icon: CreditCard, tone: 'emerald' }, { label: 'Access & controls', value: users, note: `${activeStaff} active staff accounts`, icon: ShieldCheck, tone: 'violet' }].map((item) => <div key={item.label} className="rounded-2xl border border-white/10 bg-[#101b2f] p-4 shadow-[0_12px_34px_rgba(0,0,0,.16)]"><div className="flex items-start justify-between"><div><p className="text-[11px] font-medium uppercase tracking-[.13em] text-slate-500">{item.label}</p><p className="mt-3 text-2xl font-semibold tracking-tight text-white">{item.value}</p></div><span className={`flex size-9 items-center justify-center rounded-xl bg-${item.tone}-400/10 text-${item.tone}-300`}><item.icon className="size-4" /></span></div><p className="mt-3 text-xs text-slate-500">{item.note}</p></div>)}</section>
    <HQPortfolioCharts monthly={monthly} organizations={organizationRows} subscriptions={subscriptionStatuses} connections={connectionStatuses} propertyLifecycle={propertyLifecycle} />
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">HQ attention queue</p><p className="mt-1 text-xs text-slate-500">Cross-organisation signals that require intervention</p></div><CircleAlert className="size-5 text-amber-300" /></div><div className="space-y-2">{[{ label: 'Organisation lifecycle', value: attentionOrganizations, detail: 'organisations need setup or billing review', href: '/hq/organizations', color: 'amber' }, { label: 'Distribution health', value: connectionIssues, detail: 'channel connections are degraded or disconnected', href: '/hq/activity', color: 'rose' }, { label: 'Delivery reliability', value: failedOutbox, detail: 'events failed or are dead-lettered', href: '/hq/activity', color: 'violet' }, { label: 'Outstanding invoices', value: money(Number(invoices._sum.amountDue || 0)), detail: 'current month balance due', href: '/hq/invoices', color: 'sky' }].map((item) => <a key={item.label} href={item.href} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] p-3 transition hover:bg-white/[.06]"><div><p className="text-xs font-medium text-slate-200">{item.label}</p><p className="mt-1 text-[11px] text-slate-500">{item.detail}</p></div><span className={`text-sm font-semibold ${item.value === 0 ? 'text-emerald-300' : 'text-white'}`}>{item.value}</span></a>)}</div></div><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">Lifecycle insight</p><p className="mt-1 text-xs text-slate-500">Derived from organisation and property records</p></div><Gauge className="size-5 text-indigo-300" /></div><p className="text-sm leading-6 text-slate-300">{attentionOrganizations ? `${attentionOrganizations} organisation${attentionOrganizations === 1 ? '' : 's'} require${attentionOrganizations === 1 ? 's' : ''} HQ attention before the property estate is fully operational.` : connectionIssues ? `${connectionIssues} distribution connection${connectionIssues === 1 ? '' : 's'} need review across the organisation portfolio.` : 'All organisations have an active property footprint and a healthy subscription state.'}</p><div className="mt-5 flex items-center gap-2 rounded-xl border border-indigo-300/15 bg-indigo-300/[.06] p-3 text-xs text-indigo-100"><CheckCircle2 className="size-4 text-indigo-300" /> All values are sourced from live organisation records.</div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Recent organisation activity</p><p className="mt-1 text-xs text-slate-500">Audit events across every tenant and property estate</p></div><a href="/hq/activity" className="text-xs font-medium text-indigo-300 hover:text-indigo-200">Open audit log <ArrowUpRight className="inline size-3" /></a></div><div className="grid gap-3 md:grid-cols-2">{recentLogs.map((log) => <div key={log.id} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><span className="truncate text-xs font-semibold text-indigo-200">{log.action}</span><span className="shrink-0 text-[11px] text-slate-500">{log.createdAt.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div><p className="mt-2 truncate text-sm text-slate-300">{log.organization.name}</p><p className="mt-1 truncate text-xs text-slate-500">{log.resource} · {log.userEmail || 'System'}</p></div>)}{!recentLogs.length && <p className="text-sm text-slate-500">No organisation activity has been recorded yet.</p>}</div></div><div className="rounded-2xl border border-white/10 bg-[#101b2f] p-5"><div className="mb-5"><p className="text-sm font-semibold text-white">Property lifecycle snapshot</p><p className="mt-1 text-xs text-slate-500">Latest properties requiring setup or oversight</p></div><div className="space-y-2">{properties.slice(0, 6).map((property) => <div key={property.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-200">{property.name}</p><p className="mt-1 truncate text-[11px] text-slate-500">{property.organization.name} · {property.city}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${property.isActive && property.businessDate ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-400/10 text-amber-300'}`}>{property.isActive && property.businessDate ? 'Ready' : 'Review'}</span></div>)}{!properties.length && <p className="text-sm text-slate-500">No properties have been created yet.</p>}</div></div></section>
  </div></div>;
}
