'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { BadgePercent, Download, Gift, Loader2, Search, ShieldCheck, UserCheck } from 'lucide-react';

type Scope = { propertyId: string; propertyName: string; currency: string; auditPeriodStart: string; auditPeriodEnd: string };
type Control = { id: string; kind: 'DISCOUNT' | 'COMPLIMENTARY'; businessDate: string; createdAt: string; reference: string; folioReference?: string | null; guestName: string; amount: number; currency: string; description: string; reason: string; source: string; status: string; operator: string | null; approver: string; requestedBy: string; beneficiary: string; requestedAt: string | null; reviewedAt: string | null; approvalStatus: string; executionStatus: string | null; approvalId: string | null; nightAuditor?: string; notes?: string | null; lineage?: { financialLogs: Array<{ id: string; operationType: string; amount: number | null; reason: string | null; approvalStatus: string; createdAt: string }>; auditLogs: Array<{ id: string; action: string; userEmail?: string | null; userRole?: string | null; requestId?: string | null; createdAt: string }> } };
type Summary = { label: string; count: number; amount: number };
type Response = { scope: Scope; items: Control[]; totals: { discounts: number; complimentary: number; discountCount: number; complimentaryCount: number }; analytics: { byBeneficiary: Summary[]; bySource: Summary[]; byStatus: Summary[]; byDate: Array<{ date: string; count: number; amount: number }> } };
const money = (value: number, currency: string) => new Intl.NumberFormat('en', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value);
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function RevenueControlsPage() {
  const [scope, setScope] = useState<Scope | null>(null); const [kind, setKind] = useState<'all' | 'discounts' | 'complimentary'>('all'); const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ dateFrom: '', dateTo: '', minAmount: '', maxAmount: '', source: '', status: '', operator: '', approver: '', beneficiary: '' }); const [data, setData] = useState<Response | null>(null); const [selected, setSelected] = useState<Control | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (propertyId: string, nextKind = kind, q = query, nextFilters = filters) => { setLoading(true); setError(''); try { const params = new URLSearchParams({ propertyId, kind: nextKind, q }); Object.entries(nextFilters).forEach(([key, value]) => { if (value) params.set(key, value); }); const response = await fetch(`/api/v1/external-auditor/controls?${params}`); const value = await response.json(); if (!response.ok) throw new Error(value.error || 'Unable to load revenue controls'); setData(value); setScope(value.scope); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to load revenue controls'); } finally { setLoading(false); } };
  // The loader is intentionally stable for this one-time scope bootstrap.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(value => { const current = value.scopes?.[0]; if (!current) throw new Error(value.error || 'No active engagement'); setScope(current); return load(current.propertyId); }).catch(value => { setError(value instanceof Error ? value.message : 'Unable to load audit scope'); setLoading(false); }); }, []);
  const controls = useMemo(() => data?.items || [], [data]);
  const exportHref = scope ? `/api/v1/external-auditor/controls?${new URLSearchParams({ propertyId: scope.propertyId, kind, q: query, format: 'csv', ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) })}` : '#';
  return <div className="space-y-6 pb-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-amber-300"><ShieldCheck className="h-4 w-4" /> Revenue controls</div><h1 className="text-3xl font-semibold tracking-tight text-white">Discounts & complimentary register</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Review every concession in the authorized period with its value, reason, operator, approval, and verification trail.</p></div>{scope && <div className="rounded-xl border border-white/[.08] bg-white/[.035] px-3 py-2 text-xs text-slate-400">{scope.propertyName} · {new Date(scope.auditPeriodStart).toLocaleDateString()} — {new Date(scope.auditPeriodEnd).toLocaleDateString()}</div>}</div>
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.05] p-5"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Discounts</p><BadgePercent className="h-4 w-4 text-amber-300" /></div><p className="mt-2 text-2xl font-semibold text-white">{money(data?.totals.discounts || 0, scope?.currency || 'NGN')}</p><p className="mt-1 text-xs text-slate-500">{data?.totals.discountCount || 0} records</p></div><div className="rounded-2xl border border-violet-300/20 bg-violet-300/[.05] p-5"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Complimentary</p><Gift className="h-4 w-4 text-violet-300" /></div><p className="mt-2 text-2xl font-semibold text-white">{money(data?.totals.complimentary || 0, scope?.currency || 'NGN')}</p><p className="mt-1 text-xs text-slate-500">{data?.totals.complimentaryCount || 0} records</p></div></div>
    <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-white/[.08] bg-white/[.035] p-3"><button onClick={() => { setKind('all'); if (scope) void load(scope.propertyId, 'all'); }} className={`rounded-lg px-3 py-2 text-sm ${kind === 'all' ? 'bg-white/[.1] text-white' : 'text-slate-500'}`}>All controls</button><button onClick={() => { setKind('discounts'); if (scope) void load(scope.propertyId, 'discounts'); }} className={`rounded-lg px-3 py-2 text-sm ${kind === 'discounts' ? 'bg-amber-300/10 text-amber-200' : 'text-slate-500'}`}>Discounts</button><button onClick={() => { setKind('complimentary'); if (scope) void load(scope.propertyId, 'complimentary'); }} className={`rounded-lg px-3 py-2 text-sm ${kind === 'complimentary' ? 'bg-violet-300/10 text-violet-200' : 'text-slate-500'}`}>Complimentary</button><div className="relative ml-auto min-w-[220px] flex-1 sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" /><input value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && scope) void load(scope.propertyId); }} placeholder="Search guest, reason, operator…" className="field w-full pl-9" /></div><a href={exportHref} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm text-slate-300 hover:bg-white/[.06]"><Download className="h-4 w-4" /> CSV</a></div>
    <div className="grid gap-2 rounded-2xl border border-white/[.08] bg-white/[.035] p-3 sm:grid-cols-2 lg:grid-cols-4"><input type="date" value={filters.dateFrom} onChange={event => setFilters(value => ({ ...value, dateFrom: event.target.value }))} className="field" /><input type="date" value={filters.dateTo} onChange={event => setFilters(value => ({ ...value, dateTo: event.target.value }))} className="field" /><input type="number" min="0" value={filters.minAmount} onChange={event => setFilters(value => ({ ...value, minAmount: event.target.value }))} placeholder="Minimum amount" className="field" /><input type="number" min="0" value={filters.maxAmount} onChange={event => setFilters(value => ({ ...value, maxAmount: event.target.value }))} placeholder="Maximum amount" className="field" /><input value={filters.source} onChange={event => setFilters(value => ({ ...value, source: event.target.value }))} placeholder="Source" className="field" /><input value={filters.status} onChange={event => setFilters(value => ({ ...value, status: event.target.value }))} placeholder="Status" className="field" /><input value={filters.operator} onChange={event => setFilters(value => ({ ...value, operator: event.target.value }))} placeholder="Operator" className="field" /><div className="flex gap-2"><input value={filters.approver} onChange={event => setFilters(value => ({ ...value, approver: event.target.value }))} placeholder="Approver" className="field min-w-0 flex-1" /><button onClick={() => { if (scope) void load(scope.propertyId); }} className="rounded-lg bg-emerald-300 px-3 text-sm font-semibold text-slate-950">Apply</button></div></div>
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]">{loading ? <div className="flex h-56 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading revenue controls…</div> : <div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="bg-slate-950/30"><tr>{['Type', 'Date / reference', 'Guest', 'Amount', 'Reason', 'Operator', 'Approver', 'Status', ''].map(header => <th key={header} className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{header}</th>)}</tr></thead><tbody className="divide-y divide-white/[.06]">{controls.map(item => <tr key={`${item.kind}-${item.id}`} className="hover:bg-white/[.025]"><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${item.kind === 'DISCOUNT' ? 'bg-amber-300/10 text-amber-200' : 'bg-violet-300/10 text-violet-200'}`}>{item.kind === 'DISCOUNT' ? <BadgePercent className="h-3 w-3" /> : <Gift className="h-3 w-3" />}{human(item.kind)}</span></td><td className="px-5 py-4"><p className="text-slate-300">{new Date(item.businessDate).toLocaleDateString()}</p><p className="mt-1 font-mono text-[11px] text-slate-600">{item.reference}</p></td><td className="px-5 py-4 text-slate-300">{item.guestName}</td><td className="px-5 py-4 font-medium text-white">{money(item.amount, item.currency)}</td><td className="max-w-[230px] px-5 py-4 text-slate-400"><p className="truncate" title={item.reason}>{item.reason}</p></td><td className="px-5 py-4 text-slate-400">{item.operator || 'Not recorded'}</td><td className="px-5 py-4 text-slate-400">{item.approver}</td><td className="px-5 py-4"><span className="rounded-full bg-white/[.06] px-2 py-1 text-[11px] text-slate-300">{human(item.status)}</span></td><td className="px-5 py-4 text-right"><button onClick={() => setSelected(item)} className="text-xs font-medium text-sky-300 hover:text-sky-200">Inspect</button></td></tr>)}</tbody></table>{!controls.length && <div className="p-14 text-center text-sm text-slate-500">No discounts or complimentary records match this audit scope.</div>}</div>}</section>
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 sm:items-center" onClick={() => setSelected(null)}><div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl" onClick={event => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.15em] text-emerald-300">Control detail</p><h2 className="mt-2 text-xl font-semibold text-white">{human(selected.kind)} · {selected.reference}</h2></div><button onClick={() => setSelected(null)} className="text-sm text-slate-500 hover:text-white">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Business date', new Date(selected.businessDate).toLocaleDateString()], ['Guest', selected.guestName], ['Folio / order', selected.folioReference || selected.reference], ['Amount', money(selected.amount, selected.currency)], ['Source', human(selected.source)], ['Reason', selected.reason], ['Operator', selected.operator || 'Not recorded'], ['Requested by', selected.requestedBy], ['Approver', selected.approver], ['Approval status', human(selected.approvalStatus)], ['Execution status', selected.executionStatus ? human(selected.executionStatus) : 'Not applicable'], ['Reviewed at', selected.reviewedAt ? new Date(selected.reviewedAt).toLocaleString() : 'Not recorded'], ['Night auditor', selected.nightAuditor || 'Not applicable']].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[.07] bg-white/[.03] p-3"><p className="text-[11px] uppercase tracking-[.12em] text-slate-600">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div>)}</div>{selected.approvalId && <p className="mt-5 flex items-center gap-2 text-xs text-slate-500"><UserCheck className="h-3.5 w-3.5 text-emerald-300" /> Approval record {selected.approvalId}</p>}{selected.lineage && <div className="mt-5 rounded-xl border border-white/[.07] p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-500">Linked lineage</p><p className="mt-2 text-sm text-slate-300">{selected.lineage.financialLogs.length} financial events · {selected.lineage.auditLogs.length} audit events</p><div className="mt-3 space-y-2 text-xs text-slate-500">{[...selected.lineage.financialLogs.map(event => `${event.operationType} · ${event.approvalStatus} · ${event.reason || 'No reason'}`), ...selected.lineage.auditLogs.map(event => `${event.action} · ${event.userEmail || event.userRole || 'System'}`)].map((event, index) => <p key={`${event}-${index}`} className="border-l border-emerald-300/30 pl-3">{event}</p>)}</div></div>}{selected.notes && <p className="mt-4 rounded-xl border border-white/[.07] p-3 text-sm text-slate-400">{selected.notes}</p>}</div></div>}
    <p className="text-xs text-slate-600">Revenue controls are read-only and limited to the authorized property and audit period. <Link href="/external-auditor/evidence" className="text-emerald-300">Open evidence explorer →</Link></p>
  </div>;
}
