CREATE TYPE "StockItemType" AS ENUM ('SELLABLE', 'RAW_MATERIAL', 'CONSUMABLE', 'CLEANING', 'HOUSEKEEPING', 'ASSET', 'PACKAGING');

ALTER TABLE "StockItem" ADD COLUMN "stockType" "StockItemType" NOT NULL DEFAULT 'CONSUMABLE';
