'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarDays, ChevronRight, Clock3, Loader2, Plus, ShieldCheck } from 'lucide-react';

type Engagement = { id: string; name: string; auditType: string; status: string; propertyId: string; auditPeriodStart: string; auditPeriodEnd: string; objective?: string | null; materiality?: number | null; updatedAt: string };
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());
const statusTone = (status: string) => status === 'COMPLETED' || status === 'CLOSED' ? 'bg-emerald-300/10 text-emerald-300' : status === 'PLANNED' ? 'bg-sky-300/10 text-sky-300' : 'bg-amber-300/10 text-amber-300';

export default function ActiveEngagementsPage() {
  const [items, setItems] = useState<Engagement[]>([]);
  const [filter, setFilter] = useState('ALL');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { void fetch('/api/v1/external-auditor/management?resource=engagements').then(async response => { const value = await response.json(); if (!response.ok) throw new Error(value.error || 'Unable to load engagements'); return value; }).then(value => setItems(value.items || [])).catch(value => setError(value.message)).finally(() => setLoading(false)); }, []);
  const statuses = useMemo(() => ['ALL', ...new Set(items.map(item => item.status))], [items]);
  const visible = items.filter(item => filter === 'ALL' || item.status === filter);
  return <div className="space-y-6 pb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><ShieldCheck className="h-4 w-4" /> External auditor governance</div><h1 className="text-3xl font-semibold tracking-tight text-white">Active engagements</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Monitor every organisation audit engagement, its scope window, lifecycle status, and review readiness.</p></div><Link href="/admin/external-auditors" className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-300 px-4 text-sm font-semibold text-slate-950 transition hover:bg-emerald-200"><Plus className="h-4 w-4" /> New engagement</Link></div>
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">Total engagements</p><p className="mt-2 text-2xl font-semibold text-white">{items.length}</p></div><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">In progress</p><p className="mt-2 text-2xl font-semibold text-amber-300">{items.filter(item => item.status === 'IN_PROGRESS').length}</p></div><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><p className="text-xs text-slate-500">Completed or closed</p><p className="mt-2 text-2xl font-semibold text-emerald-300">{items.filter(item => item.status === 'COMPLETED' || item.status === 'CLOSED').length}</p></div></div>
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.07] px-5 py-4"><div><h2 className="font-semibold text-white">Engagement register</h2><p className="mt-1 text-xs text-slate-500">Live records ordered by most recently updated.</p></div><select value={filter} onChange={event => setFilter(event.target.value)} className="field w-auto">{statuses.map(status => <option key={status} value={status}>{status === 'ALL' ? 'All statuses' : human(status)}</option>)}</select></div>{loading ? <div className="flex min-h-48 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading engagements…</div> : <div className="divide-y divide-white/[.06]">{visible.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-5 p-5 transition hover:bg-white/[.025]"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-white">{item.name}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${statusTone(item.status)}`}>{human(item.status)}</span></div><p className="mt-2 text-xs text-slate-500">{human(item.auditType)} · Property {item.propertyId}</p><p className="mt-2 flex items-center gap-2 text-xs text-slate-400"><CalendarDays className="h-3.5 w-3.5 text-emerald-300" />{new Date(item.auditPeriodStart).toLocaleDateString()} — {new Date(item.auditPeriodEnd).toLocaleDateString()}<span className="text-slate-700">·</span><Clock3 className="h-3.5 w-3.5 text-slate-500" />Updated {new Date(item.updatedAt).toLocaleDateString()}</p>{item.objective && <p className="mt-2 max-w-3xl truncate text-xs text-slate-500">{item.objective}</p>}</div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-[10px] uppercase tracking-[.14em] text-slate-600">Materiality</p><p className="mt-1 text-sm text-slate-300">{item.materiality == null ? 'Not set' : item.materiality.toLocaleString()}</p></div><Link href={`/admin/external-auditors`} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300 transition hover:bg-white/[.06]">Manage <ChevronRight className="h-3.5 w-3.5" /></Link></div></div>)}{!visible.length && <div className="p-14 text-center"><Activity className="mx-auto h-7 w-7 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No engagements match this status.</p></div>}</div>}</section>
  </div>;
}
