'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, KeyRound, Loader2, Send } from 'lucide-react';

export default function InviteAuditorPage() {
  const [email, setEmail] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); const response = await fetch('/api/v1/external-auditor/invitations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const value = await response.json(); if (!response.ok) setError(value.error || 'Unable to send invitation'); else { setMessage(`Invitation sent to ${value.email}.`); setEmail(''); } setSaving(false); };
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-slate-200 sm:px-8"><div className="mx-auto max-w-2xl"><Link href="/admin/external-auditors" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to auditor management</Link><section className="mt-8 rounded-3xl border border-white/[.08] bg-white/[.035] p-7"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-300 text-slate-950"><KeyRound className="h-5 w-5" /></div><h1 className="mt-6 text-3xl font-semibold text-white">Invite an external auditor</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">The invitee receives a one-time setup link, creates their own password, and is provisioned with the external-auditor role. Access to a property is granted separately from the management register.</p><form onSubmit={submit} className="mt-8 flex flex-col gap-3 sm:flex-row"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="auditor@example.com" className="field flex-1" autoComplete="email" /><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />} Send invitation</button></form>{message && <p className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/[.07] p-3 text-sm text-emerald-200">{message}</p>}{error && <p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/[.07] p-3 text-sm text-red-200">{error}</p>}<p className="mt-6 text-xs leading-5 text-slate-600">Invitation delivery requires <code>RESEND_API_KEY</code> and <code>RESEND_FROM_EMAIL</code> in the production environment.</p></section></div></main>;
}
