'use client';

import { useEffect, useState } from 'react';
import { BarChart3, BookOpen, CalendarDays, CheckCircle2, Download, FileSpreadsheet, FileText, Loader2, Table2 } from 'lucide-react';

const reports = [{ key: 'general-ledger', title: 'General ledger', description: 'Entry-level activity with account, source, debit, and credit lineage.', icon: BookOpen }, { key: 'trial-balance', title: 'Trial balance', description: 'Posted account balances for the authorized audit period.', icon: BarChart3 }, { key: 'revenue', title: 'Revenue audit', description: 'Source-level charge detail across room, F&B, tax, and other revenue.', icon: FileSpreadsheet }, { key: 'night-audit', title: 'Night audit summary', description: 'Daily close status, revenue, occupancy, ADR, and exceptions.', icon: CalendarDays }];
type Report = { headers: string[]; rows: unknown[][]; scope?: { propertyName?: string; auditPeriodStart: string; auditPeriodEnd: string; currency?: string } };

export default function ExternalAuditorReports() {
  const [propertyId, setPropertyId] = useState(''); const [scope, setScope] = useState<Report['scope']>(); const [report, setReport] = useState<Report | null>(null); const [kind, setKind] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(v => { const first = v.scopes?.[0]; if (first) { setPropertyId(first.propertyId); setScope(first); } }); }, []);
  const view = (key: string) => { if (!propertyId) return; setKind(key); setLoading(true); setError(''); void fetch(`/api/v1/external-auditor/reports?propertyId=${propertyId}&kind=${key}`).then(async r => { const value = await r.json(); if (!r.ok) throw new Error(value.error || 'Unable to generate report'); return value; }).then(value => { setReport(value); setScope(value.scope); }).catch(e => setError(e.message)).finally(() => setLoading(false)); };
  const exportHref = (key: string) => propertyId ? `/api/v1/external-auditor/reports?propertyId=${propertyId}&kind=${key}&format=csv` : '#';
  return <div className="space-y-6 pb-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><FileText className="h-4 w-4" /> Audit deliverables</div><h1 className="text-3xl font-semibold tracking-tight text-white">Reports & exports</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Generate reconciled, period-scoped reporting directly from the PMS ledger and close records.</p></div>{scope && <div className="flex items-center gap-2 rounded-xl border border-white/[.08] bg-white/[.035] px-3 py-2 text-xs text-slate-400"><CalendarDays className="h-4 w-4 text-emerald-300" />{new Date(scope.auditPeriodStart).toLocaleDateString()} — {new Date(scope.auditPeriodEnd).toLocaleDateString()}</div>}</div>
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    <div className="grid gap-4 lg:grid-cols-2">{reports.map(item => <div key={item.key} className={`rounded-2xl border p-5 transition ${kind === item.key ? 'border-emerald-300/30 bg-emerald-300/[.06]' : 'border-white/[.08] bg-white/[.035]'}`}><div className="flex items-start gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/[.06] text-emerald-300"><item.icon className="h-5 w-5" /></div><div className="min-w-0"><h2 className="font-semibold text-white">{item.title}</h2><p className="mt-1 text-sm leading-5 text-slate-500">{item.description}</p></div></div><div className="mt-5 flex items-center gap-2"><button onClick={() => view(item.key)} disabled={!propertyId || loading} className="inline-flex h-9 items-center gap-2 rounded-lg bg-emerald-300 px-3 text-sm font-semibold text-slate-950 transition hover:bg-emerald-200 disabled:opacity-50">{loading && kind === item.key ? <Loader2 className="h-4 w-4 animate-spin" /> : <Table2 className="h-4 w-4" />} Preview report</button><a href={exportHref(item.key)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-white/10 px-3 text-sm font-medium text-slate-300 transition hover:bg-white/[.06] aria-disabled:pointer-events-none aria-disabled:opacity-40"><Download className="h-4 w-4" /> Export CSV</a></div></div>)}</div>
    {report && <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[.07] px-5 py-4 sm:px-6"><div><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><h2 className="font-semibold text-white">{reports.find(item => item.key === kind)?.title}</h2></div><p className="mt-1 text-xs text-slate-500">{report.rows.length.toLocaleString()} rows · generated from live PMS data</p></div><span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-[11px] font-semibold text-emerald-300">Read-only preview</span></div><div className="max-h-[560px] overflow-auto"><table className="min-w-full text-left text-sm"><thead className="sticky top-0 bg-[#132036]"><tr>{report.headers.map(header => <th key={header} className="whitespace-nowrap border-b border-white/[.08] px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{header}</th>)}</tr></thead><tbody className="divide-y divide-white/[.06]">{report.rows.map((row, index) => <tr key={index} className="hover:bg-white/[.025]">{row.map((cell, cellIndex) => <td key={cellIndex} className="whitespace-nowrap px-4 py-3 text-slate-300">{cell == null ? '—' : String(cell)}</td>)}</tr>)}</tbody></table>{!report.rows.length && <div className="p-14 text-center text-sm text-slate-500">This report contains no rows for the authorized period.</div>}</div></section>}
  </div>;
}
