'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, ClipboardList, Loader2, Package, RefreshCw, Send, UserRound, X } from 'lucide-react';
import { useLodgeCoreSession } from '@/lib/auth/useLodgeCoreSession';
import { useProperty } from '@/components/PropertyProvider';
import { cn } from '@/lib/utils';

type Warehouse = { id: string; name: string };
type StockItem = { id: string; name: string; baseUnit: string; quantityOnHand: number | string; reorderLevel?: number | string | null; warehouse: Warehouse; inventoryCategory?: { name?: string } | null };
type Request = { id: string; transferRef: string; status: string; notes?: string | null; createdAt: string; fromWarehouse: Warehouse; toWarehouse: Warehouse; items: { quantity: number | string; unitOfMeasure: string; stockItem: { name: string; baseUnit: string } }[] };
type Issue = { id: string; quantity: number | string; notes?: string | null; timestamp: string; stockItem: { name: string; baseUnit: string }; warehouse?: Warehouse | null };
type InventoryData = { warehouses: Warehouse[]; mainWarehouses: Warehouse[]; mainStock: StockItem[]; stock: StockItem[]; requests: Request[]; issues: Issue[] };

const badge = (status: string) => status === 'PENDING_APPROVAL' ? 'border-amber-300/20 bg-amber-300/10 text-amber-200' : ['APPROVED', 'RECEIVED', 'COMPLETED'].includes(status) ? 'border-emerald-300/20 bg-emerald-300/10 text-emerald-300' : 'border-white/10 bg-white/[0.05] text-slate-400';
const formatDate = (value: string) => new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });

export default function HousekeepingInventoryView() {
  const { data: session } = useLodgeCoreSession();
  const { propertyId: selectedPropertyId } = useProperty();
  const propertyId = session?.user?.propertyId || selectedPropertyId;
  const [data, setData] = useState<InventoryData | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState('');
  const [dialog, setDialog] = useState<'request' | 'issue' | null>(null);
  const [saving, setSaving] = useState(false);
  const [requestLines, setRequestLines] = useState([{ stockItemId: '', quantity: '1' }]);
  const [requestSourceWarehouseId, setRequestSourceWarehouseId] = useState('');
  const [requestWarehouseId, setRequestWarehouseId] = useState('');
  const [requestNotes, setRequestNotes] = useState('');
  const [issue, setIssue] = useState({ warehouseId: '', stockItemId: '', quantity: '1', notes: '' });

  const load = useCallback(async (silent = false) => {
    if (!propertyId) return;
    silent ? setRefreshing(true) : setLoading(true);
    try { const response = await fetch('/api/v1/housekeeping/inventory', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Unable to load housekeeping inventory'); setData(payload.data); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load inventory'); } finally { setLoading(false); setRefreshing(false); }
  }, [propertyId]);
  useEffect(() => { void load(); }, [load]);

  const outletStock = useMemo(() => data?.stock.filter((item) => data.warehouses.some((warehouse) => warehouse.id === item.warehouse.id)) || [], [data]);
  const lowStock = outletStock.filter((item) => item.reorderLevel != null && Number(item.quantityOnHand) <= Number(item.reorderLevel));
  const submit = async (action: 'REQUEST' | 'ISSUE') => {
    setSaving(true); setError('');
    try { const body = action === 'REQUEST' ? { action, fromWarehouseId: requestSourceWarehouseId || data?.mainWarehouses[0]?.id, toWarehouseId: requestWarehouseId, items: requestLines.filter((line) => line.stockItemId).map((line) => ({ stockItemId: line.stockItemId, quantity: Number(line.quantity) })), notes: requestNotes } : { action, ...issue }; const response = await fetch('/api/v1/housekeeping/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Inventory action failed'); setDialog(null); setRequestLines([{ stockItemId: '', quantity: '1' }]); setRequestSourceWarehouseId(''); setRequestNotes(''); setIssue({ warehouseId: '', stockItemId: '', quantity: '1', notes: '' }); await load(true); } catch (err) { setError(err instanceof Error ? err.message : 'Inventory action failed'); } finally { setSaving(false); }
  };

  if (loading) return <div className="flex min-h-[60vh] items-center justify-center text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Loading outlet inventory…</div>;
  if (!data) return <div className="p-8 text-sm text-rose-300">{error || 'Inventory is unavailable.'}</div>;
  return <div className="mx-auto max-w-[1500px] space-y-6 p-5 sm:p-8">
    <section className="rounded-3xl border border-cyan-300/10 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,0.12),transparent_38%),#0b1728] p-6 sm:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-300"><Package className="h-4 w-4" /> Housekeeping inventory control</div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Rooms &amp; laundry stock</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Monitor department stock, request replenishment from the main warehouse, and maintain a traceable issue record for every team member.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => void load(true)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold text-slate-300 hover:bg-white/[0.06]"><RefreshCw className={cn('h-4 w-4', refreshing && 'animate-spin')} />Refresh</button><button onClick={() => setDialog('request')} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-[#06202a] hover:bg-cyan-200"><Send className="h-4 w-4" />Request stock</button><button onClick={() => setDialog('issue')} className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-2.5 text-sm font-semibold text-emerald-200 hover:bg-emerald-300/20"><UserRound className="h-4 w-4" />Issue to staff</button></div></div></section>
    {error && <div className="flex items-center gap-2 rounded-xl border border-rose-300/20 bg-rose-300/10 px-4 py-3 text-sm text-rose-200"><AlertTriangle className="h-4 w-4" />{error}</div>}
    <div className="grid gap-4 md:grid-cols-3"><Metric label="Outlet stock lines" value={String(outletStock.length)} detail={`${data.warehouses.length} department warehouses`} /><Metric label="Low stock attention" value={String(lowStock.length)} detail="At or below reorder level" tone={lowStock.length ? 'amber' : 'emerald'} /><Metric label="Open replenishment" value={String(data.requests.filter((request) => !['COMPLETED', 'CANCELLED', 'REJECTED'].includes(request.status)).length)} detail="Requests with stock manager" tone="cyan" /></div>
    <section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Department stock position</h2><p className="mt-1 text-xs text-slate-500">Housekeeping and laundry outlet warehouses only.</p></div><span className="text-xs text-slate-600">Live balance</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.14em] text-slate-600"><tr>{['Item', 'Warehouse', 'Category', 'On hand', 'Reorder', ''].map((heading) => <th key={heading} className="px-3 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.06]">{outletStock.map((item) => { const low = item.reorderLevel != null && Number(item.quantityOnHand) <= Number(item.reorderLevel); return <tr key={item.id} className="hover:bg-white/[0.025]"><td className="px-3 py-4 font-semibold text-slate-200">{item.name}<span className="ml-2 text-[10px] text-slate-600">{item.baseUnit}</span></td><td className="px-3 py-4 text-slate-400">{item.warehouse.name}</td><td className="px-3 py-4 text-slate-500">{item.inventoryCategory?.name || 'General'}</td><td className={cn('px-3 py-4 font-semibold', low ? 'text-amber-300' : 'text-emerald-300')}>{Number(item.quantityOnHand).toLocaleString()} {item.baseUnit}</td><td className="px-3 py-4 text-slate-500">{item.reorderLevel ?? '—'}</td><td className="px-3 py-4 text-right">{low && <span className="inline-flex items-center gap-1 text-xs font-semibold text-amber-300"><AlertTriangle className="h-3.5 w-3.5" />Replenish</span>}</td></tr>})}{!outletStock.length && <tr><td colSpan={6} className="px-3 py-12 text-center text-sm text-slate-600">No housekeeping or laundry outlet warehouse stock has been provisioned yet.</td></tr>}</tbody></table></div></section>
    <div className="grid gap-6 xl:grid-cols-2"><Activity title="Replenishment requests" icon={ClipboardList}>{data.requests.map((request) => <div key={request.id} className="flex items-center gap-3 border-b border-white/[0.06] py-3 last:border-0"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{request.transferRef} · {request.toWarehouse.name}</p><p className="mt-1 text-xs text-slate-600">{request.items.length} line(s) · {formatDate(request.createdAt)}</p></div><span className={cn('rounded-full border px-2 py-1 text-[10px] font-bold uppercase', badge(request.status))}>{request.status.replaceAll('_', ' ')}</span></div>)}{!data.requests.length && <Empty text="No replenishment requests yet." />}</Activity><Activity title="Recent staff issues" icon={UserRound}>{data.issues.map((entry) => <div key={entry.id} className="flex items-center gap-3 border-b border-white/[0.06] py-3 last:border-0"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{entry.stockItem.name}</p><p className="mt-1 truncate text-xs text-slate-600">{entry.notes || 'Staff issue'} · {formatDate(entry.timestamp)}</p></div><span className="text-sm font-semibold text-amber-200">{Math.abs(Number(entry.quantity))} {entry.stockItem.baseUnit}</span></div>)}{!data.issues.length && <Empty text="No staff issues have been recorded." />}</Activity></div>
    {dialog === 'request' && <Dialog title="Request stock from main warehouse" onClose={() => setDialog(null)}><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/[0.06] px-3 py-2 text-xs text-cyan-100">Only Housekeeping, Laundry, and Linen categories are requestable. Quantities must be entered in the item&apos;s base unit.</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={requestSourceWarehouseId} onChange={(event) => setRequestSourceWarehouseId(event.target.value)} className="field"><option value="">Select source warehouse</option>{data.mainWarehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select><select value={requestWarehouseId} onChange={(event) => setRequestWarehouseId(event.target.value)} className="field"><option value="">Select department warehouse</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></div><div className="mt-4 space-y-3">{requestLines.map((line, index) => <div key={index} className="grid grid-cols-[1fr_100px_36px] gap-2"><select value={line.stockItemId} onChange={(event) => setRequestLines(requestLines.map((current, currentIndex) => currentIndex === index ? { ...current, stockItemId: event.target.value } : current))} className="field"><option value="">Select Housekeeping/Laundry item</option>{data.mainStock.filter((item) => item.warehouse.id === (requestSourceWarehouseId || data.mainWarehouses[0]?.id)).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.quantityOnHand} {item.baseUnit} base</option>)}</select><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={(event) => setRequestLines(requestLines.map((current, currentIndex) => currentIndex === index ? { ...current, quantity: event.target.value } : current))} className="field" placeholder="Base qty" /><button type="button" onClick={() => setRequestLines(requestLines.filter((_, currentIndex) => currentIndex !== index))} className="rounded-xl border border-white/10 text-slate-500 hover:text-rose-300"><X className="mx-auto h-4 w-4" /></button></div>)}</div><button type="button" onClick={() => setRequestLines([...requestLines, { stockItemId: '', quantity: '1' }])} className="mt-3 text-xs font-semibold text-cyan-300">+ Add another line</button><textarea value={requestNotes} onChange={(event) => setRequestNotes(event.target.value)} className="field mt-4 min-h-20" placeholder="Reason, arrival pressure, or linen par note…" /><Actions saving={saving} label="Submit request" onClick={() => void submit('REQUEST')} /></Dialog>}
    {dialog === 'issue' && <Dialog title="Issue stock for operational use" onClose={() => setDialog(null)}><select value={issue.warehouseId} onChange={(event) => setIssue({ ...issue, warehouseId: event.target.value, stockItemId: '' })} className="field"><option value="">Select department warehouse</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select><select value={issue.stockItemId} onChange={(event) => setIssue({ ...issue, stockItemId: event.target.value })} className="field mt-3"><option value="">Select stock item</option>{outletStock.filter((item) => item.warehouse.id === issue.warehouseId).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.quantityOnHand} {item.baseUnit}</option>)}</select><input type="number" min="0.01" step="0.01" value={issue.quantity} onChange={(event) => setIssue({ ...issue, quantity: event.target.value })} className="field mt-3" placeholder="Quantity" /><textarea value={issue.notes} onChange={(event) => setIssue({ ...issue, notes: event.target.value })} className="field mt-3 min-h-20" placeholder="Usage purpose, shift, or operational note…" /><Actions saving={saving} label="Record issue" onClick={() => void submit('ISSUE')} /></Dialog>}
  </div>;
}

function Metric({ label, value, detail, tone = 'cyan' }: { label: string; value: string; detail: string; tone?: string }) { return <div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-600">{label}</p><p className={cn('mt-4 text-3xl font-semibold', tone === 'amber' ? 'text-amber-200' : tone === 'emerald' ? 'text-emerald-300' : 'text-white')}>{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }
function Activity({ title, icon: Icon, children }: { title: string; icon: React.ElementType; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-cyan-300" /><h2 className="font-semibold text-white">{title}</h2></div><div className="mt-4">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="py-8 text-center text-sm text-slate-600">{text}</p>; }
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-[#0d1b2d] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">{title}</h2><button onClick={onClose} className="text-slate-500 hover:text-white"><X className="h-5 w-5" /></button></div><div className="mt-5">{children}</div></div></div>; }
function Actions({ saving, label, onClick }: { saving: boolean; label: string; onClick: () => void }) { return <div className="mt-5 flex justify-end border-t border-white/[0.07] pt-4"><button onClick={onClick} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-[#06202a] disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}{label}</button></div>; }
