'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, BedDouble, CheckCircle2, Clock3, DoorOpen, Loader2, RefreshCw, Sparkles, Wrench, X } from 'lucide-react';
import { useLodgeCoreSession } from '@/lib/auth/useLodgeCoreSession';
import { cn } from '@/lib/utils';

type ViewMode = 'overview' | 'tasks' | 'maintenance' | 'rooms' | 'reports';
type Task = { id: string; roomId: string; status: string; priority: string; type: string; notes?: string | null; room?: { number?: string; roomType?: { name?: string }; status?: string } };
type Ticket = { id: string; title: string; description: string; status: string; priority: string; roomNumber?: string; location?: string; createdAt: string };

const taskLabel: Record<string, string> = { CLEANING: 'Cleaning', INSPECTED: 'Inspected', MAINTENANCE_REQUIRED: 'Maintenance required', CANCELLED: 'Cancelled' };
const ticketTransitions: Record<string, string[]> = { OPEN: ['ASSIGNED', 'CANCELLED'], ASSIGNED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['WAITING_PARTS', 'RESOLVED', 'CANCELLED'], WAITING_PARTS: ['IN_PROGRESS', 'CANCELLED'] };

function Pill({ children, tone = 'slate' }: { children: React.ReactNode; tone?: 'slate' | 'cyan' | 'emerald' | 'amber' | 'rose' }) {
  const tones = { slate: 'border-white/10 bg-white/[0.04] text-slate-400', cyan: 'border-cyan-300/20 bg-cyan-300/10 text-cyan-200', emerald: 'border-emerald-300/20 bg-emerald-300/10 text-emerald-300', amber: 'border-amber-300/20 bg-amber-300/10 text-amber-200', rose: 'border-rose-300/20 bg-rose-300/10 text-rose-300' };
  return <span className={cn('inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold', tones[tone])}>{children}</span>;
}

function toneForStatus(status: string) { if (['INSPECTED', 'RESOLVED'].includes(status)) return 'emerald' as const; if (['MAINTENANCE_REQUIRED', 'CRITICAL', 'CANCELLED'].includes(status)) return 'rose' as const; if (['CLEANING', 'IN_PROGRESS', 'ASSIGNED'].includes(status)) return 'cyan' as const; return 'amber' as const; }

export default function ManagerOperationsView({ mode }: { mode: ViewMode }) {
  const { data: session } = useLodgeCoreSession();
  const propertyId = (session?.user as any)?.propertyId as string | undefined;
  const [tasks, setTasks] = useState<Task[]>([]);
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState('');
  const [selected, setSelected] = useState<Task | Ticket | null>(null);
  const [dialogType, setDialogType] = useState<'task' | 'ticket' | null>(null);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async (quiet = false) => {
    if (!propertyId) return;
    if (quiet) setRefreshing(true); else setLoading(true);
    setError('');
    try {
      const [taskResponse, ticketResponse] = await Promise.all([
        fetch(`/api/v1/housekeeping/tasks?propertyId=${propertyId}`, { cache: 'no-store' }),
        fetch(`/api/v1/maintenance/tickets?propertyId=${propertyId}`, { cache: 'no-store' }),
      ]);
      const taskJson = await taskResponse.json(); const ticketJson = await ticketResponse.json();
      if (!taskResponse.ok) throw new Error(taskJson.error?.message || taskJson.error || 'Unable to load housekeeping tasks');
      if (!ticketResponse.ok) throw new Error(ticketJson.error?.message || ticketJson.error || 'Unable to load maintenance tickets');
      setTasks(Array.isArray(taskJson.data) ? taskJson.data : []);
      setTickets(Array.isArray(ticketJson.data) ? ticketJson.data : ticketJson.data?.tickets || []);
    } catch (err: any) { setError(err.message || 'Unable to load operational data'); } finally { setLoading(false); setRefreshing(false); }
  }, [propertyId]);

  useEffect(() => { load(); }, [load]);

  const metrics = useMemo(() => ({ cleaning: tasks.filter((task) => ['PENDING', 'ASSIGNED', 'CLEANING', 'CLEAN'].includes(task.status)).length, inspected: tasks.filter((task) => task.status === 'INSPECTED').length, maintenance: tasks.filter((task) => task.status === 'MAINTENANCE_REQUIRED').length, openTickets: tickets.filter((ticket) => !['RESOLVED', 'CANCELLED', 'CLOSED'].includes(ticket.status)).length, critical: tickets.filter((ticket) => ticket.priority === 'CRITICAL').length }), [tasks, tickets]);

  const updateTask = async (task: Task, status: string) => { setSaving(true); try { const response = await fetch(`/api/v1/housekeeping/tasks/${task.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error('Unable to update housekeeping task'); setDialogType(null); setSelected(null); await load(true); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };
  const updateTicket = async (ticket: Ticket, status: string) => { setSaving(true); try { const response = await fetch(`/api/v1/maintenance/tickets/${ticket.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error('Unable to update maintenance ticket'); setDialogType(null); setSelected(null); await load(true); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };

  if (loading) return <div className="flex min-h-[70vh] items-center justify-center text-slate-500"><Loader2 className="mr-3 h-5 w-5 animate-spin text-cyan-300" />Loading operational intelligence…</div>;
  if (!propertyId) return <div className="p-8 text-slate-400">No property is assigned to this account.</div>;

  const title = mode === 'overview' ? 'Rooms & care command center' : mode === 'tasks' ? 'Room operations' : mode === 'maintenance' ? 'Maintenance control' : mode === 'rooms' ? 'Room readiness' : 'Performance reports';
  const subtitle = mode === 'overview' ? 'A single operating picture for clean rooms, service exceptions, and engineering response.' : mode === 'tasks' ? 'Direct the daily room-turn workflow from cleaning through inspection.' : mode === 'maintenance' ? 'Track engineering issues before they become guest-impacting incidents.' : mode === 'rooms' ? 'See which rooms are sellable, in service, or blocked by an exception.' : 'Review service throughput and unresolved operational risk.';
  const visibleTasks = mode === 'maintenance' ? [] : tasks;
  const visibleTickets = mode === 'tasks' ? [] : tickets;

  return <div className="mx-auto max-w-[1500px] space-y-7 px-4 py-7 sm:px-8 sm:py-9">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.22em] text-cyan-300"><Sparkles className="h-3.5 w-3.5" />Property operations</div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{subtitle}</p></div><button onClick={() => load(true)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-semibold text-slate-300 transition hover:bg-white/[0.08] hover:text-white"><RefreshCw className={cn('h-4 w-4', refreshing && 'animate-spin')} />Refresh view</button></div>
    {error && <div className="flex items-center justify-between rounded-2xl border border-rose-300/20 bg-rose-300/[0.06] px-4 py-3 text-sm text-rose-200"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Cleaning queue', metrics.cleaning, 'cyan', Sparkles], ['Inspected', metrics.inspected, 'emerald', CheckCircle2], ['Maintenance queue', metrics.openTickets, 'amber', Wrench], ['Room exceptions', metrics.maintenance, 'rose', AlertTriangle], ['Critical issues', metrics.critical, 'rose', Clock3]].map(([label, value, tone, Icon]: any) => <div key={label} className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="flex items-center justify-between"><p className="text-[11px] font-bold uppercase tracking-[0.13em] text-slate-500">{label}</p><Icon className={cn('h-4 w-4', tone === 'emerald' ? 'text-emerald-300' : tone === 'rose' ? 'text-rose-300' : tone === 'amber' ? 'text-amber-300' : 'text-cyan-300')} /></div><p className="mt-4 text-3xl font-semibold tracking-tight text-white">{value}</p><p className="mt-1 text-xs text-slate-600">Live property position</p></div>)}</div>
    {mode === 'overview' && <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold text-white">Today’s operating pulse</h2><p className="mt-1 text-xs text-slate-500">Priority queues requiring a manager’s attention.</p></div><Pill tone="cyan">Live</Pill></div><div className="space-y-3">{tasks.slice(0, 5).map((task) => <button key={task.id} onClick={() => { setSelected(task); setDialogType('task'); }} className="flex w-full items-center justify-between rounded-xl border border-white/[0.06] bg-[#0a1728] p-4 text-left transition hover:border-cyan-300/20 hover:bg-cyan-300/[0.04]"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-200"><BedDouble className="h-4 w-4" /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-slate-200">Room {task.room?.number || '—'} · {task.type || 'Cleaning'}</span><span className="mt-1 block truncate text-xs text-slate-500">{task.room?.roomType?.name || 'Guest room'} · {task.notes || 'No operational note'}</span></span></div><span className="ml-3 shrink-0"><Pill tone={toneForStatus(task.status)}>{taskLabel[task.status] || task.status}</Pill></span></button>)}{!tasks.length && <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No housekeeping tasks are open today.</div>}</div></section><section className="rounded-2xl border border-white/[0.08] bg-gradient-to-br from-cyan-300/[0.12] to-emerald-300/[0.04] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-200">Manager brief</p><h2 className="mt-2 text-xl font-semibold text-white">Protect room readiness</h2></div><ShieldIcon /></div><p className="mt-4 text-sm leading-6 text-slate-400">Resolve engineering blockers first, then move rooms through cleaning and inspection. The front desk only receives a clean, inspected room.</p><div className="mt-6 space-y-3"><LinkCard href="/housekeeping-manager/maintenance" label="Review maintenance queue" value={`${metrics.openTickets} open tickets`} icon={Wrench} /><LinkCard href="/housekeeping-manager/rooms" label="Open room readiness" value={`${metrics.inspected} inspected today`} icon={DoorOpen} /></div></section></div>}
    {mode !== 'overview' && mode !== 'rooms' && <section className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><div className="border-b border-white/[0.07] px-5 py-4"><p className="font-semibold text-white">{mode === 'tasks' ? 'Housekeeping task register' : 'Maintenance ticket register'}</p><p className="mt-1 text-xs text-slate-500">Select a record to review and move it through its controlled workflow.</p></div><div className="divide-y divide-white/[0.06]">{(mode === 'tasks' ? visibleTasks : visibleTickets).map((record: any) => mode === 'tasks' ? <button key={record.id} onClick={() => { setSelected(record); setDialogType('task'); }} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left hover:bg-white/[0.025]"><div className="flex min-w-0 items-center gap-3"><BedDouble className="h-4 w-4 shrink-0 text-cyan-300" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-200">Room {record.room?.number || '—'} <span className="font-normal text-slate-500">· {record.type}</span></p><p className="mt-1 truncate text-xs text-slate-600">{record.room?.roomType?.name || 'Guest room'} · {record.notes || 'No note recorded'}</p></div></div><div className="flex shrink-0 items-center gap-3"><Pill tone={toneForStatus(record.status)}>{taskLabel[record.status] || record.status}</Pill><ArrowRight className="h-4 w-4 text-slate-600" /></div></button> : <button key={record.id} onClick={() => { setSelected(record); setDialogType('ticket'); }} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left hover:bg-white/[0.025]"><div className="flex min-w-0 items-center gap-3"><Wrench className="h-4 w-4 shrink-0 text-amber-300" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-200">{record.title}</p><p className="mt-1 truncate text-xs text-slate-600">Room {record.roomNumber || record.location || '—'} · {record.description}</p></div></div><div className="flex shrink-0 items-center gap-3"><Pill tone={toneForStatus(record.status)}>{record.status}</Pill><Pill tone={record.priority === 'CRITICAL' ? 'rose' : 'slate'}>{record.priority}</Pill></div></button>)}{!(mode === 'tasks' ? visibleTasks : visibleTickets).length && <div className="p-14 text-center text-sm text-slate-500">No records match this operational view.</div>}</div></section>}
    {mode === 'rooms' && <RoomReadiness tasks={tasks} tickets={tickets} />}
    {mode === 'reports' && <Reports tasks={tasks} tickets={tickets} />}
    {dialogType && selected && <RecordDialog type={dialogType} record={selected as any} saving={saving} onClose={() => { setDialogType(null); setSelected(null); }} onTaskStatus={(status) => updateTask(selected as Task, status)} onTicketStatus={(status) => updateTicket(selected as Ticket, status)} />}
  </div>;
}

function ShieldIcon() { return <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-200"><CheckCircle2 className="h-5 w-5" /></span>; }
function LinkCard({ href, label, value, icon: Icon }: { href: string; label: string; value: string; icon: any }) { return <a href={href} className="flex items-center justify-between rounded-xl border border-white/10 bg-[#07111f]/50 p-3 transition hover:border-cyan-300/30"><span className="flex items-center gap-3"><Icon className="h-4 w-4 text-cyan-300" /><span><span className="block text-sm font-semibold text-slate-200">{label}</span><span className="block text-xs text-slate-500">{value}</span></span></span><ArrowRight className="h-4 w-4 text-slate-600" /></a>; }
function RoomReadiness({ tasks, tickets }: { tasks: Task[]; tickets: Ticket[] }) { const rows = tasks.map((task) => ({ room: task.room?.number || '—', type: task.room?.roomType?.name || 'Guest room', roomStatus: task.room?.status || '—', task: taskLabel[task.status] || task.status, blocked: task.status === 'MAINTENANCE_REQUIRED' || tickets.some((ticket) => ticket.roomNumber === task.room?.number && !['RESOLVED', 'CANCELLED', 'CLOSED'].includes(ticket.status)) })); return <section className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.035]"><div className="border-b border-white/[0.07] px-5 py-4"><p className="font-semibold text-white">Room readiness board</p><p className="mt-1 text-xs text-slate-500">Operational readiness derived from housekeeping and maintenance records.</p></div><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <div key={row.room} className="rounded-xl border border-white/[0.07] bg-[#0a1728] p-4"><div className="flex items-start justify-between"><div><p className="text-2xl font-semibold text-white">{row.room}</p><p className="mt-1 text-xs text-slate-500">{row.type}</p></div><Pill tone={row.blocked ? 'rose' : row.task === 'Inspected' ? 'emerald' : 'cyan'}>{row.blocked ? 'Blocked' : row.task}</Pill></div><div className="mt-5 flex items-center justify-between text-xs"><span className="text-slate-600">PMS status</span><span className="text-slate-300">{row.roomStatus}</span></div></div>)}{!rows.length && <div className="col-span-full p-10 text-center text-sm text-slate-500">No room readiness records are available yet.</div>}</div></section>; }
function Reports({ tasks, tickets }: { tasks: Task[]; tickets: Ticket[] }) { const total = tasks.length || 1; const inspected = tasks.filter((task) => task.status === 'INSPECTED').length; const resolved = tickets.filter((ticket) => ticket.status === 'RESOLVED').length; return <div className="grid gap-5 lg:grid-cols-3"><ReportCard label="Inspection completion" value={`${Math.round((inspected / total) * 100)}%`} detail={`${inspected} of ${tasks.length} tracked tasks inspected`} /><ReportCard label="Maintenance resolution" value={`${resolved}`} detail={`${tickets.length} tickets recorded in the current feed`} /><ReportCard label="Critical exposure" value={`${tickets.filter((ticket) => ticket.priority === 'CRITICAL' && ticket.status !== 'RESOLVED').length}`} detail="Critical tickets still requiring attention" /></div>; }
function ReportCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-6"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500">{label}</p><p className="mt-5 text-4xl font-semibold text-white">{value}</p><p className="mt-2 text-sm text-slate-500">{detail}</p></div>; }
function RecordDialog({ type, record, saving, onClose, onTaskStatus, onTicketStatus }: { type: 'task' | 'ticket'; record: any; saving: boolean; onClose: () => void; onTaskStatus: (status: string) => void; onTicketStatus: (status: string) => void }) { const isTask = type === 'task'; const nextStatuses = isTask ? (record.status === 'CLEANING' || ['PENDING', 'ASSIGNED', 'CLEAN'].includes(record.status) ? ['INSPECTED', 'MAINTENANCE_REQUIRED'] : record.status === 'MAINTENANCE_REQUIRED' ? ['CLEANING'] : []) : ticketTransitions[record.status] || []; return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-[#0d1b2d] shadow-2xl"><div className="flex items-start justify-between border-b border-white/[0.08] px-6 py-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-300">Operational review</p><h2 className="mt-2 text-xl font-semibold text-white">{isTask ? `Room ${record.room?.number || '—'} task` : record.title}</h2><p className="mt-1 text-sm text-slate-500">{isTask ? record.room?.roomType?.name || 'Guest room' : `Room ${record.roomNumber || record.location || '—'}`}</p></div><button onClick={onClose} className="text-slate-500 hover:text-white"><X className="h-5 w-5" /></button></div><div className="space-y-5 px-6 py-6"><div className="flex items-center justify-between rounded-xl border border-white/[0.07] bg-white/[0.03] p-4"><span className="text-sm text-slate-500">Current status</span><Pill tone={toneForStatus(record.status)}>{taskLabel[record.status] || record.status}</Pill></div><p className="text-sm leading-6 text-slate-400">{record.notes || record.description || 'No additional operational notes have been recorded.'}</p><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-600">Available actions</p><div className="grid gap-2 sm:grid-cols-2">{nextStatuses.map((status) => <button key={status} disabled={saving} onClick={() => isTask ? onTaskStatus(status) : onTicketStatus(status)} className="rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-4 py-3 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-300/20 disabled:opacity-50">{saving ? 'Saving…' : status.replaceAll('_', ' ')}</button>)}{!nextStatuses.length && <p className="text-sm text-slate-600">No further actions are available for this record.</p>}</div></div></div></div></div>; }
