import type { Metadata } from "next";
import Link from "next/link";
import { PublicShell } from "@/components/public-shell";

const copy: Record<string, { title: string; description: string; capabilities: string[] }> = {
  pms: { title: "The operating core for your property.", description: "A complete property management workspace for reservations, front desk, guests, rooms and the daily rhythm of your hotel.", capabilities: ["Reservations and room rack", "Guest profiles and folios", "Front desk workflows", "Night audit and reporting"] },
  "front-desk": { title: "A clearer front desk, from arrival to departure.", description: "Give your team one calm, connected workspace for arrivals, room status, payments and guest service.", capabilities: ["Live arrivals and departures", "Room assignment", "Folio and payment control", "Offline-ready workflows"] },
  pos: { title: "Every outlet, connected to the stay.", description: "Connect restaurants, bars, kitchens and room charges without duplicating work across systems.", capabilities: ["Menus and open checks", "Kitchen workflows", "Room-charge posting", "Outlet reporting"] },
  housekeeping: { title: "Make room readiness visible.", description: "Coordinate housekeeping, inspections and maintenance with a live view of what the property needs next.", capabilities: ["Room status", "Task assignment", "Inspections", "Maintenance handoffs"] },
  accounting: { title: "Know where every naira goes.", description: "Bring operational transactions, cash control, reconciliation and financial reporting into one picture.", capabilities: ["Folios and city ledger", "Cash management", "Reconciliation", "Night audit"] },
};
const fallback = { title: "Hotel operations, connected.", description: "Purpose-built workflows that bring your property, people and performance together.", capabilities: ["Designed for hotel teams", "Connected operational data", "Implementation support", "Control-plane ready"] };
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const page = copy[(await params).slug] || fallback; return { title: page.title, description: page.description }; }
export default async function PlatformPage({ params }: { params: Promise<{ slug: string }> }) { const page = copy[(await params).slug] || fallback; return <PublicShell eyebrow="LodgeCore platform" title={page.title} description={page.description}><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{page.capabilities.map((item, i) => <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm" key={item}><span className="text-xs font-bold text-[#1677c8]">0{i + 1}</span><h2 className="mt-8 font-bold">{item}</h2><p className="mt-3 text-sm leading-6 text-slate-500">A connected workflow designed around the way hotel teams operate.</p></div>)}</div><div className="mt-10 rounded-3xl bg-[#07111f] p-8 text-white md:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-300">See it in context</p><h2 className="mt-4 max-w-2xl text-3xl font-black">One operating picture for the whole property.</h2><p className="mt-4 max-w-xl leading-7 text-slate-400">LodgeCore connects this capability to reservations, guests, payments, finance and the teams delivering the stay.</p><Link href="/book-demo" className="mt-7 inline-flex rounded-full bg-sky-300 px-5 py-3 text-sm font-bold text-[#07111f]">Book a demo →</Link></div></PublicShell>; }
