'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, Building2, CalendarDays, CheckCircle2, CircleDollarSign, FileSearch, FileText, RefreshCw, ShieldCheck, TrendingUp } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Scope = { propertyId: string; propertyName: string; currency: string; auditPeriodStart: string; auditPeriodEnd: string };
type Dashboard = { scope: Scope; kpis: { totalRevenue: number; cashCollected: number; averageOccupancy: number; adr: number; reconciliationStatus: string; closeFinalizedAt: string | null }; exceptions: Array<{ key: string; label: string; count: number; risk: string }>; trend: Array<{ date: string; revenue: number; occupancy: number; adr: number; revpar: number; status: string; exceptions: number }>; revenueMix: Array<{ category: string; amount: number }>; review: { evidenceRecords: number; journalEntries: number; auditEvents: number } };
const COLORS = ['#34d399', '#38bdf8', '#a78bfa', '#fbbf24'];
const compact = new Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 1 });
const money = (value: number, currency: string) => new Intl.NumberFormat('en', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);
const date = (value: string) => new Date(value).toLocaleDateString('en', { month: 'short', day: 'numeric' });
const streamLabel = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function ExternalAuditorDashboard() {
  const [scopes, setScopes] = useState<Scope[]>([]); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = (propertyId: string) => { setLoading(true); void fetch(`/api/v1/external-auditor/dashboard?propertyId=${propertyId}`).then(async r => { const value = await r.json(); if (!r.ok) throw new Error(value.error || 'Unable to load engagement'); return value; }).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(async r => { const value = await r.json(); if (!r.ok || !value.scopes?.length) throw new Error(value.error || 'No active engagement'); setScopes(value.scopes); load(value.scopes[0].propertyId); }).catch(e => setError(e.message)); }, []);
  const exceptionTotal = useMemo(() => data?.exceptions.reduce((sum, item) => sum + item.count, 0) || 0, [data]);
  if (error) return <div className="rounded-2xl border border-red-400/20 bg-red-400/[.08] p-6 text-red-200"><p className="font-semibold">Unable to load audit workspace</p><p className="mt-1 text-sm text-red-200/70">{error}</p></div>;
  if (!data) return <div className="flex min-h-[50vh] items-center justify-center text-sm text-slate-400"><RefreshCw className="mr-2 h-4 w-4 animate-spin" /> Loading verified audit data…</div>;
  const { kpis, scope } = data;
  const status = kpis.reconciliationStatus.replaceAll('_', ' ');
  const closeLabel = kpis.reconciliationStatus === 'COMPLETED' ? 'Completed' : status;
  return <div className="space-y-6 pb-8">
    <section className="relative overflow-hidden rounded-3xl border border-white/[.08] bg-gradient-to-br from-[#132a2d] via-[#101d2d] to-[#0d1524] p-6 shadow-2xl shadow-black/10 sm:p-7">
      <div className="pointer-events-none absolute -right-20 -top-28 h-72 w-72 rounded-full bg-emerald-400/10 blur-3xl" />
      <div className="relative flex flex-wrap items-start justify-between gap-6"><div><div className="mb-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><ShieldCheck className="h-4 w-4" /> Independent assurance workspace</div><h1 className="max-w-2xl text-3xl font-semibold tracking-tight text-white sm:text-4xl">Audit command center</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">A live view of financial integrity, close controls, and review priorities for the authorized engagement.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.05] px-3 py-2 text-xs text-slate-300"><CalendarDays className="h-4 w-4 text-emerald-300" />{new Date(scope.auditPeriodStart).toLocaleDateString()} — {new Date(scope.auditPeriodEnd).toLocaleDateString()}</div></div>
      <div className="relative mt-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs text-slate-500">Engagement property</p><p className="mt-1 flex items-center gap-2 text-lg font-medium text-white"><Building2 className="h-4 w-4 text-emerald-300" />{scope.propertyName}</p></div><div className="flex flex-wrap gap-2">{scopes.length > 1 && <select value={scope.propertyId} onChange={e => load(e.target.value)} className="rounded-xl border border-white/10 bg-slate-950/50 px-3 py-2 text-sm text-slate-200 outline-none"><option value="">Select property</option>{scopes.map(item => <option key={item.propertyId} value={item.propertyId}>{item.propertyName}</option>)}</select>}<Link href={`/external-auditor/evidence?propertyId=${scope.propertyId}`} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-3 py-2 text-sm font-medium text-slate-200 transition hover:bg-white/[.1]"><FileSearch className="h-4 w-4 text-sky-300" /> Evidence</Link><Link href={`/external-auditor/reports?propertyId=${scope.propertyId}`} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-3 py-2 text-sm font-semibold text-slate-950 transition hover:bg-emerald-200"><FileText className="h-4 w-4" /> Reports</Link></div></div>
    </section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[{ label: 'Audited revenue', value: money(kpis.totalRevenue, scope.currency), icon: CircleDollarSign, tone: 'text-emerald-300' }, { label: 'Average occupancy', value: `${kpis.averageOccupancy.toFixed(1)}%`, icon: Building2, tone: 'text-sky-300' }, { label: 'Cash collected', value: money(kpis.cashCollected, scope.currency), icon: TrendingUp, tone: 'text-violet-300' }, { label: 'Close status', value: closeLabel, icon: kpis.reconciliationStatus === 'COMPLETED' ? CheckCircle2 : AlertTriangle, tone: kpis.reconciliationStatus === 'COMPLETED' ? 'text-emerald-300' : 'text-amber-300' }].map(item => <div key={item.label} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><div className="flex items-center justify-between text-xs text-slate-500"><span>{item.label}</span><item.icon className={`h-4 w-4 ${item.tone}`} /></div><p className={`mt-3 font-semibold capitalize tracking-tight text-white ${item.label === 'Close status' ? 'text-xl' : 'truncate text-2xl'}`}>{item.value}</p></div>)}
    </div>
    <div className="grid gap-6 xl:grid-cols-[1.55fr_1fr]">
      <section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5 sm:p-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Operating signal</p><h2 className="mt-1 text-lg font-semibold text-white">Revenue and occupancy trend</h2></div><BarChart3 className="h-5 w-5 text-slate-500" /></div><div className="mb-3 flex items-center gap-4 text-[11px] text-slate-500"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-emerald-400" />Revenue</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-sky-400" />Occupancy</span></div><div className="h-64">{data.trend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend}><defs><linearGradient id="revenueFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#34d399" stopOpacity={0.35} /><stop offset="100%" stopColor="#34d399" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#ffffff10" vertical={false} /><XAxis dataKey="date" tickFormatter={date} tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis yAxisId="revenue" tickFormatter={value => compact.format(value)} tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} width={42} /><YAxis yAxisId="occupancy" orientation="right" domain={[0, 100]} tickFormatter={value => `${value}%`} tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} width={38} /><Tooltip contentStyle={{ background: '#111c2d', border: '1px solid #ffffff18', borderRadius: 12, color: '#e2e8f0' }} labelFormatter={value => new Date(String(value)).toLocaleDateString()} formatter={(value, name) => [name === 'revenue' ? money(Number(value), scope.currency) : `${Number(value).toFixed(1)}%`, name === 'revenue' ? 'Revenue' : 'Occupancy']} /><Area yAxisId="revenue" type="monotone" dataKey="revenue" stroke="#34d399" fill="url(#revenueFill)" strokeWidth={2} /><Line yAxisId="occupancy" type="monotone" dataKey="occupancy" stroke="#38bdf8" strokeWidth={2} dot={false} /></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-slate-500">No finalized night-audit observations in this period.</div>}</div></section>
      <section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Revenue composition</p><h2 className="mt-1 text-lg font-semibold text-white">Revenue by operating stream</h2><p className="mt-1 text-xs text-slate-500">Uses revenue class, then the source recorded on each folio charge.</p></div><CircleDollarSign className="h-5 w-5 text-slate-500" /></div><div className="h-48">{data.revenueMix.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.revenueMix} dataKey="amount" nameKey="category" innerRadius={55} outerRadius={78} paddingAngle={3}>{data.revenueMix.map((item, index) => <Cell key={item.category} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip formatter={value => money(Number(value), scope.currency)} contentStyle={{ background: '#111c2d', border: '1px solid #ffffff18', borderRadius: 12 }} /></PieChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-slate-500">No charge mix in the authorized period.</div>}</div><div className="space-y-3">{data.revenueMix.map((item, index) => { const total = data.revenueMix.reduce((sum, stream) => sum + stream.amount, 0); const share = total ? (item.amount / total) * 100 : 0; return <div key={item.category}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-slate-300"><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: COLORS[index % COLORS.length] }} />{streamLabel(item.category)}</span><span className="shrink-0 text-slate-200">{money(item.amount, scope.currency)} <span className="ml-1 text-slate-500">{share.toFixed(1)}%</span></span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full" style={{ width: `${share}%`, backgroundColor: COLORS[index % COLORS.length] }} /></div></div>; })}</div></section>
    </div>
    <section className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Control review queue</p><h2 className="mt-1 text-lg font-semibold text-white">Exceptions requiring attention</h2><p className="mt-1 text-sm text-slate-500">{exceptionTotal ? `${exceptionTotal} records are flagged across the authorized period.` : 'No exceptions are currently flagged.'}</p></div><Link href={`/external-auditor/evidence?propertyId=${scope.propertyId}`} className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-300 hover:text-emerald-200">Open evidence explorer <ArrowUpRight className="h-4 w-4" /></Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.exceptions.map(item => <Link key={item.key} href={`/external-auditor/evidence?propertyId=${scope.propertyId}&q=${encodeURIComponent(item.label)}`} className={`group rounded-xl border border-white/[.07] border-l-2 bg-slate-950/25 p-4 transition hover:bg-white/[.05] ${item.risk === 'HIGH' ? 'border-l-red-400 hover:border-red-300/40' : item.risk === 'MEDIUM' ? 'border-l-amber-300 hover:border-amber-300/40' : 'border-l-slate-500 hover:border-emerald-300/30'}`}><div className="flex items-center justify-between"><span className="text-sm text-slate-300">{item.label}</span><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.count ? (item.risk === 'HIGH' ? 'bg-red-300/10 text-red-300' : 'bg-amber-300/10 text-amber-300') : 'bg-emerald-300/10 text-emerald-300'}`}>{item.count}</span></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span className={item.risk === 'HIGH' ? 'font-semibold text-red-300' : item.risk === 'MEDIUM' ? 'font-semibold text-amber-300' : ''}>{item.risk} review priority</span><ArrowUpRight className="h-3.5 w-3.5 opacity-0 transition group-hover:opacity-100" /></div></Link>)}</div></section>
    <div className="grid gap-3 md:grid-cols-3"><Link href={`/external-auditor/evidence?propertyId=${scope.propertyId}`} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4 hover:bg-white/[.06]"><div className="flex items-center gap-3"><FileSearch className="h-5 w-5 text-sky-300" /><div><p className="text-xs text-slate-500">Evidence records</p><p className="mt-1 text-lg font-semibold text-white">{data.review.evidenceRecords.toLocaleString()}</p></div></div></Link><Link href={`/external-auditor/reports?propertyId=${scope.propertyId}`} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4 hover:bg-white/[.06]"><div className="flex items-center gap-3"><BarChart3 className="h-5 w-5 text-violet-300" /><div><p className="text-xs text-slate-500">Journal entries</p><p className="mt-1 text-lg font-semibold text-white">{data.review.journalEntries.toLocaleString()}</p></div></div></Link><div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-300" /><div><p className="text-xs text-slate-500">Audit events</p><p className="mt-1 text-lg font-semibold text-white">{data.review.auditEvents.toLocaleString()}</p></div></div></div></div>
    {loading && <p className="flex items-center justify-end gap-2 text-xs text-slate-500"><RefreshCw className="h-3 w-3 animate-spin" /> Refreshing engagement data…</p>}
  </div>;
}
