'use client';

import { useCallback, useEffect, useState } from 'react';
import { Check, CheckCircle2, Clock3, FileText, Loader2, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

type Line = { description: string; unit?: string | null; quantity: number | string; unitPrice: number | string; total: number | string };
type Expense = { id: string; expenseReference: string; status: string; currentApprovalStage?: string | null; amount: number | string; currency: string; category: string; description: string; payee: string; lineItems?: Line[] };
const money = (value: number | string, currency: string) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value));

export function GeneralManagerExpenseApprovalQueue({ stage = 'GENERAL_MANAGER', title = 'Expense invoices awaiting your approval' }: { stage?: 'GENERAL_CASHIER' | 'ACCOUNTANT' | 'GENERAL_MANAGER'; title?: string }) {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [selected, setSelected] = useState<Expense | null>(null);
  const [message, setMessage] = useState('');
  const load = useCallback(async () => {
    setLoading(true);
    try { const response = await fetch('/api/v1/financial-control/expenses', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load expense approvals'); setExpenses((body.data || []).filter((expense: Expense) => expense.currentApprovalStage === stage)); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load expense approvals'); } finally { setLoading(false); }
  }, [stage]);
  useEffect(() => { void load(); }, [load]);
  const decide = async (expense: Expense, action: 'approve' | 'reject') => {
    const reason = action === 'reject' ? window.prompt('Reason for rejecting this invoice:')?.trim() : undefined;
    if (action === 'reject' && !reason) return;
    setBusy(expense.id); setMessage('');
    try { const response = await fetch(`/api/v1/financial-control/expenses/${expense.id}/action`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...(reason ? { reason } : {}) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to update expense'); setSelected(null); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update expense'); } finally { setBusy(null); }
  };
  const stageDescription = stage === 'GENERAL_CASHIER' ? 'New requests awaiting initial cashier review.' : stage === 'ACCOUNTANT' ? 'Requests already cleared by the General Cashier.' : 'Requests that have passed General Cashier and Accountant review.';
  return <section className="mt-8 space-y-4"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{stageDescription}</p></div><Badge variant="secondary" className="px-3 py-1">{expenses.length} pending</Badge></div>{message && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</p>}{loading ? <div className="flex items-center justify-center rounded-2xl border bg-card p-10 text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading expense invoices…</div> : expenses.length === 0 ? <div className="rounded-2xl border bg-card p-10 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 h-8 w-8 text-emerald-500" />No expense invoices are awaiting this approval stage.</div> : <div className="grid gap-4 lg:grid-cols-2">{expenses.map(expense => <article key={expense.id} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-cyan-700">{expense.expenseReference}</p><h3 className="mt-1 font-semibold">{expense.payee}</h3><p className="mt-1 text-sm text-muted-foreground">{expense.category} · {expense.description}</p></div><p className="font-bold">{money(expense.amount, expense.currency || 'NGN')}</p></div><div className="mt-4 flex items-center gap-2 text-xs text-emerald-700">{stage !== 'GENERAL_CASHIER' && <><Check className="h-3.5 w-3.5" />Cashier approved</>}{stage === 'GENERAL_MANAGER' && <><Check className="ml-2 h-3.5 w-3.5" />Accountant approved</>}<Clock3 className="ml-2 h-3.5 w-3.5 text-amber-600" />Your decision</div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => setSelected(expense)}><FileText className="mr-1.5 h-3.5 w-3.5" />View invoice</Button><Button variant="outline" size="sm" disabled={busy === expense.id} onClick={() => void decide(expense, 'reject')}><X className="mr-1.5 h-3.5 w-3.5 text-rose-600" />Reject</Button><Button size="sm" disabled={busy === expense.id} onClick={() => void decide(expense, 'approve')}>{busy === expense.id ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Check className="mr-1.5 h-3.5 w-3.5" />}Approve</Button></div></article>)}</div>}
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>Expense invoice {selected?.expenseReference}</DialogTitle><DialogDescription>Review the complete line-item requisition before approving.</DialogDescription></DialogHeader>{selected && <div className="space-y-4"><div className="grid grid-cols-3 gap-3 rounded-xl bg-muted/50 p-4 text-sm"><div><p className="text-xs text-muted-foreground">Payee</p><p className="mt-1 font-semibold">{selected.payee}</p></div><div><p className="text-xs text-muted-foreground">Category</p><p className="mt-1">{selected.category}</p></div><div><p className="text-xs text-muted-foreground">Total</p><p className="mt-1 font-bold">{money(selected.amount, selected.currency || 'NGN')}</p></div></div><p className="text-sm">{selected.description}</p><div className="overflow-hidden rounded-xl border"><div className="grid grid-cols-[1fr_70px_110px_110px] gap-2 bg-muted/50 px-4 py-2 text-xs font-semibold"><span>Item / service</span><span>Qty</span><span>Unit price</span><span className="text-right">Total</span></div>{(selected.lineItems || []).map((line, index) => <div key={`${line.description}-${index}`} className="grid grid-cols-[1fr_70px_110px_110px] gap-2 border-t px-4 py-3 text-sm"><span>{line.description}{line.unit ? ` · ${line.unit}` : ''}</span><span>{line.quantity}</span><span>{money(line.unitPrice, selected.currency || 'NGN')}</span><span className="text-right font-semibold">{money(line.total, selected.currency || 'NGN')}</span></div>)}<div className="flex justify-between border-t bg-muted/50 px-4 py-3 font-bold"><span>Invoice total</span><span>{money(selected.amount, selected.currency || 'NGN')}</span></div></div></div>}<DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>Close</Button><Button variant="destructive" disabled={!selected || busy === selected.id} onClick={() => selected && void decide(selected, 'reject')}>Reject</Button><Button disabled={!selected || busy === selected.id} onClick={() => selected && void decide(selected, 'approve')}>Approve invoice</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}
