'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { CheckCircle2, Loader2 } from 'lucide-react';

export function CreateHandoverButton({ propertyId, posSessionIds, frontdeskSessionIds }: { propertyId: string; posSessionIds: string[]; frontdeskSessionIds: string[] }) {
  const [open, setOpen] = useState(false); const [safeReference, setSafeReference] = useState(''); const [notes, setNotes] = useState(''); const [state, setState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [error, setError] = useState(''); const router = useRouter();
  const create = async () => { setState('loading'); try { const res = await fetch('/api/v1/financial-control/handovers', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ propertyId, posSessionIds, frontdeskSessionIds, safeReference: safeReference.trim() || undefined, notes: notes.trim() || undefined }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error || 'Unable to create handover'); setState('success'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create handover'); setState('error'); } };
  return <><Button size="sm" onClick={() => setOpen(true)}>Create handover</Button><Dialog open={open} onOpenChange={v => v && state !== 'loading' ? setOpen(v) : undefined}><DialogContent>{state === 'idle' || state === 'loading' ? <><DialogHeader><DialogTitle>Create cash handover</DialogTitle><DialogDescription>This places the selected approved shifts into custody transfer. The receiving cashier must confirm receipt.</DialogDescription></DialogHeader><Input value={safeReference} onChange={e => setSafeReference(e.target.value)} placeholder="Safe reference (optional)" /><Input value={notes} onChange={e => setNotes(e.target.value)} placeholder="Notes (optional)" /><DialogFooter><Button variant="outline" onClick={() => setOpen(false)} disabled={state === 'loading'}>Cancel</Button><Button onClick={create} disabled={state === 'loading'}>{state === 'loading' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Confirm handover</Button></DialogFooter></> : state === 'success' ? <><DialogHeader><DialogTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" />Handover created</DialogTitle><DialogDescription>The selected shifts are now waiting for cash receipt confirmation.</DialogDescription></DialogHeader><DialogFooter><Button onClick={() => { setOpen(false); router.refresh(); }}>Continue</Button></DialogFooter></> : <><DialogHeader><DialogTitle>Unable to create handover</DialogTitle><DialogDescription>{error}</DialogDescription></DialogHeader><DialogFooter><Button onClick={() => setState('idle')}>Back</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
