import Link from 'next/link';
import { redirect } from 'next/navigation';
import { AlertCircle, ArrowRight, BarChart3, CalendarClock, CheckCircle2, CreditCard, FileCheck2, Landmark, Receipt, ShieldCheck, Wallet } from 'lucide-react';
import { auth } from '@/lib/auth';
import { prisma } from '@hotel-pms/db';
import { RecordSupplierBillModal } from '@/components/accountant/RecordSupplierBillModal';
import { PayablesRegister, type PayablesRow } from '@/components/accountant/PayablesRegister';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const money = (amount: number, currency: string) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount);
const date = (value: Date) => new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(value);
const daysBetween = (from: Date, to: Date) => Math.floor((to.getTime() - from.getTime()) / 86400000);

export default async function PayablesPage() {
  const session = await auth();
  if (!session?.user) redirect('/login?callbackUrl=%2Faccountant%2Fpayables');
  const propertyId = session.user.propertyId;
  if (!propertyId) return <EmptyState title="No property assigned" />;

  const [property, invoices, suppliers] = await Promise.all([
    prisma.property.findUnique({ where: { id: propertyId }, select: { name: true, baseCurrency: true, businessDate: true } }),
    prisma.supplierInvoice.findMany({ where: { propertyId }, include: { supplier: { select: { id: true, name: true } }, payments: { select: { amount: true, paymentDate: true } } }, orderBy: [{ dueDate: 'asc' }, { createdAt: 'desc' }] }),
    prisma.supplier.findMany({ where: { propertyId, isActive: true }, select: { id: true, name: true }, orderBy: { name: 'asc' } }),
  ]);

  const currency = property?.baseCurrency || invoices[0]?.currency || 'NGN';
  const asOf = property?.businessDate || new Date();
  const open = invoices.filter(invoice => !['PAID', 'CANCELLED'].includes(invoice.status) && Number(invoice.outstandingAmount) > 0.009);
  const totalOutstanding = open.reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0);
  const overdue = open.filter(invoice => invoice.dueDate < asOf);
  const overdueAmount = overdue.reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0);
  const dueNextSeven = open.filter(invoice => invoice.dueDate >= asOf && daysBetween(asOf, invoice.dueDate) <= 7).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0);
  const pendingReview = invoices.filter(invoice => ['RECEIVED', 'UNDER_REVIEW'].includes(invoice.status));
  const readyToPay = invoices.filter(invoice => ['APPROVED', 'PARTIAL'].includes(invoice.status) && Number(invoice.outstandingAmount) > 0.009);
  const settledThisMonth = invoices.flatMap(invoice => invoice.payments).filter(payment => { const d = new Date(payment.paymentDate); return d.getUTCFullYear() === asOf.getUTCFullYear() && d.getUTCMonth() === asOf.getUTCMonth(); }).reduce((sum, payment) => sum + Number(payment.amount), 0);
  const aging = [
    { label: 'Current', detail: 'Not yet due', amount: open.filter(invoice => invoice.dueDate >= asOf).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), color: 'bg-emerald-400' },
    { label: '1–30 days', detail: 'Recently overdue', amount: open.filter(invoice => { const d = daysBetween(invoice.dueDate, asOf); return d > 0 && d <= 30; }).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), color: 'bg-amber-400' },
    { label: '31–60 days', detail: 'Needs owner follow-up', amount: open.filter(invoice => { const d = daysBetween(invoice.dueDate, asOf); return d > 30 && d <= 60; }).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), color: 'bg-orange-400' },
    { label: '61–90 days', detail: 'Escalation queue', amount: open.filter(invoice => { const d = daysBetween(invoice.dueDate, asOf); return d > 60 && d <= 90; }).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), color: 'bg-rose-400' },
    { label: '90+ days', detail: 'Executive attention', amount: open.filter(invoice => daysBetween(invoice.dueDate, asOf) > 90).reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), color: 'bg-fuchsia-400' },
  ];
  const maxAging = Math.max(...aging.map(item => item.amount), 1);
  const supplierExposure = Array.from(open.reduce((map, invoice) => map.set(invoice.supplier.name, (map.get(invoice.supplier.name) || 0) + Number(invoice.outstandingAmount)), new Map<string, number>()).entries()).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const rows: PayablesRow[] = invoices.map(invoice => ({ id: invoice.id, invoiceNumber: invoice.invoiceNumber, supplierName: invoice.supplier.name, supplierId: invoice.supplier.id, invoiceDate: invoice.invoiceDate.toISOString(), dueDate: invoice.dueDate.toISOString(), totalAmount: Number(invoice.totalAmount), outstandingAmount: Number(invoice.outstandingAmount), currency: invoice.currency || currency, status: invoice.status, daysPastDue: Math.max(0, daysBetween(invoice.dueDate, asOf)), hasGrn: false }));

  return <main className="min-h-full bg-[#09111f] px-4 py-6 text-slate-200 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-emerald-300"><Landmark className="h-4 w-4" />Accounts payable control room</div><h1 className="text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">Supplier liabilities, in control.</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Live invoice exposure, due-date pressure, approval queue, and payment readiness for {property?.name || 'this property'}.</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-400">Business date <strong className="ml-1 text-slate-200">{date(asOf)}</strong></span><RecordSupplierBillModal propertyId={propertyId} suppliers={suppliers} /></div></header>
    <section className="flex flex-col justify-between gap-4 rounded-2xl border border-emerald-400/15 bg-emerald-400/[.055] px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-400/15 text-emerald-300"><ShieldCheck className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-white">AP close posture</p><p className="mt-1 text-xs text-slate-400">{pendingReview.length ? `${pendingReview.length} invoice${pendingReview.length === 1 ? '' : 's'} still need review before payment.` : 'No invoice is waiting in the initial review queue.'}</p></div></div><Link href="/accountant/gl" className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-300 hover:text-emerald-200">Inspect GL control <ArrowRight className="h-3.5 w-3.5" /></Link></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Open AP" value={money(totalOutstanding, currency)} detail={`${open.length} unpaid invoices`} icon={CreditCard} tone="amber" /><Metric label="Overdue" value={money(overdueAmount, currency)} detail={`${overdue.length} past due`} icon={AlertCircle} tone="rose" /><Metric label="Due in 7 days" value={money(dueNextSeven, currency)} detail="Near-term cash requirement" icon={CalendarClock} tone="blue" /><Metric label="Ready to pay" value={money(readyToPay.reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0), currency)} detail={`${readyToPay.length} approved invoices`} icon={FileCheck2} tone="emerald" /><Metric label="Paid this month" value={money(settledThisMonth, currency)} detail="Supplier payments posted" icon={Wallet} tone="violet" /></section>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Payables ageing" subtitle="Live outstanding balance grouped by contractual due date"><div className="space-y-4">{aging.map(item => <div key={item.label}><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span><span className="text-slate-200">{item.label}</span><span className="ml-2 text-xs text-slate-600">{item.detail}</span></span><strong className="text-white">{money(item.amount, currency)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${item.color}`} style={{ width: `${item.amount / maxAging * 100}%` }} /></div></div>)}</div></Panel><Panel title="Supplier concentration" subtitle="Largest open liabilities by supplier"><div className="space-y-4">{supplierExposure.length ? supplierExposure.map(([name, amount], index) => <div key={name}><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white/[.06] text-[10px] text-slate-500">{index + 1}</span><span className="truncate text-slate-300">{name}</span></span><strong className="shrink-0 text-white">{money(amount, currency)}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${amount / Math.max(supplierExposure[0]?.[1] || 1, 1) * 100}%` }} /></div></div>) : <EmptyInline text="No open supplier exposure." />}</div><div className="mt-5 border-t border-white/[.07] pt-4 text-xs text-slate-500">Payment execution should follow approved invoice status, open-period controls, and bank reconciliation.</div></Panel></section>
    <section className="grid gap-4 sm:grid-cols-3"><Signal icon={Receipt} title="Review queue" value={`${pendingReview.length} invoice${pendingReview.length === 1 ? '' : 's'}`} detail="Received or under review" href="#invoice-register" tone="amber" /><Signal icon={CheckCircle2} title="Approval queue" value={`${readyToPay.length} ready`} detail="Approved or partially paid" href="#invoice-register" tone="emerald" /><Signal icon={BarChart3} title="Control insight" value={overdueAmount ? `${Math.round(overdueAmount / Math.max(totalOutstanding, 1) * 100)}% overdue` : '0% overdue'} detail="Share of open AP exposure" href="#invoice-register" tone={overdueAmount ? 'rose' : 'blue'} /></section>
    <PayablesRegister rows={rows} currency={currency} />
  </div></main>;
}

function Metric({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: React.ElementType; tone: 'emerald' | 'blue' | 'amber' | 'rose' | 'violet' }) { const colors = { emerald: 'text-emerald-300 bg-emerald-400/10 ring-emerald-400/15', blue: 'text-blue-300 bg-blue-400/10 ring-blue-400/15', amber: 'text-amber-300 bg-amber-400/10 ring-amber-400/15', rose: 'text-rose-300 bg-rose-400/10 ring-rose-400/15', violet: 'text-violet-300 bg-violet-400/10 ring-violet-400/15' }; return <div className="rounded-2xl border border-white/[.08] bg-[#111a2b]/75 p-5"><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-slate-500">{label}</p><span className={`flex h-9 w-9 items-center justify-center rounded-xl ring-1 ${colors[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-2xl font-semibold tracking-[-.03em] text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/[.08] bg-[#111a2b]/75 p-5 shadow-[0_18px_50px_rgba(0,0,0,.1)]"><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></section>; }
function Signal({ icon: Icon, title, value, detail, href, tone }: { icon: React.ElementType; title: string; value: string; detail: string; href: string; tone: 'emerald' | 'blue' | 'amber' | 'rose' }) { const colors = { emerald: 'text-emerald-300', blue: 'text-blue-300', amber: 'text-amber-300', rose: 'text-rose-300' }; return <Link href={href} className="flex items-center gap-4 rounded-2xl border border-white/[.08] bg-white/[.025] p-4 transition hover:border-white/20 hover:bg-white/[.05]"><Icon className={`h-5 w-5 ${colors[tone]}`} /><span><span className="block text-xs text-slate-500">{title}</span><strong className="mt-1 block text-sm text-white">{value}</strong><span className="mt-1 block text-xs text-slate-600">{detail}</span></span><ArrowRight className="ml-auto h-4 w-4 text-slate-600" /></Link>; }
function EmptyInline({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/10 py-8 text-center text-xs text-slate-600">{text}</div>; }
function EmptyState({ title }: { title: string }) { return <main className="flex min-h-full items-center justify-center bg-[#09111f] text-slate-300"><div className="text-center"><Landmark className="mx-auto mb-3 h-10 w-10 text-slate-600" /><h1 className="text-xl font-semibold text-white">{title}</h1></div></main>; }
