'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ClipboardCheck, FilePlus2, Flag, Loader2, Plus, ShieldAlert, UploadCloud } from 'lucide-react';

type Engagement = { id: string; name: string; propertyId: string; status: string; auditType: string; auditPeriodStart: string; auditPeriodEnd: string; materiality?: number | null };
type Request = { id: string; title: string; description: string; category: string; status: string; priority: string; dueDate?: string | null };
type Workpaper = { id: string; reference: string; title: string; controlArea: string; status: string; result?: string | null };
type Finding = { id: string; reference: string; title: string; severity: string; status: string; description: string; dueDate?: string | null };

const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());
const pill = (value: string) => value === 'CRITICAL' || value === 'HIGH' ? 'bg-red-300/10 text-red-300' : value === 'MEDIUM' || value === 'IN_PROGRESS' ? 'bg-amber-300/10 text-amber-300' : 'bg-emerald-300/10 text-emerald-300';

export default function AuditOperationsPage() {
  const [propertyId, setPropertyId] = useState(''); const [engagements, setEngagements] = useState<Engagement[]>([]); const [requests, setRequests] = useState<Request[]>([]); const [workpapers, setWorkpapers] = useState<Workpaper[]>([]); const [findings, setFindings] = useState<Finding[]>([]); const [tab, setTab] = useState<'requests' | 'workpapers' | 'findings'>('requests'); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async (id: string, engagementId?: string) => { setLoading(true); const params = `propertyId=${id}${engagementId ? `&engagementId=${engagementId}` : ''}`; const [e, r, w, f] = await Promise.all([fetch(`/api/v1/external-auditor/management?resource=engagements&${params}`), fetch(`/api/v1/external-auditor/management?resource=requests&${params}`), fetch(`/api/v1/external-auditor/management?resource=workpapers&${params}`), fetch(`/api/v1/external-auditor/management?resource=findings&${params}`)]); const values = await Promise.all([e.json(), r.json(), w.json(), f.json()]); setEngagements(values[0].items || []); setRequests(values[1].items || []); setWorkpapers(values[2].items || []); setFindings(values[3].items || []); setLoading(false); };
  useEffect(() => { void fetch('/api/v1/external-auditor/context').then(r => r.json()).then(v => { const scope = v.scopes?.[0]; if (!scope) throw new Error(v.error || 'No active engagement'); setPropertyId(scope.propertyId); return load(scope.propertyId); }).catch(e => { setError(e.message); setLoading(false); }); }, []);
  const engagement = engagements[0];
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!engagement) return; setSaving(true); const form = new FormData(event.currentTarget); const resource = tab === 'requests' ? 'request' : tab === 'workpapers' ? 'workpaper' : 'finding'; const body: Record<string, string> = { resource, propertyId, organizationId: '', engagementId: engagement.id }; form.forEach((value, key) => { body[key] = String(value); }); const response = await fetch('/api/v1/external-auditor/management', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) setError(value.error || 'Unable to create record'); else { setShowForm(false); event.currentTarget.reset(); await load(propertyId, engagement.id); } setSaving(false); };
  const update = async (resource: string, id: string, status: string) => { const response = await fetch('/api/v1/external-auditor/management', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resource, id, status }) }); if (!response.ok) { const value = await response.json(); setError(value.error || 'Unable to update record'); } else await load(propertyId, engagement?.id); };
  if (error && !propertyId) return <div className="rounded-2xl border border-red-400/20 bg-red-400/[.07] p-6 text-red-200">{error}</div>;
  return <div className="space-y-6 pb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300"><ClipboardCheck className="h-4 w-4" /> Engagement fieldwork</div><h1 className="text-3xl font-semibold tracking-tight text-white">Audit operations</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage evidence requests, workpapers, and findings with an auditable review trail.</p></div><button onClick={() => setShowForm(value => !value)} disabled={!engagement} className="inline-flex h-10 items-center gap-2 rounded-xl bg-emerald-300 px-4 text-sm font-semibold text-slate-950 disabled:opacity-50"><Plus className="h-4 w-4" /> New {tab === 'requests' ? 'request' : tab === 'workpapers' ? 'workpaper' : 'finding'}</button></div>
    {engagement && <div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.15em] text-slate-500">Active engagement</p><h2 className="mt-1 text-lg font-semibold text-white">{engagement.name}</h2><p className="mt-1 text-sm text-slate-500">{human(engagement.auditType)} · {new Date(engagement.auditPeriodStart).toLocaleDateString()} — {new Date(engagement.auditPeriodEnd).toLocaleDateString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${pill(engagement.status)}`}>{human(engagement.status)}</span></div></div>}
    {error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}
    {showForm && <form onSubmit={create} className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[.04] p-5"><div className="mb-4 flex items-center gap-2"><FilePlus2 className="h-4 w-4 text-emerald-300" /><h2 className="font-semibold text-white">Create {tab === 'requests' ? 'evidence request' : tab === 'workpapers' ? 'workpaper' : 'finding'}</h2></div><div className="grid gap-3 sm:grid-cols-2">{tab === 'requests' && <><input required name="title" placeholder="Request title" className="field" /><input name="category" placeholder="Category e.g. POS reconciliation" className="field" /><textarea required name="description" placeholder="Describe the evidence required" className="field min-h-24 sm:col-span-2" /><select name="priority" className="field"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select><input name="dueDate" type="date" className="field" /></>}{tab === 'workpapers' && <><input required name="reference" placeholder="Reference e.g. WP-001" className="field" /><input required name="title" placeholder="Workpaper title" className="field" /><input required name="controlArea" placeholder="Control area" className="field" /><input name="sampleSize" type="number" min="0" placeholder="Sample size" className="field" /><textarea name="objective" placeholder="Audit objective" className="field min-h-24 sm:col-span-2" /><textarea name="procedure" placeholder="Procedure performed" className="field min-h-24 sm:col-span-2" /></>}{tab === 'findings' && <><input required name="reference" placeholder="Reference e.g. FIND-001" className="field" /><input required name="title" placeholder="Finding title" className="field" /><select name="severity" className="field"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select><input name="dueDate" type="date" className="field" /><textarea required name="description" placeholder="Finding description" className="field min-h-24 sm:col-span-2" /><textarea name="recommendation" placeholder="Recommendation" className="field min-h-24 sm:col-span-2" /></>}</div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="rounded-lg border border-white/10 px-3 py-2 text-sm text-slate-300">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-emerald-300 px-3 py-2 text-sm font-semibold text-slate-950">{saving && <Loader2 className="h-4 w-4 animate-spin" />} Save record</button></div></form>}
    <div className="flex gap-1 rounded-xl border border-white/[.08] bg-white/[.035] p-1"><button onClick={() => { setTab('requests'); setShowForm(false); }} className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium ${tab === 'requests' ? 'bg-white/[.1] text-white' : 'text-slate-500'}`}>Evidence requests <span className="ml-1 text-xs">{requests.length}</span></button><button onClick={() => { setTab('workpapers'); setShowForm(false); }} className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium ${tab === 'workpapers' ? 'bg-white/[.1] text-white' : 'text-slate-500'}`}>Workpapers <span className="ml-1 text-xs">{workpapers.length}</span></button><button onClick={() => { setTab('findings'); setShowForm(false); }} className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium ${tab === 'findings' ? 'bg-white/[.1] text-white' : 'text-slate-500'}`}>Findings <span className="ml-1 text-xs">{findings.length}</span></button></div>
    <section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]">{loading ? <div className="flex h-48 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading fieldwork records…</div> : tab === 'requests' ? <div className="divide-y divide-white/[.06]">{requests.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="min-w-0"><div className="flex items-center gap-2"><UploadCloud className="h-4 w-4 text-sky-300" /><h3 className="truncate font-medium text-white">{item.title}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${pill(item.status)}`}>{human(item.status)}</span></div><p className="mt-1 text-sm text-slate-500">{item.category} · {item.description}</p></div><select value={item.status} onChange={event => void update('request', item.id, event.target.value)} className="field w-auto"><option>OPEN</option><option>IN_PROGRESS</option><option>SUBMITTED</option><option>RETURNED</option><option>ACCEPTED</option><option>CLOSED</option></select></div>)}{!requests.length && <Empty text="No evidence requests yet." />}</div> : tab === 'workpapers' ? <div className="divide-y divide-white/[.06]">{workpapers.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><FilePlus2 className="h-4 w-4 text-violet-300" /><span className="font-mono text-xs text-violet-300">{item.reference}</span><h3 className="font-medium text-white">{item.title}</h3></div><p className="mt-1 text-sm text-slate-500">{item.controlArea}{item.result ? ` · ${item.result}` : ''}</p></div><select value={item.status} onChange={event => void update('workpaper', item.id, event.target.value)} className="field w-auto"><option>DRAFT</option><option>IN_REVIEW</option><option>APPROVED</option><option>LOCKED</option></select></div>)}{!workpapers.length && <Empty text="No workpapers have been prepared." />}</div> : <div className="divide-y divide-white/[.06]">{findings.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><Flag className="h-4 w-4 text-amber-300" /><span className="font-mono text-xs text-amber-300">{item.reference}</span><h3 className="font-medium text-white">{item.title}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${pill(item.severity)}`}>{item.severity}</span></div><p className="mt-1 max-w-2xl text-sm text-slate-500">{item.description}</p></div><select value={item.status} onChange={event => void update('finding', item.id, event.target.value)} className="field w-auto"><option>OPEN</option><option>MANAGEMENT_RESPONSE</option><option>IN_REMEDIATION</option><option>PENDING_VALIDATION</option><option>CLOSED</option></select></div>)}{!findings.length && <Empty text="No findings have been recorded." />}</div>}</section>
  </div>;
}

function Empty({ text }: { text: string }) { return <div className="p-14 text-center"><ShieldAlert className="mx-auto h-7 w-7 text-slate-700" /><p className="mt-3 text-sm text-slate-500">{text}</p></div>; }
