'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { CheckCircle2, Loader2 } from 'lucide-react';

export function CreateDepositButton({ propertyId, posSessionIds, frontdeskSessionIds }: { propertyId: string; posSessionIds: string[]; frontdeskSessionIds: string[] }) {
  const [open, setOpen] = useState(false); const [bankName, setBankName] = useState(''); const [bankAccount, setBankAccount] = useState(''); const [state, setState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [error, setError] = useState(''); const router = useRouter();
  const create = async () => { setState('loading'); try { const res = await fetch('/api/v1/financial-control/deposits', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ propertyId, posSessionIds, frontdeskSessionIds, bankName: bankName.trim() || undefined, bankAccount: bankAccount.trim() || undefined }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error || 'Unable to create deposit'); setState('success'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create deposit'); setState('error'); } };
  return <><Button size="sm" onClick={() => setOpen(true)}>Create bank deposit</Button><Dialog open={open} onOpenChange={v => v && state !== 'loading' ? setOpen(v) : undefined}><DialogContent>{state === 'idle' || state === 'loading' ? <><DialogHeader><DialogTitle>Create bank deposit</DialogTitle><DialogDescription>Bundle the selected received handovers into one deposit record. The deposit can then be submitted to the bank.</DialogDescription></DialogHeader><Input value={bankName} onChange={e => setBankName(e.target.value)} placeholder="Bank name (optional)" /><Input value={bankAccount} onChange={e => setBankAccount(e.target.value)} placeholder="Bank account (optional)" /><DialogFooter><Button variant="outline" onClick={() => setOpen(false)} disabled={state === 'loading'}>Cancel</Button><Button onClick={create} disabled={state === 'loading'}>{state === 'loading' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Create deposit</Button></DialogFooter></> : state === 'success' ? <><DialogHeader><DialogTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" />Deposit created</DialogTitle><DialogDescription>The selected handovers are now grouped into a pending bank deposit.</DialogDescription></DialogHeader><DialogFooter><Button onClick={() => { setOpen(false); router.refresh(); }}>Continue</Button></DialogFooter></> : <><DialogHeader><DialogTitle>Unable to create deposit</DialogTitle><DialogDescription>{error}</DialogDescription></DialogHeader><DialogFooter><Button onClick={() => setState('idle')}>Back</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
