'use client';

import { useEffect, useState } from 'react';
import { CheckCircle2, FileCheck2, Loader2, PenLine } from 'lucide-react';

type Pack = { id: string; status: string; packageHash: string; createdAt: string; auditorSignedAt?: string | null; managementSignedAt?: string | null; manifest: { requests: number; workpapers: number; findings: number } };
const human = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, match => match.toUpperCase());

export default function ManagementFinalPackPage() {
  const [packs, setPacks] = useState<Pack[]>([]); const [loading, setLoading] = useState(true); const [signing, setSigning] = useState(''); const [error, setError] = useState('');
  const load = async () => { const response = await fetch('/api/v1/external-auditor/management?resource=final-packs'); const value = await response.json(); if (!response.ok) throw new Error(value.error || 'Unable to load final packs'); setPacks(value.items || []); setLoading(false); };
  // Hydrate the management register from the live final-pack API on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load().catch(e => { setError(e.message); setLoading(false); }); }, []);
  const sign = async (id: string) => { setSigning(id); setError(''); const response = await fetch('/api/v1/external-auditor/final-pack', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, signer: 'management' }) }); const value = await response.json(); if (!response.ok) setError(value.error || 'Unable to record management sign-off'); else await load(); setSigning(''); };
  if (loading) return <div className="flex min-h-[40vh] items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading final packs…</div>;
  return <div className="min-h-screen bg-slate-950 px-5 py-8 text-slate-200 sm:px-8"><div className="mx-auto max-w-6xl space-y-6"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300">Governance deliverables</p><h1 className="mt-3 text-3xl font-semibold text-white">Management sign-off</h1><p className="mt-2 text-sm text-slate-500">Review the immutable external-audit pack register and issue packs after auditor review.</p></div>{error && <div className="rounded-xl border border-red-400/20 bg-red-400/[.07] p-4 text-sm text-red-200">{error}</div>}<section className="overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.035]"><div className="divide-y divide-white/[.06]">{packs.map(pack => <div key={pack.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><span className="font-medium text-white">{human(pack.status)} pack</span></div><p className="mt-2 font-mono text-xs text-slate-500">SHA-256 {pack.packageHash}</p><p className="mt-1 text-xs text-slate-600">Generated {new Date(pack.createdAt).toLocaleString()} · {pack.manifest.requests} requests · {pack.manifest.workpapers} workpapers · {pack.manifest.findings} findings</p><p className="mt-2 text-xs text-slate-400">Auditor: {pack.auditorSignedAt ? 'signed' : 'pending'} · Management: {pack.managementSignedAt ? 'signed' : 'pending'}</p></div><div className="flex gap-2"><a href={`/external-auditor/reports`} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300"><FileCheck2 className="h-3.5 w-3.5" /> Reports</a>{!pack.managementSignedAt && pack.auditorSignedAt && <button onClick={() => void sign(pack.id)} disabled={signing === pack.id} className="inline-flex items-center gap-2 rounded-lg bg-emerald-300 px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-50">{signing === pack.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <PenLine className="h-3.5 w-3.5" />} Sign and issue</button>}</div></div>)}{!packs.length && <div className="p-14 text-center text-sm text-slate-500">No final packs are available for management review.</div>}</div></section></div></div>;
}
