'use client';

import { useMemo } from 'react';
import { format } from 'date-fns';
import Link from 'next/link';
import { AlertCircle, ArrowLeft, Building2, CheckCircle2, CreditCard, FileText, ShieldCheck, Wallet } from 'lucide-react';

import { Badge } from '@/components/ui/badge';

type Account = { id: string; name: string; type: string; status: string; currency: string; balance: number | string; CorporateAccount?: Array<{ name: string }> };
type Invoice = { id: string; invoiceNumber: string; description: string; issueDate: string | Date; dueDate: string | Date; outstandingAmount: number | string; status: string };
type Entry = { id: string; type: string; reference?: string | null; reason?: string | null; createdAt: string | Date; amount: number | string; audit?: { settledBy: string; shiftReference: string | null; settledAt: string | Date } | null };

export function CityLedgerDetailClient({ account, openInvoices, recentEntries, totalOutstanding, asAt }: { account: Account; openInvoices: Invoice[]; recentEntries: Entry[]; totalOutstanding: number; asAt: number }) {
  const isSkipper = account.type === 'SKIPPER';
  const isRefundPayable = account.type === 'REFUND_PAYABLE';
  const currency = account.currency || 'NGN';
  const balance = Number(account.balance);
  const formatCurrency = (amount: number | string) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount));
  const formatBalance = (amount: number) => amount > .01 ? `${formatCurrency(amount)} DR` : amount < -.01 ? `${formatCurrency(Math.abs(amount))} CR` : formatCurrency(0);
  const overdueInvoices = useMemo(() => openInvoices.filter(invoice => new Date(invoice.dueDate).getTime() < asAt), [openInvoices, asAt]);
  const overdueAmount = overdueInvoices.reduce((sum, invoice) => sum + Number(invoice.outstandingAmount), 0);
  const currentAmount = Math.max(0, totalOutstanding - overdueAmount);
  const debitExposure = isRefundPayable ? Math.max(balance, 0) : Math.max(balance, 0);
  const creditExposure = isRefundPayable ? Math.max(-balance, 0) : Math.max(-balance, 0);

  return <main className="space-y-6 pb-10">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Link href="/accountant/city-ledger" className="mb-4 inline-flex items-center gap-2 text-xs text-cyan-300 hover:text-cyan-200"><ArrowLeft className="h-3.5 w-3.5" />Back to city ledger</Link><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-300"><Building2 className="h-4 w-4" />Account detail</div><h1 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">{isSkipper ? 'Skippers & Walk-Outs' : (account.CorporateAccount?.[0]?.name || account.name || 'Corporate account')}</h1><p className="mt-2 text-sm text-slate-400">{isSkipper ? 'Individual invoice settlement for walk-out and skipper exposure.' : 'Corporate city-ledger account with controlled invoice allocation and payment history.'}</p></div><div className="flex items-center gap-2"><Badge className="border border-emerald-300/20 bg-emerald-300/10 px-3 py-1.5 text-emerald-300">{account.status}</Badge><span className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-400">{account.type}</span></div></header>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Ledger posture" value={formatBalance(balance)} detail={isRefundPayable ? 'Refund liability owed by hotel' : balance < 0 ? 'Credit available to account' : balance > 0 ? 'Debit owed to property' : 'Account is settled'} icon={creditExposure > 0 ? Wallet : CreditCard} tone={creditExposure > 0 ? 'emerald' : debitExposure > 0 ? 'rose' : 'cyan'} /><Metric title="Open invoice exposure" value={formatCurrency(totalOutstanding)} detail={`${openInvoices.length} active invoice${openInvoices.length === 1 ? '' : 's'}`} icon={FileText} tone="cyan" /><Metric title="Past due" value={formatCurrency(overdueAmount)} detail={`${overdueInvoices.length} invoice${overdueInvoices.length === 1 ? '' : 's'} overdue`} icon={AlertCircle} tone="amber" /><Metric title="Control state" value={isRefundPayable ? 'Liability tracked' : Math.abs(balance - totalOutstanding) < .01 ? 'Aligned' : 'Review'} detail={isRefundPayable ? 'Separate from guest/corporate AR' : 'Account balance vs open invoice total'} icon={ShieldCheck} tone={isRefundPayable || Math.abs(balance - totalOutstanding) < .01 ? 'emerald' : 'amber'} /></section>

    <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Panel title="Exposure profile" subtitle="Debit and credit are intentionally shown as separate accounting positions"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-rose-300/15 bg-rose-300/[.05] p-4"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-rose-300"><CreditCard className="h-4 w-4" />Debit exposure</div><p className="mt-3 text-2xl font-semibold text-white">{formatCurrency(debitExposure)}</p><p className="mt-1 text-xs text-slate-500">{isRefundPayable ? 'Unexpected debit against hotel refund liability' : 'Amount owed to the property'}</p></div><div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[.05] p-4"><div className="flex items-center gap-2 text-xs uppercase tracking-wider text-emerald-300"><Wallet className="h-4 w-4" />{isRefundPayable ? 'Refund liability' : 'Credit position'}</div><p className="mt-3 text-2xl font-semibold text-white">{formatCurrency(creditExposure)}</p><p className="mt-1 text-xs text-slate-500">{isRefundPayable ? 'Credit owed by the hotel to the guest' : 'Credit owed to or available for the account'}</p></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Current invoice exposure</span><span className="text-slate-300">{formatCurrency(currentAmount)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-cyan-400" style={{ width: `${totalOutstanding ? currentAmount / totalOutstanding * 100 : 0}%` }} /></div><div className="mt-2 flex justify-between text-xs"><span className="text-amber-300">Past due {formatCurrency(overdueAmount)}</span><span className="text-slate-500">{totalOutstanding ? Math.round(overdueAmount / totalOutstanding * 100) : 0}% aged</span></div></div></Panel><Panel title="Settlement workflow" subtitle="Read-only Accountant view">{isRefundPayable ? <div className="rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-sm leading-6 text-amber-100"><Wallet className="mr-2 inline h-5 w-5 text-amber-300" />This is a hotel liability. Refund or apply the guest credit through the approved guest-credit workflow; it is not a collection account.</div> : <div className="rounded-xl border border-cyan-300/15 bg-cyan-300/[.05] p-4 text-sm leading-6 text-cyan-100"><ShieldCheck className="mr-2 inline h-5 w-5 text-cyan-300" />Invoice settlement is performed by Front Desk. This page is for exposure review and payment audit only.</div>}<div className="mt-4 rounded-xl border border-white/[.07] bg-slate-950/30 p-4 text-xs leading-5 text-slate-400"><ShieldCheck className="mr-1 inline h-4 w-4 text-emerald-300" />Payments require a reference and remain visible here with the operator and Front Desk shift that posted them.</div></Panel></section>

    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel title="Open invoice register" subtitle="Read-only invoice balances; settlement is performed by Front Desk"><div className="space-y-3">{openInvoices.length ? openInvoices.map(invoice => { const overdue = new Date(invoice.dueDate).getTime() < asAt; return <div key={invoice.id} className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2"><span className="font-semibold text-slate-100">{invoice.invoiceNumber}</span><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold ${overdue ? 'border-rose-300/20 bg-rose-300/10 text-rose-300' : 'border-emerald-300/20 bg-emerald-300/10 text-emerald-300'}`}>{overdue ? 'OVERDUE' : invoice.status}</span></div><p className="mt-2 text-sm text-slate-400">{invoice.description}</p><p className="mt-2 text-xs text-slate-500">Issued {format(new Date(invoice.issueDate), 'dd MMM yyyy')} · Due {format(new Date(invoice.dueDate), 'dd MMM yyyy')}</p></div><div className="text-right"><p className="text-[10px] uppercase tracking-wider text-slate-500">Outstanding</p><p className="mt-1 text-lg font-semibold text-rose-300">{formatCurrency(invoice.outstandingAmount)}</p></div></div></div>; }) : <div className="rounded-xl border border-dashed border-white/10 bg-white/[.025] p-12 text-center"><CheckCircle2 className="mx-auto mb-3 h-9 w-9 text-emerald-300" /><p className="font-medium text-slate-300">All invoices are settled</p></div>}</div></Panel><Panel title="Settlement audit" subtitle="Who posted each payment and under which Front Desk shift"><div className="space-y-1">{recentEntries.length ? recentEntries.map(entry => <div key={entry.id} className="border-b border-white/[.07] py-3 last:border-0"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium text-slate-200">{entry.type === 'TRANSFER_IN' ? 'Invoice transfer' : entry.type === 'PAYMENT' ? 'AR payment' : entry.type}</p><span className={`shrink-0 font-semibold ${entry.type === 'TRANSFER_IN' ? 'text-rose-300' : 'text-emerald-300'}`}>{entry.type === 'TRANSFER_IN' ? '+' : '-'}{formatCurrency(entry.amount)}</span></div><p className="mt-1 truncate text-xs text-slate-500">{entry.reference || entry.reason || 'Ledger entry'} · {format(new Date(entry.createdAt), 'dd MMM, HH:mm')}</p>{entry.type === 'PAYMENT' && <p className="mt-1 text-xs text-cyan-300">Settled by {entry.audit?.settledBy || 'Recorded operator'}{entry.audit?.shiftReference ? ` · Shift ${entry.audit.shiftReference}` : ''}</p>}</div>) : <p className="py-8 text-sm text-slate-500">No recent activity.</p>}</div></Panel></section>

  </main>;
}

function Metric({ title, value, detail, icon: Icon, tone }: { title: string; value: string; detail: string; icon: React.ElementType; tone: 'cyan' | 'rose' | 'amber' | 'emerald' }) { const colors = { cyan: 'border-cyan-300/15 text-cyan-300', rose: 'border-rose-300/15 text-rose-300', amber: 'border-amber-300/15 text-amber-300', emerald: 'border-emerald-300/15 text-emerald-300' }; return <div className={`rounded-2xl border bg-white/[.035] p-5 ${colors[tone]}`}><div className="flex items-start justify-between"><p className="text-xs uppercase tracking-wider text-slate-500">{title}</p><Icon className="h-5 w-5" /></div><p className="mt-4 text-2xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5 shadow-[0_18px_50px_rgba(0,0,0,.12)]"><div className="mb-5"><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div>{children}</section>; }
