import React from 'react';
import Link from 'next/link';
import {
  AlertCircle, ArrowRight, ArrowUpRight,
  Building2, CreditCard, FileText, Link2, ShieldCheck, Wallet,
  Sparkles, Users,
} from 'lucide-react';
import { redirect } from 'next/navigation';

// City-ledger balances must reflect the latest posted subledger activity.
export const dynamic = 'force-dynamic';
export const revalidate = 0;

import { ExportCityLedgerButton } from '@/components/accountant/ExportCityLedgerButton';
import { NewCityLedgerInvoiceModal } from '@/components/accountant/NewCityLedgerInvoiceModal';
import { auth } from '@/lib/auth';
import { prisma } from '@hotel-pms/db';

type AgingKey = 'CURRENT' | '31_60' | '61_90' | 'OVER_90';
const agingMeta: Record<AgingKey, { label: string; range: string; color: string; bar: string }> = {
  CURRENT: { label: 'Current', range: '0–30 days', color: 'text-emerald-300', bar: 'bg-emerald-400' },
  '31_60': { label: 'Watch', range: '31–60 days', color: 'text-amber-300', bar: 'bg-amber-400' },
  '61_90': { label: 'At risk', range: '61–90 days', color: 'text-orange-300', bar: 'bg-orange-400' },
  OVER_90: { label: 'Critical', range: '90+ days', color: 'text-rose-300', bar: 'bg-rose-400' },
};

const date = (value: Date | null) => value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(value) : '—';
const money = (value: number, currency: string, compact = false) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, notation: compact && Math.abs(value) >= 1_000_000 ? 'compact' : 'standard', maximumFractionDigits: compact && Math.abs(value) >= 1_000_000 ? 1 : 0 }).format(value);
const age = (dueDate: Date, now: number) => Math.max(0, Math.floor((now - dueDate.getTime()) / 86_400_000));
const agingKey = (days: number): AgingKey => days <= 30 ? 'CURRENT' : days <= 60 ? '31_60' : days <= 90 ? '61_90' : 'OVER_90';

export default async function CityLedgerPage() {
  const session = await auth();
  if (!session?.user) redirect('/login?callbackUrl=%2Faccountant%2Fcity-ledger');
  const propertyId = session.user.propertyId;
  if (!propertyId) return <EmptyState title="No property assigned" message="Your user account is not assigned to a property." />;

  const asAt = new Date();
  const now = asAt.getTime();
  const [property, accounts, invoices, payments, arControl, creditFolios, corporateAccounts] = await Promise.all([
    prisma.property.findUnique({ where: { id: propertyId }, select: { name: true, baseCurrency: true } }),
    prisma.cityLedgerAccount.findMany({ where: { propertyId }, orderBy: { name: 'asc' } }),
    prisma.cityLedgerInvoice.findMany({ where: { propertyId, status: { in: ['OPEN', 'PARTIALLY_PAID'] } }, include: { account: { select: { id: true, name: true, type: true, currency: true } } }, orderBy: [{ dueDate: 'asc' }, { issueDate: 'asc' }] }),
    prisma.cityLedgerEntry.findMany({ where: { propertyId, type: 'PAYMENT' }, include: { account: { select: { name: true, currency: true } }, allocations: { select: { amount: true } } }, orderBy: { createdAt: 'desc' } }),
    prisma.chartOfAccount.findFirst({ where: { propertyId, code: '1140', isActive: true }, select: { id: true, code: true, name: true } }),
    prisma.folio.findMany({ where: { propertyId, balance: { lt: 0 }, status: { not: 'VOID' } }, select: { id: true, folioNumber: true, balance: true, currency: true, guest: { select: { firstName: true, lastName: true } } }, orderBy: { balance: 'asc' }, take: 10 }),
    prisma.corporateAccount.findMany({ where: { propertyId, isActive: true }, select: { id: true, name: true, code: true, cityLedgerAccountId: true } }),
  ]);
  const currency = property?.baseCurrency || accounts[0]?.currency || 'NGN';
  const invoiceAccounts = accounts.filter(account => account.type === 'CORPORATE' && account.status === 'ACTIVE').map(account => ({ id: account.id, name: account.name }));
  const debtorAccounts = accounts.filter(account => Number(account.balance) > 0);
  const totalOutstanding = debtorAccounts.reduce((sum, account) => sum + Number(account.balance), 0);
  const totalCredits = accounts.reduce((sum, account) => sum + Math.abs(Math.min(0, Number(account.balance))), 0);
  const cityLedgerCreditAccounts = accounts.filter(account => Number(account.balance) < 0);
  const guestFolioCredit = creditFolios.reduce((sum, folio) => sum + Math.abs(Number(folio.balance)), 0);
  const linkedCorporateAccounts = corporateAccounts.filter(account => account.cityLedgerAccountId).length;
  const unlinkedCorporateAccounts = corporateAccounts.filter(account => !account.cityLedgerAccountId);
  const openRows = invoices.map(invoice => ({ invoice, days: age(invoice.dueDate, now), overdue: invoice.dueDate.getTime() < now }));
  const aging = (Object.keys(agingMeta) as AgingKey[]).map(key => ({ key, ...agingMeta[key], amount: openRows.filter(row => agingKey(row.days) === key).reduce((sum, row) => sum + Number(row.invoice.outstandingAmount), 0), count: openRows.filter(row => agingKey(row.days) === key).length }));
  const overdueAmount = aging.filter(item => item.key !== 'CURRENT').reduce((sum, item) => sum + item.amount, 0);
  const dueNextSeven = openRows.filter(row => !row.overdue && row.invoice.dueDate.getTime() <= now + 7 * 86_400_000).reduce((sum, row) => sum + Number(row.invoice.outstandingAmount), 0);
  const unappliedPayments = payments.filter(payment => Number(payment.amount) - payment.allocations.reduce((sum, allocation) => sum + Number(allocation.amount), 0) > 0.01);
  const unappliedAmount = unappliedPayments.reduce((sum, payment) => sum + Number(payment.amount) - payment.allocations.reduce((allocationSum, allocation) => allocationSum + Number(allocation.amount), 0), 0);
  const collected90 = payments.filter(payment => payment.createdAt.getTime() >= now - 90 * 86_400_000).reduce((sum, payment) => sum + Number(payment.amount), 0);
  const lastPaymentByAccount = new Map<string, Date>();
  for (const payment of payments.slice().reverse()) if (!lastPaymentByAccount.has(payment.accountId)) lastPaymentByAccount.set(payment.accountId, payment.createdAt);
  const focusAccounts = debtorAccounts.slice().sort((a, b) => Number(b.balance) - Number(a.balance)).slice(0, 6);
  const accountDirectory = accounts.slice().sort((a, b) => a.name.localeCompare(b.name));
  const weekly = Array.from({ length: 8 }, (_, index) => {
    const end = now - (7 - index) * 7 * 86_400_000;
    const start = end - 7 * 86_400_000;
    return { label: new Intl.DateTimeFormat('en-NG', { month: 'short', day: 'numeric' }).format(new Date(end)), amount: payments.filter(payment => payment.createdAt.getTime() >= start && payment.createdAt.getTime() < end).reduce((sum, payment) => sum + Number(payment.amount), 0) };
  });
  const maxWeekly = Math.max(...weekly.map(item => item.amount), 1);
  const glLines = arControl ? await prisma.journalEntryLine.aggregate({ where: { accountId: arControl.id, entry: { propertyId, status: 'POSTED' } }, _sum: { debit: true, credit: true } }) : null;
  const glBalance = glLines ? Number(glLines._sum.debit || 0) - Number(glLines._sum.credit || 0) : null;
  const variance = glBalance === null ? null : glBalance - totalOutstanding;
  const exportRows = accounts.filter(account => Math.abs(Number(account.balance)) > 0).map(account => ({ name: account.name, type: account.type, balance: Number(account.balance), currency: account.currency, status: account.status }));

  return (
    <main className="min-h-screen bg-[#07111f] p-5 text-slate-100 md:p-8">
      <div className="mx-auto max-w-[1480px] space-y-6">
        <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-cyan-300"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_14px_#67e8f9]" />City ledger command centre</div><h1 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">Corporate receivables, under control.</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">A decision-grade portfolio view of direct-bill exposure, invoice ageing, cash application, credit risk, and the controls required before close for {property?.name || 'this property'}.</p></div><div className="flex flex-wrap items-center gap-2"><div className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs text-slate-400"><span className="mr-2 text-slate-500">As at</span><span className="font-medium text-slate-200">{date(asAt)}</span><span className="ml-2 text-emerald-300">Live</span></div><NewCityLedgerInvoiceModal accounts={invoiceAccounts} /><ExportCityLedgerButton rows={exportRows} currency={currency} /></div></header>
        <nav aria-label="City ledger workspaces" className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><WorkspaceLink href="/accountant/city-ledger/accounts" icon={Building2} label="Account portfolio" detail="All city-ledger accounts" /><WorkspaceLink href="/accountant/city-ledger/credits" icon={CreditCard} label="Credits & advances" detail="Guest credits and unapplied receipts" /><WorkspaceLink href="/accountant/city-ledger/invoices" icon={FileText} label="Invoice register" detail="Open invoices and ageing" /><WorkspaceLink href="/accountant/city-ledger/payments" icon={Link2} label="Payment register" detail="Allocate, unapply, transfer, reverse" /></nav>

        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric title="Debit AR exposure" value={money(totalOutstanding, currency, true)} caption={`${debtorAccounts.length} debtor accounts`} icon={Building2} tone="cyan" href="/accountant/city-ledger/accounts" /><Metric title="Overdue exposure" value={money(overdueAmount, currency, true)} caption={`${totalOutstanding ? Math.round(overdueAmount / Math.max(totalOutstanding, 1) * 100) : 0}% of portfolio`} icon={AlertCircle} tone="rose" href="/accountant/city-ledger/invoices" /><Metric title="City-ledger credits" value={money(totalCredits, currency, true)} caption={`${cityLedgerCreditAccounts.length} account credit balances`} icon={CreditCard} tone="emerald" href="/accountant/city-ledger/credits" /><Metric title="Guest folio credits" value={money(guestFolioCredit, currency, true)} caption={`${creditFolios.length} folio${creditFolios.length === 1 ? '' : 's'} due review`} icon={Wallet} tone="violet" href="/accountant/guest-credits" /><Metric title="Unapplied cash" value={money(unappliedAmount, currency, true)} caption={`${unappliedPayments.length} item${unappliedPayments.length === 1 ? '' : 's'} needing allocation`} icon={Link2} tone="amber" href="/accountant/city-ledger/payments" /></section>

        <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]" id="aging"><Panel title="Portfolio ageing" subtitle="Open invoices aged from contractual due date" action={<Link href="/accountant/city-ledger/invoices" className="text-xs text-cyan-300 hover:text-cyan-200">Review open invoices <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="grid gap-6 lg:grid-cols-[1fr_230px]"><div className="space-y-4">{aging.map(item => <Link href="/accountant/city-ledger/invoices" key={item.key} className="group block"><div className="mb-2 flex items-center justify-between text-sm"><span className={`font-medium ${item.color}`}>{item.label} <span className="ml-1 text-xs text-slate-500">{item.range}</span></span><span className="font-semibold text-slate-200">{money(item.amount, currency)} <span className="ml-1 text-xs font-normal text-slate-500">{item.count} inv.</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full group-hover:brightness-125 ${item.bar}`} style={{ width: `${totalOutstanding ? Math.max(item.amount ? 3 : 0, item.amount / totalOutstanding * 100) : 0}%` }} /></div></Link>)}</div><div className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Collection outlook</p><p className="mt-2 text-3xl font-semibold text-white">{money(dueNextSeven, currency, true)}</p><p className="mt-1 text-xs text-slate-500">Due in the next 7 days</p><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs uppercase tracking-wider text-slate-500">Credit balances</p><p className="mt-1 text-lg font-semibold text-emerald-300">{money(totalCredits, currency)} CR</p></div></div></div></Panel><Panel title="Cash application" subtitle="Payments received by week" action={<Link href="/accountant/city-ledger/payments" className="text-xs text-slate-400 hover:text-white">Activity <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="flex h-44 items-end gap-2 border-b border-l border-white/10 px-2 pt-6">{weekly.map(item => <div key={item.label} className="group flex h-full flex-1 flex-col justify-end"><div className="relative flex-1"><div className="absolute bottom-0 left-1/2 w-full -translate-x-1/2 rounded-t-md bg-cyan-400/80 group-hover:bg-cyan-300" style={{ height: `${Math.max(item.amount ? 5 : 0, item.amount / maxWeekly * 100)}%` }} /></div><span className="mt-2 text-center text-[10px] text-slate-500">{item.label}</span></div>)}</div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-slate-500">8-week collection trend</span><span className="font-medium text-cyan-300">{money(collected90, currency, true)} / 90d</span></div></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Control health" subtitle="AR subledger, GL control, and reconciliation signals"><div className="space-y-3"><ControlRow label="AR control account" value={arControl ? `${arControl.code} · ${arControl.name}` : 'Not configured'} status={arControl ? 'OK' : 'REVIEW'} /><ControlRow label="City-ledger subledger" value={money(totalOutstanding, currency)} status="OK" /><ControlRow label="Posted GL balance" value={glBalance === null ? 'Unavailable' : money(glBalance, currency)} status={glBalance === null ? 'REVIEW' : 'OK'} /><ControlRow label="Reconciliation variance" value={variance === null ? 'Not tested' : money(Math.abs(variance), currency)} status={variance === null || Math.abs(variance) < .01 ? 'OK' : 'REVIEW'} /><ControlRow label="Corporate ledger links" value={`${linkedCorporateAccounts} of ${corporateAccounts.length} active corporate accounts`} status={unlinkedCorporateAccounts.length ? 'REVIEW' : 'OK'} /></div><div className="mt-5 rounded-xl border border-emerald-400/15 bg-emerald-400/[.06] p-3 text-xs leading-5 text-emerald-200"><ShieldCheck className="mr-1 inline h-4 w-4" />Every collection and invoice action remains traceable through the city-ledger entry and invoice records.</div></Panel><Panel title="Next best actions" subtitle="Move from signal to controlled workflow"><Action href="/accountant/city-ledger/accounts" icon={Users} title="Prioritise collection" detail={`${focusAccounts.length} highest-value accounts in the portfolio`} /><Action href="/accountant/city-ledger/invoices" icon={FileText} title="Review ageing" detail={`${openRows.length} open invoices require monitoring`} /><Action href="/accountant/city-ledger/payments" icon={Link2} title="Clear unapplied cash" detail={`${unappliedPayments.length} payment${unappliedPayments.length === 1 ? '' : 's'} not marked settled`} /></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]" id="accounts"><Panel title="Collection queue" subtitle="Highest-value debtor accounts with direct drill-down"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Account</th><th className="pb-3 font-medium">Type</th><th className="pb-3 font-medium">Last payment</th><th className="pb-3 text-right font-medium">Balance</th><th className="pb-3 text-right font-medium">Settlement</th></tr></thead><tbody className="divide-y divide-white/[.07]">{focusAccounts.length ? focusAccounts.map(account => <tr key={account.id} className="hover:bg-white/[.025]"><td className="py-4"><Link href={`/accountant/city-ledger/${account.id}`} className="font-medium text-cyan-300 hover:text-cyan-200">{account.name}</Link><div className="mt-1 font-mono text-[10px] text-slate-600">{account.id.slice(0, 8)}</div></td><td className="py-4 text-slate-400">{account.type}</td><td className="py-4 text-slate-400">{date(lastPaymentByAccount.get(account.id) || null)}</td><td className="py-4 text-right font-semibold text-rose-300">{money(Number(account.balance), account.currency || currency)}</td><td className="py-4 text-right"><Link href={`/accountant/city-ledger/${account.id}`} className="text-xs font-medium text-cyan-300 hover:text-cyan-200">Open invoices <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></td></tr>) : <tr><td colSpan={5} className="py-10 text-center text-slate-500">No debtor accounts require collection action.</td></tr>}</tbody></table></div></Panel><Panel title="Portfolio mix" subtitle="Exposure by city-ledger account type"><div className="space-y-3">{Object.entries(focusAccounts.reduce<Record<string, number>>((result, account) => { result[account.type] = (result[account.type] || 0) + Number(account.balance); return result; }, {})).map(([type, amount]) => <div key={type}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-400">{type}</span><span className="font-medium text-slate-200">{money(amount, currency)}</span></div><div className="h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-violet-400" style={{ width: `${totalOutstanding ? amount / totalOutstanding * 100 : 0}%` }} /></div></div>)}{!focusAccounts.length && <p className="text-sm text-slate-500">No balance mix to display.</p>}<div className="mt-5 rounded-xl border border-cyan-400/15 bg-cyan-400/[.05] p-3 text-xs leading-5 text-cyan-100"><Sparkles className="mr-1 inline h-4 w-4" />Use account drill-down for statement review, invoice allocation, and payment history.</div></div></Panel></section>
        <section><Panel title="All city-ledger accounts" subtitle="Corporate, skipper, credit, zero-balance, and other accounts remain visible here"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Account</th><th className="pb-3 font-medium">Type</th><th className="pb-3 font-medium">Status</th><th className="pb-3 text-right font-medium">Balance classification</th><th className="pb-3 text-right font-medium">Balance</th><th className="pb-3 text-right font-medium">Open</th></tr></thead><tbody className="divide-y divide-white/[.07]">{accountDirectory.length ? accountDirectory.map(account => { const balance = Number(account.balance); const isLiability = account.type === 'REFUND_PAYABLE'; const classification = balance > .01 ? (isLiability ? 'CREDIT · Owed to account' : 'DEBIT · Owed to property') : balance < -.01 ? (isLiability ? 'DEBIT · Owed to property' : 'CREDIT · Owed to account') : 'SETTLED · Zero balance'; return <tr key={account.id} className="hover:bg-white/[.025]"><td className="py-4"><Link href={`/accountant/city-ledger/${account.id}`} className="font-medium text-cyan-300 hover:text-cyan-200">{account.name}</Link><div className="mt-1 font-mono text-[10px] text-slate-600">{account.id.slice(0, 8)}</div></td><td className="py-4 text-slate-400">{account.type}</td><td className="py-4 text-slate-400">{account.status}</td><td className={`py-4 text-right text-xs font-medium ${(balance > .01 && !isLiability) || (balance < -.01 && isLiability) ? 'text-rose-300' : (balance < -.01 && !isLiability) || (balance > .01 && isLiability) ? 'text-emerald-300' : 'text-slate-500'}`}>{classification}</td><td className="py-4 text-right font-semibold text-slate-200">{money(Math.abs(balance), account.currency || currency)}{balance > .01 ? (isLiability ? ' CR' : ' DR') : balance < -.01 ? (isLiability ? ' DR' : ' CR') : ''}</td><td className="py-4 text-right"><Link href={`/accountant/city-ledger/${account.id}`} className="text-xs text-cyan-300 hover:text-cyan-200">View ledger <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link></td></tr>; }) : <tr><td colSpan={6} className="py-10 text-center text-slate-500">No city-ledger accounts configured.</td></tr>}</tbody></table></div>{unlinkedCorporateAccounts.length > 0 && <div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/[.06] p-3 text-xs leading-5 text-amber-100"><AlertCircle className="mr-1 inline h-4 w-4" />{unlinkedCorporateAccounts.length} active corporate account{unlinkedCorporateAccounts.length === 1 ? '' : 's'} have no linked city-ledger account: {unlinkedCorporateAccounts.map(account => `${account.name} (${account.code})`).join(', ')}. Link them before direct-bill charges can appear here.</div>}</Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]" id="invoices"><Panel title="Open invoice register" subtitle="Invoice-level ageing, due dates, and outstanding exposure" action={<Link href="/accountant/reports" className="text-xs text-slate-400 hover:text-white">Reports <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="overflow-x-auto"><table className="w-full min-w-[730px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Invoice</th><th className="pb-3 font-medium">Account</th><th className="pb-3 font-medium">Due</th><th className="pb-3 font-medium">Age</th><th className="pb-3 text-right font-medium">Outstanding</th></tr></thead><tbody className="divide-y divide-white/[.07]">{openRows.slice(0, 8).map(row => <tr key={row.invoice.id}><td className="py-4"><span className="font-medium text-slate-200">{row.invoice.invoiceNumber}</span><span className="mt-1 block text-xs text-slate-500">{row.invoice.description}</span></td><td className="py-4 text-slate-400">{row.invoice.account.name}</td><td className={`py-4 ${row.overdue ? 'text-rose-300' : 'text-slate-400'}`}>{date(row.invoice.dueDate)}</td><td className="py-4"><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold ${row.overdue ? 'border-rose-400/20 bg-rose-400/10 text-rose-300' : 'border-emerald-400/20 bg-emerald-400/10 text-emerald-300'}`}>{row.days}d</span></td><td className="py-4 text-right font-semibold text-slate-100">{money(Number(row.invoice.outstandingAmount), row.invoice.currency || currency)}</td></tr>)}{!openRows.length && <tr><td colSpan={5} className="py-10 text-center text-slate-500">No open invoices.</td></tr>}</tbody></table></div>{openRows.length > 8 && <p className="mt-4 text-xs text-slate-500">Showing 8 of {openRows.length} open invoices. Use an account drill-down for the complete register.</p>}</Panel><Panel title="Payment activity" subtitle="Latest city-ledger receipts and reconciliation state" id="payments"><div className="space-y-1">{payments.slice(0, 7).map(payment => <div key={payment.id} className="flex items-center justify-between gap-3 border-b border-white/[.07] py-3 last:border-0"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-200">{payment.reference || payment.id.slice(0, 8)}</p><p className="mt-1 text-xs text-slate-500">{payment.account.name} · {date(payment.createdAt)}</p></div><div className="text-right"><p className="font-medium text-emerald-300">{money(Number(payment.amount), payment.currency || currency)}</p><p className={`text-[10px] ${payment.status === 'SETTLED' ? 'text-emerald-400' : 'text-amber-300'}`}>{payment.status === 'SETTLED' ? 'Applied' : 'Needs review'}</p></div></div>)}{!payments.length && <p className="py-8 text-sm text-slate-500">No payment activity recorded.</p>}</div></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1fr_1fr]" id="credits"><Panel title="Credit control" subtitle="Balances owed to guests or available for future application"><div className="mb-4 rounded-xl border border-emerald-400/15 bg-emerald-400/[.05] p-3 text-xs leading-5 text-emerald-100"><Wallet className="mr-1 inline h-4 w-4" />Negative balances are credits, not receivables. They should be refunded, applied to a future stay, or transferred through an approved credit workflow.</div><div className="space-y-3">{cityLedgerCreditAccounts.map(account => <Link href={`/accountant/city-ledger/${account.id}`} key={account.id} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-slate-950/30 p-3 hover:bg-white/[.05]"><span><span className="block text-sm font-medium text-slate-200">{account.name}</span><span className="mt-1 block text-xs text-slate-500">City-ledger account · {account.type}</span></span><span className="font-semibold text-emerald-300">{money(Math.abs(Number(account.balance)), account.currency || currency)} CR</span></Link>)}{!cityLedgerCreditAccounts.length && <p className="text-sm text-slate-500">No city-ledger credit balances.</p>}</div></Panel><Panel title="Guest folio credits" subtitle="Negative folio balances retained during checkout" action={<Link href="/accountant/guest-credits" className="text-xs text-cyan-300 hover:text-cyan-200">Open guest credits <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="space-y-3">{creditFolios.map(folio => <div key={folio.id} className="flex items-center justify-between rounded-xl border border-white/[.07] bg-slate-950/30 p-3"><div><p className="text-sm font-medium text-slate-200">{folio.guest ? `${folio.guest.firstName} ${folio.guest.lastName}`.trim() : 'Unassigned guest'}</p><p className="mt-1 text-xs text-slate-500">Folio {folio.folioNumber}</p></div><span className="font-semibold text-emerald-300">{money(Math.abs(Number(folio.balance)), folio.currency || currency)} CR</span></div>)}{!creditFolios.length && <p className="text-sm text-slate-500">No guest folio credits awaiting review.</p>}</div></Panel></section>
      </div>
    </main>
  );
}

function Metric({ title, value, caption, icon: Icon, tone, href }: { title: string; value: string; caption: string; icon: React.ElementType; tone: 'cyan' | 'rose' | 'emerald' | 'amber' | 'violet'; href: string }) { const tones = { cyan: 'text-cyan-300 border-cyan-300/15', rose: 'text-rose-300 border-rose-300/15', emerald: 'text-emerald-300 border-emerald-300/15', amber: 'text-amber-300 border-amber-300/15', violet: 'text-violet-300 border-violet-300/15' }; return <Link href={href} className={`group rounded-2xl border bg-white/[.035] p-5 transition hover:-translate-y-0.5 hover:bg-white/[.06] ${tones[tone]}`}><div className="flex items-start justify-between"><p className="text-xs font-medium uppercase tracking-wider text-slate-500">{title}</p><Icon className="h-5 w-5 opacity-80" /></div><p className="mt-5 text-2xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{caption}<ArrowUpRight className="ml-1 inline h-3 w-3 opacity-0 transition group-hover:opacity-100" /></p></Link>; }
function Panel({ title, subtitle, action, children, id }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode; id?: string }) { return <section id={id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5 shadow-[0_18px_50px_rgba(0,0,0,.12)]"><div className="mb-6 flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div>{action}</div>{children}</section>; }
function ControlRow({ label, value, status }: { label: string; value: string; status: 'OK' | 'REVIEW' }) { return <div className="flex items-center justify-between gap-3 rounded-xl border border-white/[.07] bg-slate-950/30 p-3"><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${status === 'OK' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-400/10 text-amber-300'}`}>{status}</span></div>; }
function Action({ href, icon: Icon, title, detail }: { href: string; icon: React.ElementType; title: string; detail: string }) { return <Link href={href} className="group flex items-center gap-3 border-b border-white/[.07] py-3 last:border-0"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[.06] text-cyan-300"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-slate-200">{title}</span><span className="mt-1 block text-xs text-slate-500">{detail}</span></span><ArrowRight className="h-4 w-4 text-slate-600 group-hover:text-cyan-300" /></Link>; }
function WorkspaceLink({ href, icon: Icon, label, detail }: { href: string; icon: React.ElementType; label: string; detail: string }) { return <Link href={href} className="group flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.035] px-4 py-3 transition hover:border-cyan-300/25 hover:bg-cyan-300/[.06]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-300/10 text-cyan-300"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-slate-200">{label}</span><span className="mt-1 block truncate text-xs text-slate-500">{detail}</span></span><ArrowRight className="h-4 w-4 text-slate-600 transition group-hover:translate-x-0.5 group-hover:text-cyan-300" /></Link>; }
function EmptyState({ title, message }: { title: string; message: string }) { return <div className="flex min-h-screen items-center justify-center bg-[#07111f] p-8 text-center text-slate-300"><div><FileText className="mx-auto mb-3 h-10 w-10 text-slate-500" /><h1 className="text-xl font-semibold text-white">{title}</h1><p className="mt-2 text-sm text-slate-400">{message}</p></div></div>; }

// Trigger vercel deployment
