import React from 'react';
import Link from 'next/link';
import {
  AlertCircle, ArrowRight, ArrowUpRight, Banknote,
  Building2, FileText, Link2, ShieldCheck,
  Sparkles, Users,
} from 'lucide-react';
import { redirect } from 'next/navigation';

import { ExportCityLedgerButton } from '@/components/accountant/ExportCityLedgerButton';
import { NewCityLedgerInvoiceModal } from '@/components/accountant/NewCityLedgerInvoiceModal';
import { RecordCityLedgerPaymentModal } from '@/components/accountant/RecordCityLedgerPaymentModal';
import { auth } from '@/lib/auth';
import { prisma } from '@hotel-pms/db';

type AgingKey = 'CURRENT' | '31_60' | '61_90' | 'OVER_90';
const agingMeta: Record<AgingKey, { label: string; range: string; color: string; bar: string }> = {
  CURRENT: { label: 'Current', range: '0–30 days', color: 'text-emerald-300', bar: 'bg-emerald-400' },
  '31_60': { label: 'Watch', range: '31–60 days', color: 'text-amber-300', bar: 'bg-amber-400' },
  '61_90': { label: 'At risk', range: '61–90 days', color: 'text-orange-300', bar: 'bg-orange-400' },
  OVER_90: { label: 'Critical', range: '90+ days', color: 'text-rose-300', bar: 'bg-rose-400' },
};

const date = (value: Date | null) => value ? new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(value) : '—';
const money = (value: number, currency: string, compact = false) => new Intl.NumberFormat('en-NG', { style: 'currency', currency, notation: compact && Math.abs(value) >= 1_000_000 ? 'compact' : 'standard', maximumFractionDigits: compact && Math.abs(value) >= 1_000_000 ? 1 : 0 }).format(value);
const age = (dueDate: Date, now: number) => Math.max(0, Math.floor((now - dueDate.getTime()) / 86_400_000));
const agingKey = (days: number): AgingKey => days <= 30 ? 'CURRENT' : days <= 60 ? '31_60' : days <= 90 ? '61_90' : 'OVER_90';

export default async function CityLedgerPage() {
  const session = await auth();
  if (!session?.user) redirect('/login?callbackUrl=%2Faccountant%2Fcity-ledger');
  const propertyId = session.user.propertyId;
  if (!propertyId) return <EmptyState title="No property assigned" message="Your user account is not assigned to a property." />;

  const asAt = new Date();
  const now = asAt.getTime();
  const [property, accounts, invoices, payments, arControl] = await Promise.all([
    prisma.property.findUnique({ where: { id: propertyId }, select: { name: true, baseCurrency: true } }),
    prisma.cityLedgerAccount.findMany({ where: { propertyId }, orderBy: { name: 'asc' } }),
    prisma.cityLedgerInvoice.findMany({ where: { propertyId, status: { in: ['OPEN', 'PARTIALLY_PAID'] } }, include: { account: { select: { id: true, name: true, type: true, currency: true } } }, orderBy: [{ dueDate: 'asc' }, { issueDate: 'asc' }] }),
    prisma.cityLedgerEntry.findMany({ where: { propertyId, type: 'PAYMENT' }, include: { account: { select: { name: true, currency: true } } }, orderBy: { createdAt: 'desc' } }),
    prisma.chartOfAccount.findFirst({ where: { propertyId, code: '1140', isActive: true }, select: { id: true, code: true, name: true } }),
  ]);
  const currency = property?.baseCurrency || accounts[0]?.currency || 'NGN';
  const debtorAccounts = accounts.filter(account => Number(account.balance) > 0);
  const totalOutstanding = debtorAccounts.reduce((sum, account) => sum + Number(account.balance), 0);
  const totalCredits = accounts.reduce((sum, account) => sum + Math.abs(Math.min(0, Number(account.balance))), 0);
  const openRows = invoices.map(invoice => ({ invoice, days: age(invoice.dueDate, now), overdue: invoice.dueDate.getTime() < now }));
  const aging = (Object.keys(agingMeta) as AgingKey[]).map(key => ({ key, ...agingMeta[key], amount: openRows.filter(row => agingKey(row.days) === key).reduce((sum, row) => sum + Number(row.invoice.outstandingAmount), 0), count: openRows.filter(row => agingKey(row.days) === key).length }));
  const overdueAmount = aging.filter(item => item.key !== 'CURRENT').reduce((sum, item) => sum + item.amount, 0);
  const dueNextSeven = openRows.filter(row => !row.overdue && row.invoice.dueDate.getTime() <= now + 7 * 86_400_000).reduce((sum, row) => sum + Number(row.invoice.outstandingAmount), 0);
  const unappliedPayments = payments.filter(payment => payment.status !== 'SETTLED');
  const collected90 = payments.filter(payment => payment.createdAt.getTime() >= now - 90 * 86_400_000).reduce((sum, payment) => sum + Number(payment.amount), 0);
  const lastPaymentByAccount = new Map<string, Date>();
  for (const payment of payments.slice().reverse()) if (!lastPaymentByAccount.has(payment.accountId)) lastPaymentByAccount.set(payment.accountId, payment.createdAt);
  const focusAccounts = debtorAccounts.slice().sort((a, b) => Number(b.balance) - Number(a.balance)).slice(0, 6);
  const weekly = Array.from({ length: 8 }, (_, index) => {
    const end = now - (7 - index) * 7 * 86_400_000;
    const start = end - 7 * 86_400_000;
    return { label: new Intl.DateTimeFormat('en-NG', { month: 'short', day: 'numeric' }).format(new Date(end)), amount: payments.filter(payment => payment.createdAt.getTime() >= start && payment.createdAt.getTime() < end).reduce((sum, payment) => sum + Number(payment.amount), 0) };
  });
  const maxWeekly = Math.max(...weekly.map(item => item.amount), 1);
  const glLines = arControl ? await prisma.journalEntryLine.aggregate({ where: { accountId: arControl.id, entry: { propertyId, status: 'POSTED' } }, _sum: { debit: true, credit: true } }) : null;
  const glBalance = glLines ? Number(glLines._sum.debit || 0) - Number(glLines._sum.credit || 0) : null;
  const variance = glBalance === null ? null : glBalance - totalOutstanding;
  const exportRows = accounts.filter(account => Math.abs(Number(account.balance)) > 0).map(account => ({ name: account.name, type: account.type, balance: Number(account.balance), currency: account.currency, status: account.status }));

  return (
    <main className="min-h-screen bg-[#07111f] p-5 text-slate-100 md:p-8">
      <div className="mx-auto max-w-[1480px] space-y-6">
        <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-cyan-300"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_14px_#67e8f9]" />City ledger command centre</div><h1 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">Corporate receivables, under control.</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">A decision-grade portfolio view of direct-bill exposure, invoice ageing, cash application, credit risk, and the controls required before close for {property?.name || 'this property'}.</p></div><div className="flex flex-wrap items-center gap-2"><div className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs text-slate-400"><span className="mr-2 text-slate-500">As at</span><span className="font-medium text-slate-200">{date(asAt)}</span><span className="ml-2 text-emerald-300">Live</span></div><NewCityLedgerInvoiceModal accounts={accounts.filter(account => account.status === 'ACTIVE').map(account => ({ id: account.id, name: account.name }))} /><ExportCityLedgerButton rows={exportRows} currency={currency} /></div></header>

        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Net AR exposure" value={money(totalOutstanding, currency, true)} caption={`${debtorAccounts.length} debtor accounts`} icon={Building2} tone="cyan" href="#accounts" /><Metric title="Overdue exposure" value={money(overdueAmount, currency, true)} caption={`${totalOutstanding ? Math.round(overdueAmount / Math.max(totalOutstanding, 1) * 100) : 0}% of portfolio`} icon={AlertCircle} tone="rose" href="#aging" /><Metric title="Cash applied · 90d" value={money(collected90, currency, true)} caption="Payments received in last 90 days" icon={Banknote} tone="emerald" href="#payments" /><Metric title="Unapplied cash" value={money(unappliedPayments.reduce((sum, payment) => sum + Number(payment.amount), 0), currency, true)} caption={`${unappliedPayments.length} item${unappliedPayments.length === 1 ? '' : 's'} needing allocation`} icon={Link2} tone="amber" href="#payments" /></section>

        <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]" id="aging"><Panel title="Portfolio ageing" subtitle="Open invoices aged from contractual due date" action={<Link href="#invoices" className="text-xs text-cyan-300 hover:text-cyan-200">Review open invoices <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="grid gap-6 lg:grid-cols-[1fr_230px]"><div className="space-y-4">{aging.map(item => <Link href="#invoices" key={item.key} className="group block"><div className="mb-2 flex items-center justify-between text-sm"><span className={`font-medium ${item.color}`}>{item.label} <span className="ml-1 text-xs text-slate-500">{item.range}</span></span><span className="font-semibold text-slate-200">{money(item.amount, currency)} <span className="ml-1 text-xs font-normal text-slate-500">{item.count} inv.</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full group-hover:brightness-125 ${item.bar}`} style={{ width: `${totalOutstanding ? Math.max(item.amount ? 3 : 0, item.amount / totalOutstanding * 100) : 0}%` }} /></div></Link>)}</div><div className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Collection outlook</p><p className="mt-2 text-3xl font-semibold text-white">{money(dueNextSeven, currency, true)}</p><p className="mt-1 text-xs text-slate-500">Due in the next 7 days</p><div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs uppercase tracking-wider text-slate-500">Credit balances</p><p className="mt-1 text-lg font-semibold text-emerald-300">{money(totalCredits, currency)} CR</p></div></div></div></Panel><Panel title="Cash application" subtitle="Payments received by week" action={<Link href="#payments" className="text-xs text-slate-400 hover:text-white">Activity <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="flex h-44 items-end gap-2 border-b border-l border-white/10 px-2 pt-6">{weekly.map(item => <div key={item.label} className="group flex h-full flex-1 flex-col justify-end"><div className="relative flex-1"><div className="absolute bottom-0 left-1/2 w-full -translate-x-1/2 rounded-t-md bg-cyan-400/80 group-hover:bg-cyan-300" style={{ height: `${Math.max(item.amount ? 5 : 0, item.amount / maxWeekly * 100)}%` }} /></div><span className="mt-2 text-center text-[10px] text-slate-500">{item.label}</span></div>)}</div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-slate-500">8-week collection trend</span><span className="font-medium text-cyan-300">{money(collected90, currency, true)} / 90d</span></div></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Panel title="Control health" subtitle="AR subledger, GL control, and reconciliation signals"><div className="space-y-3"><ControlRow label="AR control account" value={arControl ? `${arControl.code} · ${arControl.name}` : 'Not configured'} status={arControl ? 'OK' : 'REVIEW'} /><ControlRow label="City-ledger subledger" value={money(totalOutstanding, currency)} status="OK" /><ControlRow label="Posted GL balance" value={glBalance === null ? 'Unavailable' : money(glBalance, currency)} status={glBalance === null ? 'REVIEW' : 'OK'} /><ControlRow label="Reconciliation variance" value={variance === null ? 'Not tested' : money(Math.abs(variance), currency)} status={variance === null || Math.abs(variance) < .01 ? 'OK' : 'REVIEW'} /></div><div className="mt-5 rounded-xl border border-emerald-400/15 bg-emerald-400/[.06] p-3 text-xs leading-5 text-emerald-200"><ShieldCheck className="mr-1 inline h-4 w-4" />Every collection and invoice action remains traceable through the city-ledger entry and invoice records.</div></Panel><Panel title="Next best actions" subtitle="Move from signal to controlled workflow"><Action href="#accounts" icon={Users} title="Prioritise collection" detail={`${focusAccounts.length} highest-value accounts in the portfolio`} /><Action href="#invoices" icon={FileText} title="Review ageing" detail={`${openRows.length} open invoices require monitoring`} /><Action href="#payments" icon={Link2} title="Clear unapplied cash" detail={`${unappliedPayments.length} payment${unappliedPayments.length === 1 ? '' : 's'} not marked settled`} /></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]" id="accounts"><Panel title="Collection queue" subtitle="Highest-value debtor accounts with direct drill-down"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Account</th><th className="pb-3 font-medium">Type</th><th className="pb-3 font-medium">Last payment</th><th className="pb-3 text-right font-medium">Balance</th><th className="pb-3 text-right font-medium">Action</th></tr></thead><tbody className="divide-y divide-white/[.07]">{focusAccounts.length ? focusAccounts.map(account => <tr key={account.id} className="hover:bg-white/[.025]"><td className="py-4"><Link href={`/accountant/city-ledger/${account.id}`} className="font-medium text-cyan-300 hover:text-cyan-200">{account.name}</Link><div className="mt-1 font-mono text-[10px] text-slate-600">{account.id.slice(0, 8)}</div></td><td className="py-4 text-slate-400">{account.type}</td><td className="py-4 text-slate-400">{date(lastPaymentByAccount.get(account.id) || null)}</td><td className="py-4 text-right font-semibold text-rose-300">{money(Number(account.balance), account.currency || currency)}</td><td className="py-4 text-right"><RecordCityLedgerPaymentModal accountId={account.id} accountName={account.name} balance={Number(account.balance)} currency={account.currency || currency} /></td></tr>) : <tr><td colSpan={5} className="py-10 text-center text-slate-500">No debtor accounts require collection action.</td></tr>}</tbody></table></div></Panel><Panel title="Portfolio mix" subtitle="Exposure by city-ledger account type"><div className="space-y-3">{Object.entries(focusAccounts.reduce<Record<string, number>>((result, account) => { result[account.type] = (result[account.type] || 0) + Number(account.balance); return result; }, {})).map(([type, amount]) => <div key={type}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-400">{type}</span><span className="font-medium text-slate-200">{money(amount, currency)}</span></div><div className="h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-violet-400" style={{ width: `${totalOutstanding ? amount / totalOutstanding * 100 : 0}%` }} /></div></div>)}{!focusAccounts.length && <p className="text-sm text-slate-500">No balance mix to display.</p>}<div className="mt-5 rounded-xl border border-cyan-400/15 bg-cyan-400/[.05] p-3 text-xs leading-5 text-cyan-100"><Sparkles className="mr-1 inline h-4 w-4" />Use account drill-down for statement review, invoice allocation, and payment history.</div></div></Panel></section>

        <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]" id="invoices"><Panel title="Open invoice register" subtitle="Invoice-level ageing, due dates, and outstanding exposure" action={<Link href="/accountant/reports" className="text-xs text-slate-400 hover:text-white">Reports <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}><div className="overflow-x-auto"><table className="w-full min-w-[730px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="pb-3 font-medium">Invoice</th><th className="pb-3 font-medium">Account</th><th className="pb-3 font-medium">Due</th><th className="pb-3 font-medium">Age</th><th className="pb-3 text-right font-medium">Outstanding</th></tr></thead><tbody className="divide-y divide-white/[.07]">{openRows.slice(0, 8).map(row => <tr key={row.invoice.id}><td className="py-4"><span className="font-medium text-slate-200">{row.invoice.invoiceNumber}</span><span className="mt-1 block text-xs text-slate-500">{row.invoice.description}</span></td><td className="py-4 text-slate-400">{row.invoice.account.name}</td><td className={`py-4 ${row.overdue ? 'text-rose-300' : 'text-slate-400'}`}>{date(row.invoice.dueDate)}</td><td className="py-4"><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold ${row.overdue ? 'border-rose-400/20 bg-rose-400/10 text-rose-300' : 'border-emerald-400/20 bg-emerald-400/10 text-emerald-300'}`}>{row.days}d</span></td><td className="py-4 text-right font-semibold text-slate-100">{money(Number(row.invoice.outstandingAmount), row.invoice.currency || currency)}</td></tr>)}{!openRows.length && <tr><td colSpan={5} className="py-10 text-center text-slate-500">No open invoices.</td></tr>}</tbody></table></div>{openRows.length > 8 && <p className="mt-4 text-xs text-slate-500">Showing 8 of {openRows.length} open invoices. Use an account drill-down for the complete register.</p>}</Panel><Panel title="Payment activity" subtitle="Latest city-ledger receipts and reconciliation state" id="payments"><div className="space-y-1">{payments.slice(0, 7).map(payment => <div key={payment.id} className="flex items-center justify-between gap-3 border-b border-white/[.07] py-3 last:border-0"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-200">{payment.reference || payment.id.slice(0, 8)}</p><p className="mt-1 text-xs text-slate-500">{payment.account.name} · {date(payment.createdAt)}</p></div><div className="text-right"><p className="font-medium text-emerald-300">{money(Number(payment.amount), payment.currency || currency)}</p><p className={`text-[10px] ${payment.status === 'SETTLED' ? 'text-emerald-400' : 'text-amber-300'}`}>{payment.status === 'SETTLED' ? 'Applied' : 'Needs review'}</p></div></div>)}{!payments.length && <p className="py-8 text-sm text-slate-500">No payment activity recorded.</p>}</div></Panel></section>
      </div>
    </main>
  );
}

function Metric({ title, value, caption, icon: Icon, tone, href }: { title: string; value: string; caption: string; icon: React.ElementType; tone: 'cyan' | 'rose' | 'emerald' | 'amber'; href: string }) { const tones = { cyan: 'text-cyan-300 border-cyan-300/15', rose: 'text-rose-300 border-rose-300/15', emerald: 'text-emerald-300 border-emerald-300/15', amber: 'text-amber-300 border-amber-300/15' }; return <Link href={href} className={`group rounded-2xl border bg-white/[.035] p-5 transition hover:-translate-y-0.5 hover:bg-white/[.06] ${tones[tone]}`}><div className="flex items-start justify-between"><p className="text-xs font-medium uppercase tracking-wider text-slate-500">{title}</p><Icon className="h-5 w-5 opacity-80" /></div><p className="mt-5 text-2xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{caption}<ArrowUpRight className="ml-1 inline h-3 w-3 opacity-0 transition group-hover:opacity-100" /></p></Link>; }
function Panel({ title, subtitle, action, children, id }: { title: string; subtitle: string; action?: React.ReactNode; children: React.ReactNode; id?: string }) { return <section id={id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5 shadow-[0_18px_50px_rgba(0,0,0,.12)]"><div className="mb-6 flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div>{action}</div>{children}</section>; }
function ControlRow({ label, value, status }: { label: string; value: string; status: 'OK' | 'REVIEW' }) { return <div className="flex items-center justify-between gap-3 rounded-xl border border-white/[.07] bg-slate-950/30 p-3"><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-200">{value}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${status === 'OK' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-400/10 text-amber-300'}`}>{status}</span></div>; }
function Action({ href, icon: Icon, title, detail }: { href: string; icon: React.ElementType; title: string; detail: string }) { return <Link href={href} className="group flex items-center gap-3 border-b border-white/[.07] py-3 last:border-0"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[.06] text-cyan-300"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-slate-200">{title}</span><span className="mt-1 block text-xs text-slate-500">{detail}</span></span><ArrowRight className="h-4 w-4 text-slate-600 group-hover:text-cyan-300" /></Link>; }
function EmptyState({ title, message }: { title: string; message: string }) { return <div className="flex min-h-screen items-center justify-center bg-[#07111f] p-8 text-center text-slate-300"><div><FileText className="mx-auto mb-3 h-10 w-10 text-slate-500" /><h1 className="text-xl font-semibold text-white">{title}</h1><p className="mt-2 text-sm text-slate-400">{message}</p></div></div>; }
