'use client';

import { useState } from 'react';
import { Bar, BarChart, Cell, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, CheckCircle2, CircleDollarSign, CreditCard, Layers3, Package, Plus, RefreshCw, Sparkles, X } from 'lucide-react';
import { createBillingPrice as saveBillingPrice, createBillingProduct as saveBillingProduct } from './actions';

type Product = { id: string; name: string; code: string; type: string; active: boolean; flutterwaveProductId: string | null; createdAt: string; prices: { id: string; amount: number; currency: string; interval: string; flutterwavePriceId: string | null }[]; adoption: number; quantity: number; mrr: number; planCount: number; entitlementCount: number; moduleCount: number };
type Data = { generatedAt: string; catalog: Product[]; plans: { id: string; name: string; code: string; active: boolean; itemCount: number; subscriptionCount: number; products: string[] }[]; monthlyRevenue: { label: string; revenue: number; invoices: number }[]; planMix: { name: string; value: number }[]; statusMix: { name: string; value: number }[]; recentInvoices: { id: string; total: number; amountDue: number; status: string; currency: string; createdAt: string; organizationName: string }[]; metrics: Record<string, number> };

const money = (amount: number, currency = 'NGN') => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount / 100);
const tooltipStyle = { background: '#111d31', border: '1px solid rgba(255,255,255,.12)', borderRadius: 12, color: '#fff', fontSize: 11 };
const chartColors = ['#818cf8', '#34d399', '#38bdf8', '#fbbf24', '#fb7185'];

function Metric({ label, value, detail, icon: Icon, tone = 'indigo' }: { label: string; value: string | number; detail: string; icon: typeof Package; tone?: string }) { return <div className="rounded-2xl border border-white/10 bg-[#101b2f] p-4 shadow-[0_12px_34px_rgba(0,0,0,.16)]"><span className={`flex size-9 items-center justify-center rounded-xl bg-${tone}-400/10 text-${tone}-300`}><Icon className="size-4" /></span><p className="mt-4 text-[11px] font-medium uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }
function Section({ title, description, children, action }: { title: string; description: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-[#101b2f] p-5 shadow-[0_12px_34px_rgba(0,0,0,.14)]"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p></div>{action}</div>{children}</section>; }
function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020713]/80 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#101b2f] p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-indigo-300">HQ catalogue</p><h2 className="mt-1 text-lg font-semibold text-white">{title}</h2></div><button onClick={close} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white"><X className="size-4" /></button></div>{children}</div></div>; }
function SuccessDialog({ message, close }: { message: string; close: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020713]/80 p-4 backdrop-blur-sm"><div className="w-full max-w-sm rounded-2xl border border-emerald-300/20 bg-[#101b2f] p-6 text-center shadow-2xl"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-emerald-400/10 text-emerald-300"><CheckCircle2 className="size-6" /></span><p className="mt-4 text-lg font-semibold text-white">Action completed</p><p className="mt-2 text-sm leading-6 text-slate-400">{message}</p><button onClick={close} className="mt-6 w-full rounded-lg bg-emerald-500 px-4 py-2.5 text-xs font-semibold text-[#04120d] hover:bg-emerald-400">Done</button></div></div>; }
function ErrorDialog({ message, close }: { message: string; close: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020713]/80 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-rose-300/20 bg-[#101b2f] p-6 shadow-2xl"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-rose-300">Could not complete action</p><h2 className="mt-2 text-lg font-semibold text-white">Catalogue update failed</h2><p className="mt-2 text-sm leading-6 text-slate-400">{message}</p><p className="mt-3 text-xs leading-5 text-slate-500">Nothing was saved. Correct the details or check the server logs before retrying.</p><button onClick={close} className="mt-6 w-full rounded-lg border border-white/10 bg-white/[.04] px-4 py-2.5 text-xs font-semibold text-white hover:bg-white/[.08]">Close</button></div></div>; }
async function createBillingProduct(formData: FormData) { const result = await saveBillingProduct(formData); if (!result.ok) throw new Error(result.error); }
async function createBillingPrice(formData: FormData) { const result = await saveBillingPrice(formData); if (!result.ok) throw new Error(result.error); }

export default function ProductsWorkspace({ data }: { data: Data }) {
  const [dialog, setDialog] = useState<'product' | 'price' | null>(null);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const m = data.metrics;
  const actionError = (error: unknown) => error instanceof Error ? error.message : 'The server could not complete this request.';
  return <div className="min-h-full bg-[#07111f] px-4 py-6 text-slate-200 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.22em] text-indigo-300"><Sparkles className="size-3.5" /> HQ commercial control plane</div><h1 className="text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">Products & pricing</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Manage the catalogue customers buy, the plans that package it, and the live subscription economics behind the LodgeCore platform.</p></div><div className="flex items-center gap-3"><span suppressHydrationWarning className="hidden text-xs text-slate-500 sm:inline">Updated {new Date(data.generatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><button onClick={() => window.location.reload()} className="rounded-xl border border-white/10 bg-white/[.04] p-2 text-slate-400 hover:text-white" title="Refresh live data"><RefreshCw className="size-4" /></button><button onClick={() => setDialog('product')} className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-3 py-2 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20 hover:bg-indigo-400"><Plus className="size-3.5" /> New product</button></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Catalogue products" value={`${m.activeProducts}/${m.totalProducts}`} detail={`${m.pricedProducts} have published prices`} icon={Package} /><Metric label="Active plans" value={`${m.activePlans}/${m.totalPlans}`} detail="Recurring commercial packages" icon={Layers3} tone="sky" /><Metric label="Live subscriptions" value={m.activeSubscriptions} detail={`${m.totalSubscriptions} including attention states`} icon={CreditCard} tone="emerald" /><Metric label="Platform MRR" value={money(m.totalMrr)} detail={`${m.totalOrganizations} customer organisations`} icon={CircleDollarSign} tone="violet" /></div>
    <Section title="Catalogue model" description="The commercial objects used by HQ to package and sell the platform."><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-indigo-300/15 bg-indigo-300/[.06] p-4"><div className="flex items-center gap-2"><Package className="size-4 text-indigo-300" /><p className="text-xs font-semibold text-white">Product</p></div><p className="mt-2 text-xs leading-5 text-slate-400">One billable capability in the catalogue, such as the core PMS, smart access or intelligence.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wider text-indigo-300">Base or add-on</p></div><div className="rounded-xl border border-sky-300/15 bg-sky-300/[.06] p-4"><div className="flex items-center gap-2"><Layers3 className="size-4 text-sky-300" /><p className="text-xs font-semibold text-white">Plan</p></div><p className="mt-2 text-xs leading-5 text-slate-400">A commercial package that bundles one or more products for a customer subscription tier.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wider text-sky-300">Essential · Professional · Enterprise</p></div><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.06] p-4"><div className="flex items-center gap-2"><CreditCard className="size-4 text-emerald-300" /><p className="text-xs font-semibold text-white">Add-on & price</p></div><p className="mt-2 text-xs leading-5 text-slate-400">An add-on is an optional product. A price is its recurring Flutterwave charge, monthly or annual.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wider text-emerald-300">Optional expansion revenue</p></div></div></Section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Section title="Collected revenue" description="Paid billing invoices over the last six months." action={<span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[10px] font-medium text-emerald-300">Billing ledger</span>}><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthlyRevenue}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 10 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 10 }} tickFormatter={(value) => `₦${Math.round(value / 100000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [money(Number(value)), 'Collected']} /><Bar dataKey="revenue" fill="#818cf8" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Collected</p><p className="mt-1 text-lg font-semibold text-white">{money(m.collected)}</p></div><div className="rounded-xl bg-amber-400/[.06] p-3"><p className="text-[10px] uppercase tracking-wider text-amber-200/60">Outstanding</p><p className="mt-1 text-lg font-semibold text-amber-100">{money(m.outstanding)}</p></div></div></Section><Section title="Subscription mix" description="Live plans and billing states from the subscription ledger."><div className="flex items-center gap-4"><div className="h-36 w-36 shrink-0"><ResponsiveContainer><PieChart><Pie data={data.planMix.length ? data.planMix : [{ name: 'No subscriptions', value: 1 }]} dataKey="value" innerRadius={43} outerRadius={60} paddingAngle={4} stroke="none">{(data.planMix.length ? data.planMix : [{ name: 'No subscriptions', value: 1 }]).map((item, index) => <Cell key={item.name} fill={data.planMix.length ? chartColors[index % chartColors.length] : '#334155'} />)}</Pie></PieChart></ResponsiveContainer></div><div className="min-w-0 flex-1 space-y-2">{data.statusMix.map((item, index) => <div key={item.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-400"><span className="size-2 rounded-full" style={{ background: chartColors[index % chartColors.length] }} />{item.name}</span><span className="font-semibold text-white">{item.value}</span></div>)}{m.failedInvoices > 0 && <p className="mt-3 border-t border-white/8 pt-3 text-[11px] text-amber-300">{m.failedInvoices} invoice records need attention.</p>}</div></div></Section></div>
    <Section title="Product catalogue" description="Products, published prices, adoption, entitlements and recurring contribution." action={<span className="text-xs text-slate-500">{m.syncedProducts}/{m.totalProducts} synced to Flutterwave</span>}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.catalog.map((product) => <div key={product.id} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${product.type === 'ADDON' ? 'bg-amber-400/10 text-amber-300' : 'bg-indigo-400/10 text-indigo-300'}`}>{product.type === 'ADDON' ? 'Add-on' : 'Base product'}</span><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${product.active ? 'bg-emerald-400/10 text-emerald-300' : 'bg-slate-400/10 text-slate-400'}`}>{product.active ? 'Active' : 'Paused'}</span></div><p className="font-semibold text-white">{product.name}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{product.code}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 border-y border-white/8 py-3 text-center"><div><p className="text-lg font-semibold text-white">{product.adoption}</p><p className="text-[9px] uppercase tracking-wider text-slate-500">Accounts</p></div><div><p className="text-lg font-semibold text-white">{product.planCount}</p><p className="text-[9px] uppercase tracking-wider text-slate-500">Plans</p></div><div><p className="text-lg font-semibold text-white">{product.entitlementCount}</p><p className="text-[9px] uppercase tracking-wider text-slate-500">Entitled</p></div></div><div className="mt-3 flex items-center justify-between gap-3"><span className="truncate text-xs text-slate-400">{product.prices.length ? product.prices.map((price) => `${money(price.amount, price.currency.toUpperCase())}/${price.interval}`).join(' · ') : 'No live price'}</span><button onClick={() => { setSelectedProduct(product); setDialog('price'); }} className="shrink-0 text-[11px] font-medium text-indigo-300 hover:text-indigo-200">Add price</button></div>{product.mrr > 0 && <p className="mt-2 text-[11px] text-emerald-300">{money(product.mrr)} estimated MRR contribution</p>}</div>)}</div>{!data.catalog.length && <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No catalogue products exist yet.</div>}</Section>
    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Section title="Plan architecture" description="A plan is the customer-facing bundle; add-ons remain optional products outside the base tier."><div className="space-y-2">{data.plans.map((plan) => <div key={plan.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded-full bg-sky-400/10 px-2 py-1 text-[10px] font-medium text-sky-300">Plan</span><p className="text-xs font-semibold text-white">{plan.name}</p><span className="font-mono text-[10px] text-slate-600">{plan.code}</span></div><p className="mt-1 truncate text-[11px] text-slate-500">{plan.products.length ? plan.products.join(' · ') : 'No products attached'}</p></div><div className="ml-4 flex shrink-0 items-center gap-4 text-right"><div><p className="text-sm font-semibold text-white">{plan.itemCount}</p><p className="text-[9px] uppercase tracking-wider text-slate-600">Products</p></div><div><p className="text-sm font-semibold text-indigo-300">{plan.subscriptionCount}</p><p className="text-[9px] uppercase tracking-wider text-slate-600">Subscribers</p></div></div></div>)}{!data.plans.length && <p className="py-6 text-center text-sm text-slate-500">No plans configured yet.</p>}</div></Section><Section title="Latest billing activity" description="Recent invoice records from the live billing ledger." action={<a href="/hq/invoices" className="text-xs font-medium text-indigo-300 hover:text-indigo-200">View ledger <ArrowUpRight className="inline size-3" /></a>}><div className="space-y-2">{data.recentInvoices.map((invoice) => <div key={invoice.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.02] p-3"><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-200">{invoice.organizationName}</p><p className="mt-1 text-[10px] text-slate-500">{new Date(invoice.createdAt).toLocaleDateString()} · {invoice.status}</p></div><span className="text-xs font-semibold text-white">{money(invoice.total, invoice.currency)}</span></div>)}{!data.recentInvoices.length && <p className="py-8 text-center text-sm text-slate-500">No invoice activity in the ledger yet.</p>}</div></Section></div>
    {dialog === 'product' && <Dialog title="Create catalogue product" close={() => setDialog(null)}><form action={async (formData) => { try { await createBillingProduct(formData); setDialog(null); setErrorMessage(null); setSuccessMessage('The product was created in the LodgeCore catalogue.'); } catch (error) { setErrorMessage(actionError(error)); } }} className="space-y-3"><label className="block text-xs font-medium text-slate-400">Product code<input name="code" required placeholder="ADDON_SMART_ACCESS" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 text-xs uppercase text-white outline-none focus:border-indigo-400" /></label><label className="block text-xs font-medium text-slate-400">Display name<input name="name" required placeholder="Smart Access" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 text-xs text-white outline-none focus:border-indigo-400" /></label><label className="block text-xs font-medium text-slate-400">Product type<select name="type" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 text-xs text-white"><option value="ADDON">Add-on</option><option value="BASE">Base platform</option></select></label><div className="flex justify-end gap-2 pt-3"><button type="button" onClick={() => setDialog(null)} className="rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5">Cancel</button><button className="rounded-lg bg-indigo-500 px-4 py-2 text-xs font-semibold text-white">Create product</button></div></form></Dialog>}
    {dialog === 'price' && selectedProduct && <Dialog title={`Save price · ${selectedProduct.name}`} close={() => setDialog(null)}><form action={async (formData) => { try { await createBillingPrice(formData); setDialog(null); setErrorMessage(null); setSuccessMessage(`The LodgeCore catalogue price was saved for ${selectedProduct.name}.`); } catch (error) { setErrorMessage(actionError(error)); } }} className="space-y-3"><input type="hidden" name="productId" value={selectedProduct.id} /><p className="rounded-lg border border-indigo-300/15 bg-indigo-300/[.06] p-3 text-xs leading-5 text-indigo-100">This saves the LodgeCore invoice price only. Flutterwave is contacted when a customer chooses to pay an invoice.</p><label className="block text-xs font-medium text-slate-400">Amount (minor units)<input name="amount" type="number" min="1" required placeholder="5000000" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 text-xs text-white" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-medium text-slate-400">Currency<input name="currency" defaultValue="ngn" maxLength={3} required className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 text-xs uppercase text-white" /></label><label className="block text-xs font-medium text-slate-400">Interval<select name="interval" className="mt-1.5 h-10 w-full rounded-lg border border-white/10 bg-[#0b1628] px-3 py-2 text-xs text-white"><option value="month">Monthly</option><option value="year">Annual</option></select></label></div><div className="flex justify-end gap-2 pt-3"><button type="button" onClick={() => setDialog(null)} className="rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5">Cancel</button><button className="rounded-lg bg-indigo-500 px-4 py-2 text-xs font-semibold text-white">Save price</button></div></form></Dialog>}
    {successMessage && <SuccessDialog message={successMessage} close={() => setSuccessMessage(null)} />}
    {errorMessage && <ErrorDialog message={errorMessage} close={() => setErrorMessage(null)} />}
  </div></div>;
}
