'use client';

import { useState } from 'react';
import { createBillingPrice, createBillingProduct } from './actions';

type Product = { id: string; name: string; code: string; type: string; active: boolean; flutterwaveProductId: string | null; createdAt: string; prices: { id: string; amount: number; currency: string; interval: string; flutterwavePriceId: string | null }[]; adoption: number; mrr: number; planCount: number; entitlementCount: number; moduleCount: number };
type Data = { catalog: Product[]; plans: { id: string; name: string; code: string; active: boolean; itemCount: number }[]; monthlyRevenue: { label: string; revenue: number; invoices: number }[]; recentInvoices: { id: string; total: number; amountDue: number; status: string; currency: string; createdAt: string; organizationName: string }[]; metrics: { totalProducts: number; activeProducts: number; totalPlans: number; activeSubscriptions: number; totalOrganizations: number; totalMrr: number; collected: number; outstanding: number; failedInvoices: number } };

const money = (amount: number, currency = 'NGN') => new Intl.NumberFormat('en-NG', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount / 100);

function PriceForm({ productId }: { productId: string }) {
  return <form action={createBillingPrice} className="grid gap-2 rounded-lg border border-white/10 bg-white/[.03] p-3 sm:grid-cols-4"><input type="hidden" name="productId" value={productId} /><input name="amount" type="number" min="1" required placeholder="5000000" className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs text-white" /><input name="currency" defaultValue="ngn" maxLength={3} required className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs uppercase text-white" /><select name="interval" className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs text-white"><option value="month">Monthly</option><option value="year">Annual</option></select><button className="rounded bg-indigo-500 px-3 text-xs font-semibold text-white">Publish price</button></form>;
}

export default function ProductsWorkspace({ data }: { data: Data }) {
  const [showProductForm, setShowProductForm] = useState(false);
  return <div className="space-y-6">
    <div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-white">Flutterwave catalogue</h2><p className="mt-1 text-xs text-slate-400">Products, recurring payment plans, and entitlement coverage.</p></div><button onClick={() => setShowProductForm((value) => !value)} className="rounded-lg bg-indigo-500 px-3 py-2 text-xs font-semibold text-white">{showProductForm ? 'Close' : 'Create product'}</button></div>
    {showProductForm && <form action={createBillingProduct} className="grid gap-2 rounded-xl border border-white/10 bg-[#101b2f] p-4 sm:grid-cols-3"><input name="code" required placeholder="ADDON_SMART_ACCESS" className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs uppercase text-white" /><input name="name" required placeholder="Smart Access" className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs text-white" /><select name="type" className="h-9 rounded border border-white/10 bg-[#0b1628] px-2 text-xs text-white"><option value="ADDON">Add-on</option><option value="BASE">Base</option></select><button className="rounded bg-indigo-500 px-3 py-2 text-xs font-semibold text-white sm:col-span-3">Create Flutterwave product</button></form>}
    <div className="overflow-x-auto rounded-xl border border-white/10 bg-[#101b2f]"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/10 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Product</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Prices</th><th className="px-3 py-3">Coverage</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-white/10">{data.catalog.map((product) => <tr key={product.id}><td className="px-5 py-4"><p className="font-semibold text-white">{product.name}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{product.code} · {product.flutterwaveProductId ? 'Flutterwave configured' : 'Local product'}</p></td><td className="px-3 py-4 text-slate-300">{product.type}</td><td className="px-3 py-4"><div className="space-y-2">{product.prices.map((price) => <div key={price.id} className="text-xs text-slate-300">{money(price.amount, price.currency.toUpperCase())} / {price.interval}<span className="ml-2 text-[10px] text-emerald-300">{price.flutterwavePriceId ? 'Payment plan set' : 'Pending'}</span></div>)}<PriceForm productId={product.id} /></div></td><td className="px-3 py-4 text-xs text-slate-400">{product.planCount} plans · {product.entitlementCount} entitlements</td><td className="px-5 py-4 text-right text-xs text-slate-500">{product.adoption} organizations</td></tr>)}</tbody></table></div>
  </div>;
}
