
[String]
; main window items
IDD102_Title=Intelligent Lock Extension Tools
IDD102_1000=Enable Extended sector_1
IDD102_1008=Sector:
IDD102_1009=KeyA:
IDD102_1010=12 characters(0~9,A~F)
IDD102_1001=Enable extended sector_2(Hooks)
IDD102_1011=Sector:
IDD102_1012=KeyA:
IDD102_1013=12 characters(0~9,A~F)
IDD102_1006=Automatically initialize card
IDD102_1=Save
IDD102_2=Cancel

; strings 
IDS_VERIFY_ERROR=Verification failed !
IDS_STRKEYA_ERR1=The length of KeyA_1 is invalid!
IDS_STRKEYA_ERR2=The length of KeyA_2 is invalid!
IDS_STRSAVE_OK=Saved Successfully !