"use client";

import Link from "next/link";
import { useState } from "react";
import SubscriptionCatalogue from "./SubscriptionCatalogue";

type SubscriptionData = { status: string; planName: string; planCode: string | null; periodStart: string; periodEnd: string; cancelAtPeriodEnd: boolean; trialEndsAt: string | null; items: { name: string; code: string; includedQty: number | null; required: boolean }[] } | null;
type Props = { data: { subscription: SubscriptionData; entitlements: { id: string; name: string; code: string; propertyName: string; expiresAt: string | null }[]; properties: { id: string; name: string; isActive: boolean; ready: boolean }[]; invoices: { id: string; status: string; currency: string; total: number; amountPaid: number; amountDue: number; periodStart: string | null; periodEnd: string | null; hostedInvoiceUrl: string | null; invoicePdf: string | null; createdAt: string }[]; projects: { id: string; name: string; status: string; targetGoLiveAt: string | null; createdAt: string }[]; latestInvoiceStatus: string | null; metrics: { activeProperties: number; totalProperties: number; readyProperties: number; activeEntitlements: number; openProjects: number; invoiceDue: number; failedInvoices: number } }; plans: any[]; addOns: any[]; checkoutProperties: { id: string; name: string }[] };

const money = (value: number, currency: string) => new Intl.NumberFormat("en-NG", { style: "currency", currency: currency.toUpperCase(), maximumFractionDigits: 0 }).format(value / 100);
const statusClass = (status: string) => { const value = status.toUpperCase(); return value === "ACTIVE" || value === "PAID" || value === "COMPLETED" ? "badge-active" : ["PAST_DUE", "FAILED", "UNCOLLECTIBLE"].includes(value) ? "badge-urgent" : "badge-pending"; };

export default function SubscriptionWorkspace({ data, plans, addOns, checkoutProperties }: Props) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const daysRemaining = data.subscription ? Math.max(0, Math.ceil((new Date(data.subscription.periodEnd).getTime() - Date.now()) / 86400000)) : 0;
  const billingCurrency = data.invoices[0]?.currency || "NGN";
  async function requestBillingSupport() { setBusy(true); setError(null); try { const response = await fetch("/api/billing/portal", { method: "POST" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "Billing support is currently unavailable"); if (payload.url) window.location.assign(payload.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Billing support is currently unavailable"); setBusy(false); } }

  return <div>
    <div className="portal-page-header"><div><div className="portal-page-kicker">Customer workspace · commercial control</div><h1 className="portal-page-title">Subscription</h1><p className="portal-page-sub" style={{ marginBottom: 0 }}>One workspace for your plan, enabled modules, property scope and billing health.</p></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Link href="/portal/billing" className="btn btn-outline btn-sm">Open billing →</Link><button className="btn btn-primary btn-sm" onClick={requestBillingSupport} disabled={busy}>{busy ? "Contacting team…" : "Billing support →"}</button></div></div>
    {error && <div className="portal-card" role="alert" style={{ marginBottom: 18, color: "var(--danger, #ff5f72)", borderColor: "rgba(255,95,114,.3)" }}>{error}</div>}
    <section style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 20 }}><Metric label="Current plan" value={data.subscription?.planName ?? "No plan"} note={data.subscription ? data.subscription.status : "Choose a plan to begin"} tone="accent" /><Metric label="Properties" value={`${data.metrics.activeProperties}/${data.metrics.totalProperties}`} note={`${data.metrics.readyProperties} lifecycle-ready`} tone="mint" /><Metric label="Modules" value={String(data.metrics.activeEntitlements)} note="Active entitlements" tone="violet" /><Metric label="Billing health" value={data.metrics.failedInvoices ? `${data.metrics.failedInvoices} review` : "Clear"} note={data.metrics.invoiceDue ? `${money(data.metrics.invoiceDue, billingCurrency)} due` : "No open balance"} tone={data.metrics.failedInvoices ? "amber" : "mint"} /></section>
    <section className="portal-card" style={{ marginBottom: 20, position: "relative", overflow: "hidden" }}><div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: data.subscription?.status === "PAST_DUE" ? "var(--red, #ff5f72)" : "var(--accent)" }} /><div style={{ display: "flex", justifyContent: "space-between", gap: 18, alignItems: "flex-start", flexWrap: "wrap" }}><div><div className="portal-card-title" style={{ display: "flex", alignItems: "center", gap: 10 }}>Current subscription {data.subscription && <span className={`portal-badge ${statusClass(data.subscription.status)}`}>{data.subscription.status}</span>}</div><p style={{ marginTop: 8, color: "var(--text-muted)", fontSize: 13, lineHeight: 1.7 }}>{data.subscription ? `Your ${data.subscription.planName} access is active for this billing period.` : "Your organization has not selected a subscription plan yet."}</p></div>{data.subscription && <div style={{ textAlign: "right" }}><div className="portal-stat-label">Current period ends</div><div className="portal-stat-value" style={{ fontSize: "1.15rem" }}>{new Date(data.subscription.periodEnd).toLocaleDateString("en-GB")}</div><div style={{ color: "var(--text-muted)", fontSize: 11, marginTop: 4 }}>{daysRemaining} days remaining</div></div>}</div>{data.subscription && <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginTop: 22, paddingTop: 18, borderTop: "1px solid var(--border)" }}><div><div className="portal-stat-label">Plan code</div><div style={{ color: "var(--accent)", fontFamily: "var(--font-mono)", fontSize: 12 }}>{data.subscription.planCode || "CUSTOM"}</div></div><div><div className="portal-stat-label">Renewal</div><div style={{ color: "var(--text-primary)", fontSize: 13 }}>{data.subscription.cancelAtPeriodEnd ? "Scheduled to end" : "Managed by LodgeCore billing"}</div></div><div><div className="portal-stat-label">Scope</div><div style={{ color: "var(--text-primary)", fontSize: 13 }}>{data.metrics.activeProperties} active properties</div></div></div>}{data.subscription?.status === "PAST_DUE" && <div style={{ marginTop: 18, padding: 14, borderRadius: 10, background: "rgba(255,95,114,.08)", border: "1px solid rgba(255,95,114,.22)", color: "var(--text-secondary)", fontSize: 13 }}>Your payment is past due. Use Billing to view the outstanding invoice and contact the LodgeCore finance team for payment-method changes.</div>}</section>
    <section style={{ display: "grid", gridTemplateColumns: "1.1fr .9fr", gap: 16, marginBottom: 20 }}><div className="portal-card"><div className="portal-card-title" style={{ marginBottom: 12 }}>Access coverage</div><p style={{ color: "var(--text-muted)", fontSize: 13, lineHeight: 1.7, marginBottom: 16 }}>The modules and capabilities currently active for your organization.</p>{data.entitlements.length ? <div style={{ display: "grid", gap: 8 }}>{data.entitlements.slice(0, 6).map((entitlement) => <div key={entitlement.id} style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center", padding: "10px 12px", border: "1px solid var(--border)", borderRadius: 9 }}><div><div style={{ color: "var(--text-primary)", fontSize: 13, fontWeight: 600 }}>{entitlement.name}</div><div style={{ color: "var(--text-muted)", fontSize: 11, marginTop: 3 }}>{entitlement.propertyName} · {entitlement.code}</div></div><span className="portal-badge badge-active">Active</span></div>)}</div> : <p style={{ color: "var(--text-muted)", fontSize: 13 }}>No active entitlements yet.</p>}</div><div className="portal-card"><div className="portal-card-title" style={{ marginBottom: 12 }}>Implementation readiness</div>{data.projects.length ? <div style={{ display: "grid", gap: 10 }}>{data.projects.slice(0, 3).map((project) => <div key={project.id}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, fontSize: 12, color: "var(--text-primary)" }}><span>{project.name}</span><span className={`portal-badge ${statusClass(project.status)}`}>{project.status}</span></div>{project.targetGoLiveAt && <div style={{ color: "var(--text-muted)", fontSize: 11, marginTop: 5 }}>Target go-live {new Date(project.targetGoLiveAt).toLocaleDateString("en-GB")}</div>}</div>)}</div> : <p style={{ color: "var(--text-muted)", fontSize: 13, lineHeight: 1.7 }}>Implementation projects will appear here after your organization is provisioned.</p>}<Link href="/portal/implementation" className="btn btn-outline btn-sm" style={{ marginTop: 18 }}>Open implementation →</Link></div></section>
    <section className="portal-card" style={{ marginBottom: 22 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "end", flexWrap: "wrap", marginBottom: 12 }}><div><div className="portal-page-kicker">Financial record</div><div className="portal-card-title">Recent invoices</div><p style={{ color: "var(--text-muted)", fontSize: 13, marginTop: 5 }}>Provider-confirmed billing records for this organization.</p></div><Link href="/portal/billing" className="btn btn-outline btn-sm">View all billing →</Link></div>{data.invoices.length ? <div className="portal-table-wrap" style={{ border: "none" }}><table className="portal-table"><thead><tr><th>Created</th><th>Status</th><th>Period</th><th>Total</th><th>Due</th><th /></tr></thead><tbody>{data.invoices.slice(0, 5).map((invoice) => <tr key={invoice.id}><td>{new Date(invoice.createdAt).toLocaleDateString("en-GB")}</td><td><span className={`portal-badge ${statusClass(invoice.status)}`}>{invoice.status}</span></td><td>{invoice.periodEnd ? new Date(invoice.periodEnd).toLocaleDateString("en-GB") : "—"}</td><td>{money(invoice.total, invoice.currency)}</td><td style={{ color: invoice.amountDue ? "var(--amber)" : "var(--mint)" }}>{invoice.amountDue ? money(invoice.amountDue, invoice.currency) : "Paid"}</td><td>{(invoice.invoicePdf || invoice.hostedInvoiceUrl) && <a className="btn btn-outline btn-sm" href={invoice.invoicePdf || invoice.hostedInvoiceUrl || "#"} target="_blank" rel="noreferrer">View</a>}</td></tr>)}</tbody></table></div> : <p style={{ color: "var(--text-muted)", fontSize: 13, lineHeight: 1.7 }}>Invoices will appear after Flutterwave confirms your first billing cycle.</p>}</section>
    <SubscriptionCatalogue plans={plans} addOns={addOns} properties={checkoutProperties} />
  </div>;
}

function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone: "accent" | "mint" | "violet" | "amber" }) { return <div className="portal-card" style={{ padding: "16px 18px" }}><div className="portal-stat-label">{label}</div><div className={`portal-stat-value ${tone}`} style={{ fontSize: "1.35rem", marginTop: 8 }}>{value}</div><div style={{ color: "var(--text-muted)", fontSize: 11, marginTop: 5 }}>{note}</div></div>; }
