"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const views = {
  "Front Desk": ["Arrivals 18", "Departures 11", "Rooms ready 126", "Room rack"],
  Reservations: ["Today 24", "Waitlist 11", "Direct 42%", "Rate calendar"],
  POS: ["Restaurant ₦428,500", "Open checks 24", "Kitchen tickets 38", "Outlet performance"],
  Finance: ["Today ₦4.8m", "Reconciled 98%", "City ledger ₦2.1m", "Night audit ready"],
  Accounting: ["Folio postings 184", "Cash control ₦1.2m", "AR ₦2.1m", "Reconciliation"],
  Housekeeping: ["Ready 126", "In progress 12", "Inspected 84", "Maintenance 6"],
  Analytics: ["Occupancy 84.6%", "ADR ₦82,400", "RevPAR ₦69,700", "Three properties"],
};
const products = ["Property Management", "Point of Sale", "Housekeeping", "Accounting", "Events", "Analytics", "Payments", "Hardware"];
const properties = ["Boutique hotels", "Business hotels", "Resorts", "Luxury hotels", "Serviced apartments", "Lodges", "Restaurants", "Event venues", "Multi-property groups"];

function Button({ children, secondary = false, href = "/book-demo" }: { children: React.ReactNode; secondary?: boolean; href?: string }) {
  return <Link href={href} className={`inline-flex items-center justify-center rounded-full px-5 py-3 text-sm font-bold transition hover:-translate-y-0.5 ${secondary ? "border border-slate-300/30 text-white hover:border-sky-300" : "bg-sky-300 text-[#07111f] hover:bg-white"}`}>{children}</Link>;
}

export default function WebsiteHome() {
  const [view, setView] = useState<keyof typeof views>("Front Desk");
  const [plans, setPlans] = useState<{ name: string; description: string | null }[]>([]);
  useEffect(() => { fetch("/api/catalog").then((r) => r.ok ? r.json() : null).then((d) => setPlans(d?.plans ?? [])).catch(() => undefined); }, []);
  const cards = views[view];
  return <main className="home-shell overflow-hidden">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
      <Link href="/" className="text-xl font-black tracking-tight text-[#07111f]">Lodge<span className="text-[#1677c8]">Core</span></Link>
      <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 lg:flex"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#hardware">Hardware</a><a href="#integrations">Integrations</a><Link href="/pricing">Pricing</Link></nav>
      <div className="flex items-center gap-3"><Link href="/portal" className="hidden text-sm font-semibold text-slate-600 sm:block">Sign in</Link><Button>Book a demo</Button></div>
    </div></header>

    <section className="hero-grid mx-auto grid max-w-7xl gap-14 px-5 pb-24 pt-20 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-8 lg:pt-28">
      <div><p className="eyebrow">The hotel operating platform</p><h1 className="hero-title">Everything your hotel needs to operate.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">LodgeCore connects your front desk, rooms, restaurants, reservations, payments, finance, guests and hotel hardware in one powerful platform.</p><div className="mt-9 flex flex-wrap gap-3"><Button>Book a demo</Button><Button secondary href="#platform">Explore the platform</Button></div><p className="mt-7 text-sm font-medium text-slate-500">Built for modern hotels. Designed for uninterrupted operations.</p></div>
      <div className="command-window"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-slate-400">Property command center</p><p className="mt-1 font-semibold text-white">LodgeCore / Today</p></div><span className="status">● All systems live</span></div><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-4">{[["Occupancy","84.6%"],["Revenue","₦4.8m"],["Arrivals","18"],["Rooms ready","126"]].map(([a,b])=><div className="metric" key={a}><span>{a}</span><strong>{b}</strong><small>Operational view</small></div>)}</div><div className="grid gap-3 px-5 pb-5 sm:grid-cols-[1.15fr_.85fr]"><div className="panel"><p className="panel-label">Room operations</p>{["204 · Checked in · Deluxe","118 · Ready · Standard","306 · Cleaning · Suite","412 · Maintenance · King"].map((x,i)=><div className="room-row" key={x}><span className={`dot d${i}`}/>{x}<b>{i === 0 ? "Guest" : i === 1 ? "Ready" : "Task"}</b></div>)}</div><div className="panel"><p className="panel-label">Live activity</p><p className="activity">✓ Payment received <small>2 min ago</small></p><p className="activity">✓ Housekeeping · 12 ready <small>8 min ago</small></p><p className="activity">✓ Night audit · Ready <small>Today</small></p></div></div><div className="float-note note-one">Restaurant <b>₦428,500 today</b></div><div className="float-note note-two">Payment received <b>Folio #LC-204</b></div></div>
    </section>

    <section id="platform" className="dark-section px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="eyebrow">The hotel operating system</p><h2 className="section-title">One platform. Every department.</h2><p className="section-copy">The operational backbone connecting the people, processes and systems that keep a property moving.</p></div><div className="ecosystem mt-16"><div className="orbit-center">LODGE<span>CORE</span><small>Connected operations</small></div>{["Front Desk","Reservations","Housekeeping","POS & F&B","Finance","Guests","E-Locks","Analytics"].map((x,i)=><div className={`orbit-node n${i}`} key={x}>{x}</div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="eyebrow">See the product</p><h2 className="section-title dark-title">Run the property from one place.</h2><p className="section-copy text-slate-600">Purpose-built workflows for the rooms, outlets and teams that make hospitality work.</p><div className="mt-10 flex flex-wrap gap-2">{Object.keys(views).map((x) => <button className={`tab ${view === x ? "active" : ""}`} onClick={() => setView(x as keyof typeof views)} key={x}>{x}</button>)}</div><div className="product-screen mt-5"><div className="screen-top"><span>● LodgeCore</span><span>Operations / {view}</span><span>Today · 09:42</span></div><div className="grid gap-5 p-5 md:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs uppercase tracking-widest text-slate-400">{view} overview</p><h3 className="mt-2 text-2xl font-bold text-white">Everything in context.</h3><div className="mt-7 space-y-3">{cards.map((x,i)=><div className="screen-card" key={x}><span className="screen-icon">{String(i+1).padStart(2,"0")}</span><div><b>{x}</b><small>Live operational data</small></div><span className="text-sky-300">↗</span></div>)}</div></div><div className="screen-chart"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-white">Performance overview</span><span className="text-xs text-emerald-300">↑ 8.2%</span></div><div className="bars">{[36,51,42,67,58,74,62,88,71,95,81,100].map((h,i)=><i style={{height:`${h}%`}} className={i>8 ? "bright" : ""} key={i}/>)}</div><div className="flex justify-between text-xs text-slate-500"><span>Mon</span><span>Today</span></div></div></div></div></section>

    <section className="dark-section px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Offline-first operations</p><h2 className="section-title">Your hotel doesn&apos;t stop when the internet does.</h2><p className="section-copy">LodgeCore desktop Front Desk and POS keep essential operations available offline, then synchronize securely when connectivity returns.</p><div className="mt-10 space-y-4">{["Connection available · LodgeCore operating normally","Connection lost · Front Desk + POS continue","Connection restored · Secure synchronization"].map((x,i)=><div className="offline-step" key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div></div><div className="offline-visual"><div className="signal">SYNC <span>↔</span> READY</div><div className="offline-grid">{["Reservations","Check-in / out","POS transactions","Room operations","Payments","Guest profiles"].map(x=><div key={x}>✓ {x}</div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-2xl"><p className="eyebrow">One guest journey</p><h2 className="section-title text-[#07111f]">One guest. One connected journey.</h2><p className="section-copy text-slate-600">From the first booking to a reconciled folio, every handoff stays visible.</p></div><div className="journey mt-14">{["Booking Engine","Reservation","Front Desk","E-lock / Key card","Restaurant POS","Housekeeping","Payment + Accounting"].map((x,i)=><div className="journey-step" key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b>{i<6 && <i>→</i>}</div>)}</div></section>

    <section id="hardware" className="blue-section px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Hardware + e-locks</p><h2 className="section-title">Software that connects to the physical hotel.</h2><p className="section-copy">From electronic locks and key cards to POS hardware, LodgeCore connects the software your team uses with the infrastructure your guests experience.</p><div className="mt-8 flex flex-wrap gap-2">{["E-Locks","RFID key cards","Encoders","Door access","POS terminals","Kitchen printers"].map(x=><span className="hardware-pill" key={x}>{x}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Button href="/hardware">Explore hotel hardware</Button><Button secondary href="/hardware/request">Book an installation</Button></div></div><div className="hardware-card"><div className="door-visual"><span>LC</span></div><p className="mt-6 text-xs uppercase tracking-widest text-sky-200">Deployment lifecycle</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm text-white">{["Survey","Selection","Installation","Configuration","Testing","Training"].map(x=><div key={x}>✓ {x}</div>)}</div></div></div></section>

    <section id="solutions" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="eyebrow">Built around your operation</p><h2 className="section-title dark-title">Built for the way your property operates.</h2><div className="property-grid mt-10">{properties.map((x,i)=><div className={`property p${i}`} key={x}><span>0{i+1}</span><h3>{x}</h3><p>Flexible workflows for the teams and service model behind every stay.</p></div>)}</div></section>

    <section className="dark-section px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="eyebrow">Multi-property control</p><h2 className="section-title">One platform for every property.</h2><p className="section-copy">Centralize performance, finance and standards while each hotel keeps the tools it needs to operate day to day.</p></div><div className="group-board"><div className="flex justify-between border-b border-white/10 pb-4 text-sm"><b className="text-white">LodgeCore Corporate</b><span className="text-sky-300">5 properties connected</span></div>{["Lagos · 84% occupancy · ₦4.8m","Abuja · 78% occupancy · ₦3.2m","Port Harcourt · 91% occupancy · ₦2.7m","Accra · 82% occupancy · ₦3.9m","Nairobi · 76% occupancy · ₦2.1m"].map(x=><div className="group-row" key={x}>{x}<span>View property →</span></div>)}</div></div></section>

    <section id="integrations" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="eyebrow">Integrations</p><h2 className="section-title dark-title">Connect the systems you already use.</h2><div className="integration-grid mt-10">{["Payments","OTAs","Channel managers","Accounting","E-Locks","POS hardware","Communication","APIs"].map(x=><Link href="/integrations" className="integration" key={x}><span>✦</span><b>{x}</b><small>Explore connections →</small></Link>)}</div></section>

    <section className="trust-section border-y border-slate-200 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow">Reliability by design</p><h2 className="section-title text-[#07111f]">Built for hotel operations you can&apos;t afford to interrupt.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Role-based access","Audit trails","Secure authentication","Offline synchronization","Backups","Operational resilience","Multi-property controls","Clear permissions"].map(x=><div className="trust-card" key={x}>✓ <b>{x}</b><p>Designed into the operating workflow.</p></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="eyebrow">Product depth</p><h2 className="section-title dark-title">More than a PMS.</h2><div className="product-grid mt-10">{products.map((x,i)=><Link href="/platform/pms" className="product-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Reservations, rooms, guests and front desk.","Restaurant, bar, pool and outlet operations.","Room status and operational coordination.","Revenue, payments and financial reporting."][i%4]}</p><b>Explore product →</b></Link>)}</div></section>

    <section className="price-section px-5 py-20 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">Plans from the control plane</p><h2 className="section-title text-[#07111f]">Choose the plan that fits your property.</h2><p className="section-copy text-slate-600">Pricing and included modules are managed centrally and update as the catalog evolves.</p></div><Button href="/pricing">View pricing →</Button></div><div className="mt-10 grid gap-4 md:grid-cols-3">{(plans.length ? plans : [{name:"Starter",description:"PMS, reservations and front desk."},{name:"Professional",description:"Connected operations for growing properties."},{name:"Enterprise",description:"Multi-property, APIs and dedicated support."}]).map(p=><div className="price-card" key={p.name}><h3>{p.name}</h3><p>{p.description}</p><Link href="/pricing">View plan →</Link></div>)}</div></section>

    <section className="final-cta px-5 py-28 text-center lg:px-8"><p className="eyebrow">Ready when you are</p><h2 className="mx-auto mt-4 max-w-3xl text-5xl font-black tracking-[-.05em] text-white sm:text-7xl">Run your hotel with LodgeCore.</h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-slate-300">One platform for rooms, reservations, restaurants, finance, guests, payments and operations.</p><div className="mt-9 flex justify-center gap-3"><Button>Book a demo</Button><Button secondary href="/start-trial">Start with LodgeCore</Button></div></section>
    <footer className="footer px-5 py-12 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row"><div><Link href="/" className="text-xl font-black text-white">Lodge<span className="text-sky-300">Core</span></Link><p className="mt-3 text-sm text-slate-400">Everything. One App.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-3 text-sm text-slate-400 sm:grid-cols-4"><Link href="#platform">Platform</Link><Link href="#solutions">Solutions</Link><Link href="#hardware">Hardware</Link><Link href="/documentation">Documentation</Link><Link href="/help">Help centre</Link><Link href="/security">Security</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div><div className="mx-auto mt-12 max-w-7xl border-t border-white/10 pt-5 text-xs text-slate-500">© {new Date().getFullYear()} LodgeCore. Hospitality operations, connected.</div></footer>
  </main>;
}
