import Link from "next/link";

const modules = [
  ["PMS", "Reservations, front desk, guest profiles and room operations."],
  ["POS & F&B", "Restaurants, bars, kitchens and room charges in one folio."],
  ["Booking engine", "Convert direct demand and keep every channel in sync."],
  ["Finance", "Accounting, night audit, cash control and live reporting."],
  ["Housekeeping", "Room status, tasks and maintenance with less friction."],
  ["E-locks", "Smart access, encoders and installation through one partner."],
];

export default function WebsiteHome() {
  return <main className="site-grid min-h-screen overflow-hidden">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6">
      <Link href="/" className="text-xl font-bold tracking-tight text-white">Lodge<span className="text-sky-300">Core</span></Link>
      <nav className="hidden gap-7 text-sm text-slate-400 md:flex"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#integrations">Integrations</a><Link href="/pricing">Pricing</Link></nav>
      <div className="flex items-center gap-3"><Link href="/portal" className="hidden text-sm text-slate-300 sm:block">Customer login</Link><Link href="/book-demo" className="rounded-full bg-sky-300 px-4 py-2 text-sm font-bold text-[#07111f]">Book a demo</Link></div>
    </header>
    <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-28 pt-20 lg:grid-cols-2 lg:items-center lg:pt-32">
      <div><p className="mb-6 text-xs font-bold uppercase tracking-[.24em] text-sky-300">The operating system for modern hotels</p><h1 className="max-w-3xl text-5xl font-bold leading-[1.04] tracking-[-.06em] text-white sm:text-7xl">Every part of your hotel, <span className="text-sky-300">working together.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">LodgeCore connects rooms, restaurants, payments, people and performance in one intelligent hotel platform.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/book-demo" className="rounded-full bg-sky-300 px-5 py-3 text-sm font-bold text-[#07111f]">Book a demo →</Link><Link href="/platform/pms" className="rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white">Explore the platform</Link></div><div className="mt-10 flex flex-wrap gap-5 text-xs text-slate-500"><span>✓ Enterprise-ready</span><span>✓ Offline-first operations</span><span>✓ Built for every property</span></div></div>
      <div className="glass rounded-3xl p-4 shadow-2xl shadow-sky-950/30"><div className="rounded-2xl bg-[#091525] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-slate-500">Property overview</p><p className="mt-2 text-xl font-semibold text-white">LodgeCore / Today</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-[10px] font-bold text-emerald-300">● All systems live</span></div><div className="mt-8 grid grid-cols-3 gap-3">{[["Occupancy", "84.6%", "↑ 8.2%"], ["Revenue", "₦4.8m", "3 properties"], ["Rooms ready", "126/148", "22 in progress"]].map(([label, value, note]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.04] p-3"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-3 text-lg font-bold text-white">{value}</p><p className="mt-1 text-[10px] text-sky-300">{note}</p></div>)}</div><div className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="flex h-32 items-end gap-2">{[35,50,42,65,58,78,60,88,72,94,84,100].map((height, i) => <div key={i} className={`flex-1 rounded-t ${i > 8 ? "bg-sky-300" : "bg-sky-300/25"}`} style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex justify-between text-[10px] text-slate-500"><span>Revenue performance</span><span>Last 7 days</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 p-3 text-xs text-slate-300">Night audit<br /><span className="text-emerald-300">Completed · 04:12</span></div><div className="rounded-xl border border-white/10 p-3 text-xs text-slate-300">Payments<br /><span className="text-emerald-300">All reconciled</span></div></div></div></div>
    </section>
    <section id="platform" className="border-y border-white/10 bg-[#091626] px-6 py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">One connected platform</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-tight text-white">The details that make a stay exceptional.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([title, copy]) => <Link href={`/platform/${title.toLowerCase().replaceAll(" ", "-").replace("&", "and")}`} key={title} className="glass rounded-2xl p-6 transition hover:-translate-y-1 hover:border-sky-300/40"><div className="mb-8 h-10 w-10 rounded-xl bg-sky-300/10 p-3 text-sky-300">✦</div><h3 className="font-bold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{copy}</p><p className="mt-6 text-xs font-bold text-sky-300">Learn more →</p></Link>)}</div></div></section>
    <section id="solutions" className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">Made for your operation</p><h2 className="mt-4 text-4xl font-bold tracking-tight text-white">Start with one property. Grow without changing systems.</h2><p className="mt-5 leading-7 text-slate-400">From boutique hotels to multi-property groups, LodgeCore keeps the operating model consistent while the control plane manages plans, entitlements and usage.</p></div><div className="glass rounded-3xl p-7"><div className="grid grid-cols-2 gap-3 text-sm">{["Boutique hotels", "Resorts", "Restaurants", "Serviced apartments", "Event venues", "Multi-property groups"].map((item) => <div key={item} className="rounded-xl border border-white/10 p-4 text-slate-300">{item}</div>)}</div></div></div></section>
    <section id="integrations" className="border-y border-white/10 bg-[#091626] px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">An open ecosystem</p><h2 className="mt-4 text-3xl font-bold text-white">Connect the tools your team already trusts.</h2><div className="mt-8 flex flex-wrap gap-2">{["Paystack", "Flutterwave", "Booking.com", "Expedia", "WhatsApp", "Dormakaba", "Salto", "API access"].map((item) => <Link href={`/integrations/${item.toLowerCase().replaceAll(".", "").replaceAll(" ", "-")}`} key={item} className="rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300">{item}</Link>)}</div></div></section>
    <section className="mx-auto max-w-3xl px-6 py-28 text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">Ready when you are</p><h2 className="mt-4 text-5xl font-bold tracking-tight text-white">Run a better hotel, from one connected place.</h2><p className="mt-5 leading-7 text-slate-400">Tell us about your property and we&apos;ll show you how LodgeCore can help.</p><Link href="/book-demo" className="mt-8 inline-block rounded-full bg-sky-300 px-6 py-3 text-sm font-bold text-[#07111f]">Book a demo →</Link></section>
    <footer className="border-t border-white/10 px-6 py-8 text-center text-xs text-slate-500">© {new Date().getFullYear()} LodgeCore · <Link href="/security">Security</Link> · <Link href="/privacy">Privacy</Link> · <Link href="/portal">Customer portal</Link></footer>
  </main>;
}
