ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'UNIT';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'EACH';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'TONNE';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'GALLON';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'PAIR';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'SET';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'DOZEN';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'CAN';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'JAR';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'TIN';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'SACHET';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'CARTON';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'CASE';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'PALLET';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'BAG';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'BUNDLE';
ALTER TYPE "UnitOfMeasure" ADD VALUE IF NOT EXISTS 'ROLL';

CREATE TABLE IF NOT EXISTS "StockItemUnit" (
  "id" UUID NOT NULL,
  "stockItemId" UUID NOT NULL,
  "unit" "UnitOfMeasure" NOT NULL,
  "unitsInBase" DECIMAL(18,6) NOT NULL,
  "barcode" TEXT,
  "isPurchaseUnit" BOOLEAN NOT NULL DEFAULT false,
  "isIssueUnit" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL,
  CONSTRAINT "StockItemUnit_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "StockItemUnit_stockItemId_fkey" FOREIGN KEY ("stockItemId") REFERENCES "StockItem"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "StockItemUnit_stockItemId_unit_key" ON "StockItemUnit"("stockItemId", "unit");

ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "conversionToBase" DECIMAL(18,6) NOT NULL DEFAULT 1;
ALTER TABLE "GoodsReceivedNoteItem" ADD COLUMN IF NOT EXISTS "baseReceivedQty" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "GoodsReceivedNoteItem" ADD COLUMN IF NOT EXISTS "baseUnitCost" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "StockTransferItem" ADD COLUMN IF NOT EXISTS "baseQuantity" DECIMAL(18,4) NOT NULL DEFAULT 0;
